google/go-containerregistry

name/repository.go
name/repository_test.go
name/tag.go
name/tag_test.go

Export Jon's change from the monorepo

---

.travis.yml
WORKSPACE

* Verify that `go build` works
* Validate `gofmt`
* Make `bazel test` error on failure
* Add `buildifier` steps
Fixes #23 
Signed-off-by: Jake Sanders <jsand@google.com>

Add validation steps to travis

---

v1/config.go

Fix #35 
Signed-off-by: Jake Sanders <jsand@google.com>

Created: `string` -> `time.Time`

---

v1/partial/uncompressed.go
v1/remote/BUILD.bazel
v1/remote/transport/ping.go
v1/remote/transport/scheme.go
v1/remote/transport/scheme_test.go
v1/remote/write.go
v1/remote/write_test.go

Implement remote.Write

---

v1/remote/write.go
v1/remote/write_test.go

Fixes: https://github.com/google/go-containerregistry/issues/47

Add Content-Type to manifest PUT

---

cmd/deleter/main.go
cmd/poke/poke.go
name/BUILD.bazel
name/ref.go
name/ref_test.go

This parses a string as either a tag or digest.

Add ParseReference

---

vendor/github.com/google/go-cmp/cmp/cmpopts/BUILD.bazel
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go17.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go18.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/util_test.go
vendor/github.com/google/go-cmp/cmp/internal/testprotos/BUILD.bazel
vendor/github.com/google/go-cmp/cmp/internal/testprotos/protos.go
vendor/github.com/google/go-cmp/cmp/internal/teststructs/BUILD.bazel
vendor/github.com/google/go-cmp/cmp/internal/teststructs/project1.go
vendor/github.com/google/go-cmp/cmp/internal/teststructs/project2.go
vendor/github.com/google/go-cmp/cmp/internal/teststructs/project3.go
vendor/github.com/google/go-cmp/cmp/internal/teststructs/project4.go
vendor/github.com/google/go-cmp/cmp/internal/teststructs/structs.go

From HEAD I ran: `dep ensure && bazel run :gazelle`
These seem to have been missed from #60

Vendor missing deps

---

v1/remote/transport/bearer.go
v1/remote/transport/bearer_test.go

Accept access_token in token response

---

v1/image.go
v1/partial/uncompressed.go
v1/partial/with.go
v1/tarball/write.go
v1/tarball/write_test.go

This should match the OCI ordering.
Fixes #76 
Fixes #82

Fix the ordering of layers

---

v1/tarball/write.go

Write RawConfigFile to tarball

---

name/tag.go
name/tag_test.go

Fixes https://github.com/google/go-containerregistry/issues/91
Signed-off-by: Jake Sanders <jsand@google.com>

fix bug when creating Tags with weak validation and  registries

---

v1/remote/write.go

* make it clear which digests are blobs
* mimic the docker push output for the manifest

Improve logging for remote.Write

---

v1/remote/image.go

See https://github.com/GoogleContainerTools/skaffold/issues/504

Stop logging errors for mismatched digests

---

cmd/crane/append.go
cmd/crane/copy.go
cmd/crane/delete.go
cmd/crane/get.go
cmd/crane/list.go
cmd/crane/pull.go
cmd/crane/push.go
cmd/crane/rebase.go
name/ref.go

Wrap cmd errors with some context

---

.travis.yml

They regularly make breaking changes, and I have no interest in vendoring it just to get basic linting.

Remove buildifier checks

---

authn/helper.go
authn/helper_test.go

Fixes #156
Signed-off-by: David Gageot <david@gageot.net>

Fallback to Anonymous if credentials are not found

---

ko/build/gobuild.go

Fall back to default GOPATH if unset

---

v1/remote/write.go

Log pushed digest to stderr

---

v1/remote/transport/ping.go
v1/remote/transport/ping_test.go
v1/remote/transport/transport.go

Java people like to yell, which `strings.Title` doesn't handle well.
Fixes #189

Fix BASIC challenge

---

v1/mutate/mutate.go
v1/mutate/mutate_test.go

Fixes: https://github.com/google/go-containerregistry/issues/192

Recompute the size in the same places that we recompute the digest.

---

README.md
cmd/ko/README.md

Fixes #171 
This should be good enough until we figure out what to do with `ko` :)

Link to ko and crane

---

pkg/authn/keychain_test.go

When running tests under Bazel, `$TMPDIR` is set. Otherwise, the test should create and use a temp dir.
This also removes some instances where the test could `panic`, now it `t.Fatal`s.
Work toward #198

Allow keychain_test to pass outside of Bazel

---

.travis.yml

Define minimum golang version

---

pkg/v1/mutate/BUILD.bazel
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

Adding mutate library methods for reproducible images.

---

pkg/ko/build/gobuild.go

Create a new build directory for each file and use a fixed file name but don't
open the file (since that sometimes causes go build to fail).
Fixes https://github.com/google/go-containerregistry/issues/213

Avoid creating build output file

---

pkg/v1/mutate/mutate.go

preserve config for reproducible images

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

remove duplicate scope string from token handshake

---

pkg/ko/publish/default_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Perform HEAD for blob before initiating upload

---

cmd/ko/commands.go
cmd/ko/filestuff.go
cmd/ko/resolve.go

https://github.com/google/go-containerregistry/issues/141

Support  '-' for ko apply cmd

---

pkg/v1/partial/uncompressed.go

Memoizing the hash and size take the time to write on image (for one of my images) from 13s down to 8s.

Memoize size/hash for uncompressedLayerExtender

---

README.md
pkg/gcrane/gc.go
pkg/gcrane/list.go
pkg/v1/google/list.go
pkg/v1/google/list_test.go
pkg/v1/google/options.go

Add -r flag to `gcrane {gc,ls}`

Implement Walk for gcrane listing

---

pkg/v1/partial/compressed.go
pkg/v1/partial/configlayer_test.go
pkg/v1/partial/uncompressed.go
pkg/v1/remote/write_test.go

Don't return config 'layer' in ConfigByDigest

---

pkg/v1/v1util/zip.go
pkg/v1/v1util/zip_test.go

Delete unused v1util functions

---

cmd/gcrane/main.go
pkg/v1/google/list.go

Produced via: `github.com/client9/misspell`

Fix spelling errors

---

pkg/authn/helper.go
pkg/authn/helper_test.go

If the helper returns an error, add the command output and binary name
to the error if the output doesn't contain credentials.
This makes things a lot easier to debug than the current state of
things, which looks like an HTTP request somehow returned an error code
of 1.

Surface credential helper output in errors

---

pkg/v1/mutate/testdata/README.md

Remove whiteout file in testdata

---

pkg/gcrane/copy.go
pkg/gcrane/copy_test.go

tl;dr `gcrane cp -r gcr.io/foo gcr.io/bar`
This copies images from one repo to another, very quickly.
It's rather hard to test without a fake implementation of GCR, but it works on my machine 😄

Implement recursive copy for gcrane

---

.gcloudignore
Gopkg.lock

* Unignore genericclioptions in .gcloudignore
* Run dep ensure

Small cleanups

---

pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

Signed-off-by: Emily Casey <ecasey@pivotal.io>
Signed-off-by: Matthew McNew <mmcnew@pivotal.io>
After upgrading `go-containerregistry` we were getting `MANIFEST_BLOB_UNKNOWN` errors when pushing images after the config had been mutated. It seems that the config digest in the manifest was not matching the actual digest of the config blob. We believe this PR fixes the error.

Set accurate manifest config digest when mutating config

---

cloudbuild.yaml

Before we were just publishing crane.

Publish gcrane as well in cloudbuild.yaml

---

cmd/ko/filestuff.go
cmd/ko/resolve.go

Today the resolution logic in `ko` resolves all files before it starts to feed anything to `kubectl`.
This changes that logic to use channels to stream files back from the filesystem discovery process and futures to block on the resolution *in order* so that they are fed to kubectl in the order they are received.  This last bit is subtle and important because the order of the initial walk is generally expected to deterministically order how things are fed to kubectl.
This change is also a prelude to another that will make the file enumeration a continuous stream that's hooked up to a filesystem watcher like fsnotify.

Switch ko resolution to use "futures".

---

cmd/ko/commands.go

This works around buffering in kubectl that led me to workaround this issuewhen experimenting with demo material for ko [here]()https://github.com/mattmoor/kodemo/blob/90b630836e0237e67bfadb73c65bb5ad882c415e/config/service.yaml#L1-L936).

Work around kubectl buffering

---

Gopkg.lock
vendor/github.com/mattmoor/dep-notify/pkg/graph/manager.go
vendor/github.com/mattmoor/dep-notify/pkg/graph/node.go

With this `ko apply -W -f config/` on a directory outside of `GOPATH` seems to work properly.

Pull in the latest version of dep-notify to fix ko watch.

---

cmd/ko/flatname.go
cmd/ko/publish.go
cmd/ko/resolve.go

Make -B work with ko {resolve, apply}

---

cmd/crane/doc/crane.md
cmd/crane/doc/crane_validate.md
pkg/crane/validate.go
pkg/v1/validate/doc.go
pkg/v1/validate/image.go
pkg/v1/validate/index.go

Add validate.Image and crane validate

---

pkg/v1/remote/image_test.go
pkg/v1/remote/index_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Fixes https://github.com/google/go-containerregistry/issues/119

Implement remote.WriteIndex

---

pkg/v1/empty/index.go

Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`

golang format tools

---

pkg/authn/k8schain/tests/explicit/main.go
pkg/authn/k8schain/tests/implicit/main.go
pkg/authn/k8schain/tests/noauth/main.go
pkg/authn/k8schain/tests/serviceaccount/main.go
pkg/crane/append.go
pkg/crane/copy.go
pkg/crane/delete.go
pkg/crane/get.go
pkg/crane/list.go
pkg/crane/pull.go
pkg/crane/push.go
pkg/crane/rebase.go
pkg/crane/validate.go
pkg/gcrane/copy.go
pkg/gcrane/gc.go
pkg/gcrane/list.go
pkg/v1/tarball/image.go

Drop name.WeakValidation

---

pkg/v1/layer.go
pkg/v1/layout/image.go
pkg/v1/layout/image_test.go
pkg/v1/mutate/mutate_test.go
pkg/v1/partial/compressed.go
pkg/v1/partial/uncompressed.go
pkg/v1/partial/with.go
pkg/v1/random/image.go
pkg/v1/random/image_test.go
pkg/v1/remote/image.go
pkg/v1/stream/layer.go
pkg/v1/stream/layer_test.go
pkg/v1/tarball/image.go
pkg/v1/tarball/layer.go

Signed-off-by: Dave Protasowski <dprotaso@gmail.com>

expose the layer media type

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go

Only overwrite scheme for the registry host

---

pkg/registry/registry.go
pkg/registry/registry_test.go

A start to implementing the container registry protocol.

registry: Create initial registry folder and support v2 version check.

---

pkg/registry/blobs.go
pkg/registry/registry.go
pkg/registry/registry_test.go

This doesn't handle chunked uploads yet - although its design allows for it.

registry: Implement basic blob handler.

---

pkg/registry/blobs.go
pkg/registry/registry.go

I accidentally forgot to commit some review changes

registry: Missed review changes.

---

pkg/registry/blobs.go
pkg/registry/compatability_test.go
pkg/registry/registry_test.go

- fixed Location header
- added tests for Docker-Content-Digest + Location
- added compat test between pkg/registry and pkg/v1/remote

Add tests for Docker-Content-Digest,  Location headers, and v1/remote compatibility.

---

.travis.yml
cmd/registry/test.sh
pkg/registry/blobs.go
pkg/registry/registry_test.go

There is a weird bug in crane where it has on off by 1 error with writing tar files, so some of the test is commented out.

registry: Add a travis command line test for docker and crane compatibility

---

pkg/crane/append.go
pkg/crane/copy.go
pkg/crane/delete.go
pkg/crane/list.go
pkg/crane/push.go
pkg/crane/rebase.go
pkg/gcrane/copy.go
pkg/registry/compatability_test.go
pkg/v1/remote/delete.go
pkg/v1/remote/delete_test.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go
pkg/v1/remote/index.go
pkg/v1/remote/list.go
pkg/v1/remote/list_test.go
pkg/v1/remote/options.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Ref https://github.com/google/go-containerregistry/issues/161

Add functional options to the rest of remote

---

cmd/crane/doc/crane.md
cmd/crane/doc/crane_version.md
hack/update-code-gen.sh
pkg/crane/version.go

Inspired by https://github.com/google/ko/pull/25

[g]crane: Add version command

---

pkg/v1/remote/check.go

Really nasty to find know exactly where things went wrong without.

Add error details in CheckPushPermission.

---

pkg/v1/remote/descriptor.go
pkg/v1/remote/descriptor_test.go

Trading one hack for another -- instead of calculating the digest for
signed schema 1 images, we'll just trust the registry's
Docker-Content-Digest header, since calculating them correctly would
require us to do string surgery with signatures.
This allows clients to do tag -> digest resolution for schema 1 images
even though we don't explicitly handle them.

Trust the registry for signed schema1 digests

---

pkg/v1/remote/descriptor.go
pkg/v1/remote/descriptor_test.go

Add mediatype to ErrSchema1 message

---

pkg/v1/random/image.go
pkg/v1/random/image_test.go

This will make it easier to test foreign layers.

Add random.Layer

---

pkg/crane/crane_test.go
pkg/v1/remote/image_test.go

Also hit some missed coverage in remote.Image.

Follow up missed PR feedback

---

.travis.yml
pkg/gcrane/copy.go
pkg/internal/legacy/copy.go
pkg/internal/legacy/copy_test.go
pkg/internal/retry/retry.go
pkg/internal/retry/wait/kubernetes_apimachinery_wait.go
pkg/v1/hash.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/write_test.go
pkg/v1/v1util/zip_test.go

Fix linter issues

---

pkg/internal/legacy/copy.go
pkg/internal/legacy/copy_test.go

Just making this consistent with `remote.Write`.

Add progress logs to copy schema 1

---

pkg/crane/example_test.go
pkg/crane/filemap_test.go
pkg/legacy/config.go
pkg/legacy/tarball/write.go
pkg/v1/config.go
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go
pkg/v1/zz_deepcopy_generated.go

This is a holdover from docker days and isn't present in
opencontainers/image-spec.

Drop container_config from v1.Config

---

go.mod
go.sum
pkg/v1/validate/image.go
pkg/v1/validate/layer.go

I tried to use this and realized it didn't exist!

Implement validate.Layer

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

Needed for https://github.com/google/ko/issues/90
Unforunately, [this logic](https://github.com/moby/moby/blob/fc01c2b481097a6057bec3cd1ab2d7b4488c50c4/registry/config.go#L397-L404) isn't in the docker/cli package.

Fix default auth

---

pkg/v1/google/auth.go

As discussed on #482, here is a PR that adds this functionality. I've not tested the second helper function yet but planning to do in my own project separately.

Add helper func to create authenticators using a Google Service Account.

---

README.md
cmd/crane/cmd/version.go

Get version from debug info

---

cmd/crane/cmd/validate.go

This decreases the binary size by 3MB because the daemon package pulls
in so many dependencies. This feature is easy to replace with a call to
`docker save`.

Drop daemon dependency from crane

---

pkg/gcrane/list.go
pkg/v1/google/auth_test.go
pkg/v1/google/keychain.go

Cache google.Keychain results

---

go.mod
go.sum
pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

Deduplicate layers when writing a multi-image tarball

---

pkg/internal/compare/image_test.go
pkg/internal/compare/index_test.go

Cover the MediaType paths of pkg/internal/compare

---

cmd/crane/cmd/blob.go
pkg/crane/crane_test.go
pkg/crane/pull.go

This also adds PullLayer to pkg/crane (because Layer was already taken
by the filemap thing).

Add crane blob command

---

cmd/crane/cmd/root.go

Based on https://github.com/google/go-containerregistry/pull/642
This is particularly useful for debugging.

Respect HTTPHeaders in $DOCKER_CONFIG

---

pkg/v1/layout/write.go

v1.layout.WriteFile public, so can use it for other things

---

cmd/gcrane/cmd/list.go

Sometimes, I want structured output or more info than just digest +
tags. This just returns everything so that you can use e.g. jq to
process the results.

Add a --json flag to gcrane ls

---

pkg/v1/remote/list.go

Reduce default tags page size

---

pkg/v1/google/keychain.go

google.Keychain doesn't actually care about the target resource, so
caching based on the resource was never useful. In fact, it was actively
harmful, since we were invoking gcloud for every repository that
keychain called. We don't hit that often, but `gcrane cp -r` for a large
registry will definitely notice.

Use sync.Once instead of sync.Map

---

pkg/authn/k8schain/k8schain.go

After adding the ECR support, we started seeing extremely slow reconciles, even off AWS.  The logic that elides this is the `Enabled()` check, which is the only thing that should run off AWS, the problem (unconfirmed) is that we run this every time we create a k8schain (which Knative was doing per-Reconciliation) because historically this has been relatively cheap.
The fix (unconfirmed) is to simply cache the underlying `credentialprovider.DockerKeyring` across invocations, which seems worth doing regardless because it takes in zero context from the caller.  We do this in a `sync.Once` (vs. `init`)to avoid this hit when the keychain is unused, but linked.
cc @duglin @markusthoemmes

Cache the K8s keyring across k8schains.

---

pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

Addresses #680 . It doesn't change how anything works, but makes it possible to get the tarball `manifest.json` without actually writing the tarball. 
I tried to extract it as a separate func, but there was so much duplication to what is in `MultiRefWrite()` that it just made sense to pull the code out of there into a separate func that always returns the manifest. If a `*tar.Writer` is passed, then it also writes via the writer.
I also provided three separate convenience functions to parallel the three separate `Write()`/`MultiWrite()`/`MultiRefWrite()`
This is a work in progress, so looking for thoughts.

extract v1.tarball manifest creation from writing, make open

---

pkg/v1/remote/transport/ping.go

Currenty `ping` for registries doesn't drain the response body so the connection
isn't reused. But in many cases, reusing the `ping` connection is valuable for
performance because it's general to access the `ping`ed registry soon after the
`ping`ing for fetching the contents.

Drain ping body for connection reuse

---

pkg/legacy/tarball/write.go
pkg/legacy/tarball/write_test.go

Addresses https://github.com/bazelbuild/rules_docker/issues/1420

Deduplicate layers in legacy tarballs

---

.goreleaser.yml

See https://github.com/yihanzhen/go-containerregistry/releases/tag/v0.7.0 for result.

add name template for archives in goreleaser.yaml

---

cmd/crane/cmd/catalog.go

Use crane options for crane.Catalog

---

hack/update-codegen.sh
pkg/v1/doc.go
pkg/v1/image.go
pkg/v1/index.go

Drop //go:generate since we need hack/update-codegen.sh anyways

---

pkg/v1/remote/image.go

Missed this in https://github.com/google/go-containerregistry/pull/816

Don't log image layers in debug logs

---

.goreleaser.yml

Fixes https://github.com/google/go-containerregistry/issues/854

Set Version via ldflags for releases

---

README.md

I took a stab at this.  I wanted this to better reflect the immutability + function mutation + composability of the interface design.

Update the philosophy

---

pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go

Sometimes the error is on proxy level, but it still will be beneficial to retry it.

Retry registry access on some server errors.

---

pkg/v1/google/list.go
pkg/v1/google/list_test.go
pkg/v1/google/options.go

To match remote.WithUserAgent
https://github.com/google/go-containerregistry/issues/830

Add google.WithUserAgent

---

pkg/registry/manifest.go
pkg/registry/registry_test.go
pkg/v1/layout/testdata/test_index/index.json
pkg/v1/layout/write.go
pkg/v1/layout/write_test.go
pkg/v1/mutate/index.go
pkg/v1/mutate/index_test.go
pkg/v1/remote/index.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/multi_write_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go
pkg/v1/validate/index.go

Access v1.Layer via our index impls

---

cmd/crane/README.md
cmd/gcrane/README.md

Fixes https://github.com/google/go-containerregistry/issues/941

Update install instructions for go1.16

---

.github/workflows/knative-go-build.yaml
.github/workflows/knative-go-test.yaml

Build and test with go 1.15 and 1.16
as discussed https://github.com/google/go-containerregistry/pull/943#issuecomment-783553739
EDIT:
~will need to update the required status checks~
/assign @jonjohnsonjr

ci: build/test with multiple version of go

---

pkg/v1/layout/write.go

I saw https://github.com/google/go-containerregistry/pull/847 was green and clicked merge without thinking.

Fix bad layout options merge

---

pkg/v1/manifest.go

I put this on the wrong field years ago :/

Move omitempty to the right place

---

cmd/crane/README.md

hi,
as written in #968 there is a arch package to install crane/gcrane. this enhances the installation instructions for arch users.

describe how to install crane on arch

---

pkg/crane/append.go
pkg/crane/crane_test.go
pkg/crane/optimize_test.go

Noticed our coverage numbers were looking somewhat anemic, starting working on that.

Add lots of tests to pkg/crane

---

pkg/v1/remote/write.go

We often see unexpected EOF and broken pipe errors, which are somewhat
expected given that we're often both reading from and writing to the
network.
https://github.com/google/go-containerregistry/issues/618

Retry more errors in remote.Write

---

.github/workflows/stale.yaml

Fix typo in state GitHub Action

---

pkg/v1/remote/catalog.go

Reduce default catalog page size

---

pkg/name/check.go

Don't use the term 'runes' in error messages

---

pkg/v1/tarball/layer.go
pkg/v1/tarball/layer_test.go

Add tarball.WithMediaType to specify layer media type

---

pkg/authn/kubernetes/keychain.go
pkg/authn/kubernetes/keychain_test.go

Fixes: https://github.com/google/go-containerregistry/issues/1298 & https://github.com/knative/serving/issues/12642

authn/kubernetes - fix auth config lookup

---

.github/dependabot.yml
.github/workflows/bump-deps.yaml

Also disable dependabot for Go module deps

Add GitHub Action to automatically bump deps

---

.goreleaser.yml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
to include the source archive checksum to checksums.txt

add source archive checksum into the checksums.txt

---

pkg/v1/tarball/write.go

`calculateTarballSize` should work exactly as `writeImagesToTar` does when traversing tarball entries.

Fix calculating tarball size when duplicated layers exist

---

cmd/crane/README.md

I've uploaded an official `crane` package that contains binaries for `crane`, `gcrane` and `krane`.
Cheers!

Update Arch Linux install instructions

---

pkg/v1/remote/descriptor.go

See https://github.com/docker/hub-feedback/issues/2107#issuecomment-1371293316

Hack around DockerHub plugin scope handling

---

.golangci.yaml
pkg/name/digest.go
pkg/registry/registry_test.go

followup to https://github.com/google/go-containerregistry/pull/1538#issuecomment-1403631330

Enforce proper sha256 usage

---

pkg/authn/kubernetes/keychain.go
pkg/authn/kubernetes/keychain_test.go

Fixes: #1558
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

authn: also read mount secrets

---

pkg/v1/empty/index.go
pkg/v1/mutate/mutate_test.go

Set previously unset mediaType for empty.ImageIndex and update existing mediaType for empty.Image to OCIManifestSchema1

Set mediaType for empty.ImageIndex in RawManifest 

---

.github/workflows/release.yml

Similar work: github.com/ko-build/ko/pull/969/ by @mchmarny

replace manual slsa-verifier installation with action

---

pkg/v1/remote/options.go

Add `retryStatusCodes` option and `remote.WithRetryStatusCodes` to customize retryable status codes list.

feat(remote): make retryStatusCodes configurable

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Fixes https://github.com/google/go-containerregistry/issues/1741

Don't try cross-origin mounting against dockerhub

---

pkg/registry/manifest.go
pkg/registry/registry_test.go

Return OCI Index content-type for referrers response

---

.github/workflows/release.yml

Fixes https://github.com/google/go-containerregistry/issues/1785

Build releases with Go 1.21

---

.github/workflows/style.yaml
.golangci.yaml
pkg/crane/copy.go
pkg/crane/pull.go
pkg/v1/google/list.go
pkg/v1/layout/write.go
pkg/v1/mutate/index.go
pkg/v1/mutate/mutate.go
pkg/v1/remote/multi_write_test.go
pkg/v1/remote/pusher.go
pkg/v1/remote/transport/bearer_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Spawned from toil working on #2093
Required to bump Go to 1.24.0.

Migrate linter to v2

---

.github/workflows/analyze.yaml

Fixes https://github.com/google/go-containerregistry/issues/2098 according to https://github.com/github/codeql-action/issues/2789

Update CodeQL permissions

---

.github/workflows/release.yml

Successful run on main: https://github.com/Subserial/go-containerregistry/actions/runs/15149740061

Update provenance action in release

---

.github/workflows/release.yml

Successful validator run: https://github.com/Subserial/go-containerregistry/actions/runs/15150178227/job/42594883569
Update required due to https://github.com/slsa-framework/slsa-verifier/issues/325

Update validator action
