google/go-containerregistry

v1/config.go
v1/hash.go
v1/hash_test.go
v1/manifest.go
v1/manifest_test.go

This is in anticipation of using streaming interfaces to access the contents of image parts to avoid loading them into memory.

Switch parsing utilities to favor io.ReadCloser over []byte.

---

v1/remote/transport/basic.go
v1/remote/transport/basic_test.go
v1/remote/transport/bearer.go
v1/remote/transport/bearer_test.go
v1/remote/transport/transport.go

Add a name.Registry as the target registry for a bearerTransport. The
bearerTransport will only attach bearer tokens to requests matching the
registry's domain.
This fixes an issue where the registry would redirect to object storage,
which would reject the request due to an invalid Authorization header.

Fix transport authentication errors on redirect

---

v1/image.go
v1/partial/BUILD.bazel
v1/partial/compressed.go
v1/partial/doc.go
v1/partial/image.go
v1/partial/uncompressed.go
v1/partial/with_blob.go
v1/partial/with_configfile.go
v1/partial/with_manifest.go
v1/partial/with_uncompressedlayer.go
v1/random/BUILD.bazel
v1/random/doc.go
v1/random/image.go
v1/random/image_test.go
v1/tarball/BUILD.bazel
v1/tarball/image.go

This also implements `v1/random` that I was using as a testbed, and hooks it into @dlorenc's recent `v1/tarball`.

Implement the "partial" helper package.

---

v1/image.go
v1/partial/compressed.go
v1/partial/image.go
v1/partial/uncompressed.go
v1/partial/with.go
v1/random/image.go
v1/tarball/image.go

These are needed to avoid inconsistencies in reserializing our structured representation.
This reorients the v1/partial interfaces around these as the new core that needs to be implemented, which leads to some slight simplification.

Introduce Raw{ConfigFile,Manifest} methods.

---

cmd/puller/BUILD.bazel
cmd/puller/main.go
cmd/pusher/BUILD.bazel
cmd/pusher/main.go

These will fail on NYIs for now, but we have enough of the interface present that we can write them.

Add a couple simple push/pull clients.

---

cmd/deleter/BUILD.bazel
cmd/deleter/main.go
v1/remote/BUILD.bazel
v1/remote/delete.go
v1/remote/delete_test.go

This adds support for deleting images from a registry by either tag or digest.
This also adds `//cmd/deleter` with a simple wrapper of this functionality.
Fixes: #39

Implement remote.Delete

---

cmd/poke/BUILD.bazel
cmd/poke/poke.go
v1/partial/compressed.go
v1/remote/BUILD.bazel
v1/remote/image.go
v1/remote/image_test.go

* Basic interactions with schema 2 images (relies on registry fallback for manifest lists for now).
* Poke client to use it.

Initial remote.Image

---

v1/remote/BUILD.bazel
v1/remote/error.go
v1/remote/error_test.go
v1/remote/image.go
v1/remote/write.go
v1/remote/write_test.go

This changes adds support for parsing structured 4XX errors from a Docker registry.
Sample output against GCR:
```
2018/03/30 10:12:14 DENIED: "Please enable or contact project owners to enable the Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=convoy-adaptor before performing this operation."
```
Fixes: https://github.com/google/go-containerregistry/issues/46

Add support for structured error handling.

---

name/registry.go
name/repository.go
v1/remote/image.go

Fixes #56.
Just log a warning instead. Every official image is broken if we
validate the Docker-Content-Digest, since they are all manifest lists.

Ignore digest mismatch for DockerHub

---

v1/empty/BUILD.bazel
v1/empty/doc.go
v1/empty/image.go
v1/empty/image_test.go

This adds a special singleton for empty.Image, which serves a similar purpose to "FROM scratch" in the land of Dockerfiles.
In isolation this isn't particularly interesting, but it provides a foundation on top of which subsequent utilities may build.
Related to: https://github.com/google/go-containerregistry/issues/48

Add empty.Image

---

authn/keychain.go
authn/keychain_test.go

Pushing & pulling from DockerHub should now work
Signed-off-by: Brenda Chan <brchan@pivotal.io>

Docker's config uses the field 'credsStore' instead of 'credStore'

---

v1/BUILD.bazel
v1/image.go
v1/layer.go
v1/partial/compressed.go
v1/partial/uncompressed.go
v1/partial/with.go
v1/random/image.go
v1/remote/image.go
v1/remote/image_test.go
v1/remote/write.go
v1/tarball/image.go
v1/tarball/write.go

The number of methods on v1.Image that dealt in either "Diff ID" or "Digest" was a little silly, and carry-over from the Python library.  This change defines a v1.Layer abstraction to hold the bulk of these methods, and dramatically simplify the v1.Image interface.
Fixes: #59

 Create a separate v1.Layer abstraction

---

v1/mutate/mutate.go
v1/mutate/mutate_test.go

We were changing the `ConfigFile.Config`, but we weren't updating the `Manifest`'s digest for the `ConfigFile`.  This meant that things keying off of the `Manifest`'s `ConfigFile` digest field to access things through `LayerByDigest` would end up being delegated to the base image's implementation.  In my case, this was manifesting as us asking GCR for a non-existent blob (`remote.Image`).
Related: https://github.com/google/go-containerregistry/issues/87

Fix an issue accessing the Config when we mutate it.

---

ko/publish/BUILD.bazel
ko/publish/default.go
ko/publish/default_test.go
ko/publish/doc.go
ko/publish/fixed.go
ko/publish/fixed_test.go
ko/publish/publish.go

This adds a package for handling how `v1.Image`s are published for `ko`.  The `publish.Interface` contains one method, which takes a `v1.Image` and an importpath and is responsible for publishing it to some base `name.Repository` and returning a `name.Digest` suitable for substitution into the K8s yaml.
There are currently two implementations provided:
1. `NewFixed`: this is an implementation intended to aid in testing packages that need a `publish.Interface`.
1. `NewDefault`: this is an implementation that publishes to: `{chroot}/{importpath}:latest` via `remote.Write` and the default keychain.
In the future, we might consider an alternate implementation of `publish.Interface` that support flatter naming schemes (e.g. to support DockerHub, with which the `NewDefault` scheme won't work). …

Implement ko/publish

---

ko/build/BUILD.bazel
ko/build/build.go
ko/build/doc.go
ko/build/fixed.go
ko/build/fixed_test.go
ko/build/gobuild.go
ko/build/gobuild_test.go

This adds a package for handling builds for `ko`.  The `build.Interface` contains two methods:
1. `IsSupportedReference`: this is used to determine whether a particular string (in a K8s yaml) smells like a reference for which this `build.Interface` can produce a `v1.Image`.
1. `Build`: this is responsible for synthesizing a `v1.Image` for supported references.
At present, this contains two implementations:
1. `NewFixed`: this is an implementation intended to aid in testing packages that need a `build.Interface`.
1. `NewGo`: this is a real implementation that will perform a `go build` for import paths relative to the execution context and layer the resulting binary on top of a provided base image.
Progress towards: https://github.com/google/go-containerregistry/issues/80

Implement ko/build

---

v1/tarball/write.go

This is mostly cosmetic/ergonomic when debugging, but changing from:
sha256:badf00d
to:
badf00d.tar.gz
Makes `gzip` stop complaining about file extensions and `tar` stop
complaining about remote tape drives.

Make layer filenames play nice with tar and gzip

---

cmd/d8s/BUILD.bazel
cmd/d8s/copy.go
cmd/d8s/main.go

This copies an image from a src reference to a dst reference, which
should generally be fast due to mounting.

Add d8s copy

---

v1/mutate/mutate.go
v1/mutate/mutate_test.go

Instead, initialize a pipe, write tar contents into one end in a goroutine and hand the read end back to the user.
This also adds a test that errors returned during `Extract` are surfaced to the read end (since `Extract` no longer returns an error). It also tests that partial reads of the read end, and `Close` after a partial read, don't result in errors.
/cc @nkubala

Don't buffer entire tar contents into memory during Extract

---

authn/keychain.go
authn/keychain_test.go

This is needed for image-rebase to work on Container Builder, where the
user's homedir is unset, but $HOME is explicitly set in each build step.

Support $HOME/.docker if $DOCKER_CONFIG is unset

---

Gopkg.lock
Gopkg.toml
cmd/ko/BUILD.bazel
cmd/ko/README.md
cmd/ko/main.go
v1/mutate/BUILD.bazel
vendor/github.com/spf13/cobra/command.go

This uses the cobra library to implement the `ko` CLI, which wraps the `go` CLI and exposes a handful of commands for interacting with kubernetes configurations.  See `cmd/ko/README.md` for more details.
Fixes: #80

Implement cmd/ko

---

v1/remote/delete.go
v1/remote/image.go
v1/remote/image_test.go
v1/remote/transport/bearer.go
v1/remote/transport/bearer_test.go
v1/remote/transport/scope.go
v1/remote/transport/transport.go
v1/remote/transport/transport_test.go
v1/remote/write.go

This PR refactors `transport.New` to take fully-qualified scopes. This is necessary to fix `crane append` when the source and destination are two different Docker Hub repos .
See #123 for additional context.

Fix scope-related bug in remote.Write (#123)

---

Gopkg.lock
ko/resolve/BUILD.bazel
ko/resolve/resolve.go
scripts/update-deps.sh
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/BUILD.bazel
vendor/golang.org/x/sync/errgroup/errgroup.go

This simplifies the parallelism in ko/resolve's type-based walk.  Instead of trying to parallelize everything we now have three phases:
1. Serially walk the objects and gather references to build (quick)
1. Perform parallel builds and pushes of all supported references (slow)
1. Serially walk the objects and substitute published digests for supported references (quick)
This has the added benefit of deduplicating builds of the same importpath.

Address TODO in ko/resolve.

---

cmd/crane/append.go
cmd/crane/pull.go
v1/daemon/BUILD.bazel
v1/daemon/write.go
v1/daemon/write_test.go
v1/tarball/write.go
v1/tarball/write_test.go

This adds support for loading a `v1.Image` into a local docker daemon, by first writing it in `docker save` format using `tarball.Write`, and then feeding that to the docker client.
Previously `tarball.Write` only supported writing to disk, so to avoid this I changed the signature to return an `io.ReadCloser` by default. `tarball.WriteToFile` can be used in its place to write the contents of this reader to disk.

Implement daemon.Write

---

v1/mutate/mutate.go

This was causing entries like `foo/bar/bar` to get ignored when writing the final tarball in `mutate.Extract`. `foo/bar/` (the parent directory) gets written fine, but when we add it to the "seen files" map, we do a `filepath.Join(basename, dirname)`, and for some reason `filepath.Dir("foo/bar/")` is `bar`. So `foo/bar/bar` gets marked as seen and subsequently ignored.
https://play.golang.org/p/EZyvIqtQRaB

Don't filepath.Join names when splitting directories

---

v1/config.go

Needed to implement HEALTHCHECK commands to kaniko - see https://github.com/GoogleContainerTools/kaniko/issues/17#issuecomment-388868094

added healthcheck to config struct and healthcheck struct

---

ko/build/gobuild_test.go
v1/tarball/layer_test.go
v1/v1util/zip.go

Fixes #150.
gzip.BestCompression is very slow.
On my machine, for `gcr.io/google-appengine/python:latest`, computing
the digest of each layer took...
```
NoCompression        13.0 s
HuffmanOnly          23.0 s
BestSpeed            27.0 s
DefaultCompression   54.0 s
BestCompression     246.5 s
```
I think DefaultCompression is probably a reasonable default, but this
also adds GzipReadCloserLevel that lets callers determine the compression
level. We'll need to plumb that through all the v1/partial stuff.

Use gzip.DefaultCompression by default

---

cmd/ko/BUILD.bazel
cmd/ko/README.md
cmd/ko/commands.go
cmd/ko/config.go
cmd/ko/main.go
cmd/ko/publish.go
cmd/ko/resolve.go

`ko publish` builds and publishes images for import paths passed as args. See [README](https://github.com/ImJasonH/go-containerregistry/blob/29f77211e26a4d53fa82d956226d889688bee85e/cmd/ko/README.md#ko-publish).
Fixes #147

Add ko publish

---

ko/build/gobuild_test.go
v1/tarball/layer_test.go
v1/v1util/zip.go

Disk is cheap and we (generally) have fast networks, but I haven't
figured out how to get more time. This shaves ~1s off my `ko` builds.

Switch from DefaultCompression to BestSpeed

---

cmd/ko/config.go
cmd/ko/resolve.go
ko/build/gobuild.go
ko/build/gobuild_test.go
v1/mutate/mutate.go
v1/mutate/mutate_test.go

Using `ko` I noticed that when building images the creation time was '48 years ago' when running `docker images`:
Eg. 
```
bazel/v1/mutate                                        source_image        6e0b05049ed9        48 years ago        8B
```

Add creation time to image build

---

pkg/crane/digest.go

As (probably) the only user of this command, I find that I want a
newline more often than I don't want a newline.

Add newline to `crane digest` output

---

cloudbuild.yaml
cmd/crane/BUILD.bazel

This enables the use of `crane` as a build step in Container Builder, e.g.:
```yaml
steps:
- name: gcr.io/go-containerregistry/crane
args: ['help']
```

Build a crane builder image, using ko

---

ko/build/gobuild.go
ko/build/gobuild_test.go

Previously we used `/app`, which is unfortunately a fairly generic name, in a location that doesn't disambiguate well.  Under most circumstance this is fine, however, I ran into a problem with a base image that was using `/app` for other purposes and this unintentionally shadowed that directory with our app.

Rename our chosen entrypoint to /ko-app

---

cmd/ko/README.md
cmd/ko/commands.go
cmd/ko/publish.go
cmd/ko/resolve.go
ko/publish/daemon.go

This enables users to configure the use of the local docker daemon via the `KO_DOCKER_REPO` environment variable in addition to supplying `-L` on the command-line.
There have been reports that `-L` makes it harder for teams that have a mix of minikube and K8s cluster usage to script with `ko`.  This is expected to make that somewhat simpler.
Fixes: https://github.com/google/go-containerregistry/issues/179

Accept KO_DOCKER_REPO=ko.local in addition to -L

---

cmd/ko/commands.go

Previously we silently ignored unrecognized flags, which led to non-intuitive behaviors when a typo was present.
Fixes: https://github.com/google/go-containerregistry/issues/170

Reject unrecognized arguments.

---

cmd/ko/config.go
cmd/ko/publish.go
cmd/ko/resolve.go
ko/publish/BUILD.bazel
ko/publish/default.go
ko/publish/default_test.go
pkg/crane/append.go
pkg/crane/copy.go
pkg/crane/rebase.go
v1/remote/BUILD.bazel
v1/remote/image.go
v1/remote/mount.go
v1/remote/write.go
v1/remote/write_test.go

This completely changes the model for cross-repo mounting in the `go-containerregistry` library.  Rather than having clients of `remote.Write` pass in a set of potential mount sources, `remote.Write` is sensitive to a new `v1.Layer` wrapper type: `remote.MountableLayer`, which implements `v1.Layer` by embedding the layer it wraps and augmenting that with the name of the repository from which we should attempt to mount it, if written.  With this model, `remote.Image` now wraps all of the `v1.Layer`s it returns with the name of the repository from which it is pulling.
Fixes: https://github.com/google/go-containerregistry/issues/165
cc @sclevine

Change the way mounting works in go-containerregistry.

---

v1/partial/compressed.go
v1/partial/with.go
v1/remote/image.go
v1/tarball/image.go

Prior to this change, the `partial` package enabled folks to implement the bare minimum interface necessary to compute the remainder of the `v1.Image` or `v1.Layer` interface.  With this change, we start to adopt a pattern that allows implementors to go beyond this bare minimum and implement additional methods and have the `partial` wrappers respect and delegate to these additional methods.
The first use case of this pattern is in `remote.Layer` where we effectively know all of the layers' `DiffID`s, but because of the "bare minimum" constraint we had previously been unable to leverage this knowledge to elide recomputing the DiffID by downloading and uncompressing the layer.
Fixes: https://github.com/google/go-containerregistry/issues/166
cc @sclevine

Avoid recomputing the DiffID of layers where we know it.

---

cmd/ko/config.go
pkg/crane/append.go
pkg/crane/copy.go
pkg/crane/get.go
pkg/crane/pull.go
pkg/v1/daemon/BUILD.bazel
pkg/v1/daemon/image.go
pkg/v1/daemon/image_test.go
pkg/v1/daemon/options.go
pkg/v1/remote/BUILD.bazel
pkg/v1/remote/image.go
pkg/v1/remote/image_test.go
pkg/v1/remote/options.go

Opening this PR now to get some design feedback. This refactors the interfaces to add support for functional options for all `Image` calls. Each package defines its set of legal functional options in its `options.go` file as `With...()` methods, e.g. `remote.WithTransport()`.
~To allow applying configuration to the `v1.Image` after it's created, I created a `MutableImage` which essentially serves as a concrete wrapper around the `v1.Image` and allows methods to be defined on it.~
Instead of the `MutableImage` (not great design since it makes making sync mistakes easy), I adopted @mattmoor's idea of an `ImageOpener`, which gives us an easy way of applying functional options before returning an immutable image.

Functional Options

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Hi!  Thank you for maintaining great project!!
`go-containerregistry` uses [Cross Repository Blob Mount](https://docs.docker.com/registry/spec/api/#cross-repository-blob-mount) in [`writer.initiateUpload(h)`](https://github.com/google/go-containerregistry/blob/3f6471078a9661a9a439bd5e71a371aff429566a/pkg/v1/remote/write.go#L143-L149) even when the mountable layer comes from a different registry.  This would cause `401 Unauthorized` error.  It can easily happen when users try to push the layer to their own private registry.
Although I'm not so familiar with docker registry API,  I think cross repo blob mount should be used only when the mountable layer comes from the SAME registry with the target registry.

cross-repo blob mount should be used only when the layer comes from the same registry

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go
pkg/ko/build/gobuild.go
pkg/ko/build/gobuild_test.go

Without this, you get the following error:
> `2018/07/05 14:20:16 error processing import paths in "config\\webhook.yaml": working directory "c:\\Go\\src\\github.com\\evankanderson\\sia" must be on GOPATH "c:\\\\Go/src"`
With this patch, I'm able to use `ko apply` successfully.

Fix file paths for `ko` on windows

---

cmd/crane/rebase_cloudbuild.yaml

Fixes #223 
Instead of building the `crane` builder in the test, just assume it was already built from the repo's root `cloudbuild.yaml` and was pushed to `gcr.io/$PROJECT_ID/crane`

Fix rebase_cloudbuild.yaml

---

pkg/authn/multikeychain.go
pkg/authn/multikeychain_test.go

This enables us to change the fallback behavior of keychains from Anonymous to another keychain.

Add a mechanism for composing keychains.

---

Gopkg.toml
cmd/ko/publish.go
pkg/ko/build/gobuild.go
pkg/ko/build/gobuild_test.go

Fixes #215 and #197 
With this change, only import paths that represent runnable commands (i.e., `package main`) are considered "supported". As a reminder, attempting to `ko publish` an unsupported path will fail, and unsupported paths are simply ignored when `ko resolve`ing.
This change also allows `ko` to be run outside of `GOPATH`, and requires import paths to be fully qualified -- `image: ./cmd/foo` will not `resolve`, it must be `image: github.com/my/repo/cmd/foo`

Use go/build.Import to resolve import paths

---

cmd/ko/publish.go
cmd/ko/publish_test.go
pkg/ko/build/gobuild_test.go

Begins to address #190, based on work in #229 
With this change, if your working directory is within `$GOPATH/src`, you can run `ko publish ./some/local/import/path` (assuming that path is valid and points to a `package main`).
This does not yet support `ko publish ./...`, but this is a prerequisite.

Allow relative paths in ko publish

---

pkg/authn/keychain.go
pkg/ko/publish/options.go
pkg/v1/remote/options.go

With this change, if a user calls `someKeychain.Resolve(...)` and the result is `authn.Anonymous`, no logs will be emitted. It would be up to them to log the anonymous fallback, if they wanted to. Users calling `remote.WithAuthFromKeychain` _would_ see a log message if the final result of that keychain's `Resolve` was `authn.Anonymous`.
The benefit is that if `WithAuthFromKeychain` is passed an `authn.MultiKeychain`, the user won't see confusing `falling back on anonymous` messages in their logs that might not be true if a later keychain in the list picked up real creds.

Don't log anonymous fallback except in WithAuthFromKeychain

---

cmd/ko/README.md
cmd/ko/commands.go
cmd/ko/flatname.go
cmd/ko/publish.go
cmd/ko/resolve.go
pkg/ko/publish/default.go
pkg/ko/publish/default_test.go
pkg/ko/publish/options.go
pkg/name/repository.go

Add a functional option to `pkg/ko/publish` to control image names.
To enable the broadest possible support out-of-the-box, this changes our default naming behavior to use shortened names: `{package}-{hash of full import path}`.
The current behavior, which yields better discoverability, can be restored by passing `--preserve-import-paths` or `-P`.
I have verified with this flag that I can publish to DockerHub via `ko`.
Fixes: https://github.com/google/go-containerregistry/issues/160

Change the default behavior to use flat image names.

---

pkg/ko/build/gobuild.go
pkg/ko/build/gobuild_test.go

Because `buf.Bytes()` was called before `defer tw.Close()` in `tarKoData` and `tarBinary`, the returned `[]byte` didn't include tar trailer data added by `tw.Close()`.
Instead, return the `bytes.Buffer` and get its `Bytes()` after the func has returned and `tw.Close()` has been called.
Go's tar package seems to handle trailer-less tar data just fine, as evidenced by the fact that our tests and Docker itself had no problem with these images, but the Python implementation failed to extract layers without the trailer data.

Fix bug where ko layers didn't include tar trailers

---

pkg/authn/helper.go

The credentials helpers used to access osxkeychain and thelike print to stdout which is promne to contain spacing characters. Trimming before comparing to the "magicNotFoundString" fixes a bug where a fallback to anonymous credentials did not work if the user was not logged into the respective registry at all.
Fixes #233

Fix anonymous credential fallback when using keychain credentials.

---

cmd/ko/commands.go
cmd/ko/publish.go
cmd/ko/resolve.go
pkg/ko/publish/daemon.go
pkg/ko/publish/daemon_test.go

To achieve parity between different environments, `--local` should also support short paths.
Fixes #275

Support short path for --local usage.

---

cmd/ko/publish.go
cmd/ko/resolve.go
pkg/crane/append.go
pkg/crane/copy.go
pkg/crane/delete.go
pkg/crane/pull.go
pkg/crane/push.go
pkg/crane/rebase.go
pkg/ko/publish/daemon.go
pkg/ko/publish/daemon_test.go
pkg/ko/publish/default.go
pkg/v1/daemon/write.go
pkg/v1/daemon/write_test.go
pkg/v1/mutate/rebase.go
pkg/v1/mutate/rebase_test.go
pkg/v1/remote/delete.go
pkg/v1/remote/delete_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go
pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

Lots of packages included empty `FooOptions` structs which we could use to allow callers to pass optional options to the methods.
In practice, these didn't add anything and just added a wart. Users had to pass `foo.FooOptions{}`, or `&foo.FooOptions{}`, or `nil` to lots of random methods. We weren't consistent about whether options should be accepted as a pointer or not, or whether absence of options should be expressed as a pointer to an empty struct, or `nil`.
If these methods want to add options in the future, they should do so using functional options, where we can add more options to the method args directly without breaking existing callers.

Remove unused empty Options structs

---

pkg/v1/partial/compressed.go
pkg/v1/partial/configlayer_test.go

This behaviour mirrors `uncompressedImageExtender.LayerByDigest`.
Fixes #284

 compressedImageExtender.LayerByDigest properly finds config layer 

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go

Currently, a `bearerTransport` requests only one token during it's lifetime. After that token expires, all further requests will fail (`401`).
This seems to be the root cause of https://github.com/GoogleContainerTools/kaniko/issues/245
This PR enables `bearerTransport.RoundTrip` to refresh an expired token and retry the request.

Refresh Bearer token

---

.travis.yml
pkg/crane/append.go
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go
pkg/v1/random/image.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go
pkg/v1/stream/layer.go
pkg/v1/stream/layer_test.go
pkg/v1/stream/stream_test.go

This will enable scenarios where layer contents might not fit into available memory before being written to a registry in `remote.Write`.
This PR augments `mutate` and `remote` to lazily compute digests, etc., only after layer contents have been consumed and presumably uploaded to the registry.

Add pkg/v1/stream.NewLayer to stream layer contents

---

pkg/v1/google/auth.go
pkg/v1/google/auth_test.go
pkg/v1/google/keychain.go
pkg/v1/google/testdata/README.md
pkg/v1/google/testdata/key.json

This caches tokens until they're expired, so it's much faster than using
the default keychain.

Implement googley auth methods

---

cmd/ko/flatname.go
cmd/ko/publish.go

A new `-B` or `--base-import-paths` option allows to publish images without appended md5 hash at the end. It is mutually exclusive with existing `-P` option.

Allow to publish images without appended md5 hash

---

pkg/ko/build/gobuild.go

When you run a ko command, it outputs nothing for a few seconds while it
builds go binaries. This change logs the import paths before we invoke
`go build` so that you know what it's doing.

ko: log the import paths we are building

---

cmd/ko/binary.go
cmd/ko/commands.go
cmd/ko/publish.go

This adds support for a `ko run` shortcut that effectively composes
`ko publish` and `kubectl run`.  With this users can containerize and
run a Go binary on Kubernetes in a single command without any yaml.
```
ko run <deployment name> --image=./cmd/binary-name
```

Add support for `ko run`.

---

pkg/v1/remote/write.go

https://github.com/google/go-containerregistry/pull/301 introduced a
pretty big regression in upload speed. To get around this, attempt to
read the config blob before waiting for layer uploads to finish. If we
can read it, add it to the errgroup, otherwise wait for the layers to
finish before attempting to upload the config again.
In my testing, this change shaves ~3s off of ko publishing.

Upload config concurrently if we can

---

pkg/v1/mutate/mutate_test.go

Produced via:
`gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
`goimports -w $(find -name '*.go' | grep -v vendor)`

golang format tools

---

cmd/ko/commands.go
cmd/ko/resolve.go

We were buffering the output of resolveFilesToWriter instead of just
writing directly to kubectl's stdin.

Use Cmd.StdinPipe instead of buffer for kubectl

---

pkg/ko/build/recorder.go
pkg/ko/build/recorder_test.go

This adds an implementation of ko's `build.Interface` that simply records the targets that it is asked to build.

Add a Recorder to compose with builders.

---

pkg/gcrane/list.go

This cuts down on invocations of gcloud, which results in a dramatic
speedup for `gcrane ls -r`.

Use google-specific authenticator for gcrane ls

---

pkg/v1/google/list.go
pkg/v1/remote/image.go
pkg/v1/remote/list.go
pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Fixes #340 
Before:
```
$ crane manifest gcr.io//bad/image
2019/01/08 22:50:02 reading image "gcr.io//bad/image:latest": no token in bearer response:
{"errors":[{"code":"NAME_INVALID","message":"Invalid resource name: \"repository:/bad/image:pull\", must match: \"[a-z0-9._-]+(?:/[a-z0-9._-]+)*\""}]}
```
After:
```
$ crane manifest gcr.io//bad/image
2019/01/08 22:49:19 reading image "gcr.io//bad/image:latest": NAME_INVALID: Invalid resource name: "repository:/bad/image:pull", must match: "[a-z0-9._-]+(?:/[a-z0-9._-]+)*"
```
Note that this moves `CheckError` into the `transport` package so we can use it there as well as in `remote`.

Improve structured error printing

---

Gopkg.lock
cmd/ko/README.md
cmd/ko/filestuff.go
cmd/ko/resolve.go
pkg/ko/build/future.go
pkg/ko/build/future_test.go
pkg/ko/build/shared.go
pkg/ko/build/shared_test.go
pkg/ko/publish/future.go
pkg/ko/publish/future_test.go
pkg/ko/publish/shared.go
pkg/ko/publish/shared_test.go
vendor/github.com/mattmoor/dep-notify/LICENSE
vendor/github.com/mattmoor/dep-notify/pkg/graph/doc.go
vendor/github.com/mattmoor/dep-notify/pkg/graph/interface.go
vendor/github.com/mattmoor/dep-notify/pkg/graph/manager.go
vendor/github.com/mattmoor/dep-notify/pkg/graph/manager_options.go
vendor/github.com/mattmoor/dep-notify/pkg/graph/node.go
vendor/github.com/mattmoor/dep-notify/pkg/graph/set.go

This adds experimental support for fsnotify integration for `ko apply`.
With this change you can run: `ko apply --watch -f config/` and it will perform the typical deployment step, and then begin to monitor the referenced go paths from each of the yaml files for changes using github.com/mattmoor/dep-notify (a Go dependency graph library built around fsnotify).
When a change is found, only the yaml files that reference the image in question are re-applied.  In watch mode, compilation failures are ignored (so they may be remedied and picked up by the watch).

ko apply --watch

---

cmd/ko/commands.go
cmd/ko/publish.go
cmd/ko/resolve.go
cmd/ko/tags.go
pkg/ko/publish/daemon.go
pkg/ko/publish/daemon_test.go
pkg/ko/publish/default.go
pkg/ko/publish/default_test.go
pkg/ko/publish/options.go

Sequence from #277. 
I have changed a little the context of the PR. The previous implementation only let you define additional tags, but when pushing an Image, you should have total control over the tags will be pushed.
There are moments when you don't want to publish a `latest` tag, for example when you need to generate a image from a hotfix from a old version of an application.
So with this in mind, when you pass a `--tag=` flag you override the `latest` default tag.
This closes #181 
Note: this requires some more testing.

Allow to override tags on publish

---

pkg/ko/publish/daemon.go
pkg/ko/publish/daemon_test.go
pkg/v1/daemon/write.go
pkg/v1/daemon/write_test.go

follow up from #345 
With this, the image is written to the docker daemon only once with the first tag and the other tags are added via the `client.ImageTag`.

Load image to daemon only once when writing multiples tags

---

pkg/name/registry.go
pkg/name/registry_test.go

This change assumes RFC1918 addresses are insecure and use the
http scheme.  This is the same as we assume for .local addresses.
With this change images can be built from local insecure registries,
not just pushed.
Fix: #289
Signed-off-by: Berndt Jung <bjung@vmware.com>

Assume RFC1918 addresses are insecure registries

---

pkg/v1/empty/image_test.go
pkg/v1/random/image.go

This is checked by some clients, and using empty.Image fails these
checks because it uses random.Image.

Add "type":"layers" to config RootFS in random

---

pkg/ko/resolve/resolve_test.go

This was testing an image with 1024 layers, each 5 bytes, instead of 5
layers, each 1024 bytes.

Speed up ko resolve test

---

pkg/v1/stream/layer_test.go

2s is pretty long, so this removes one digit.
Also fixes a bug in the test failure output.

Speed up TestLargeStream

---

pkg/v1/hash.go
pkg/v1/hash_test.go

This was getting marshalled incorrectly when not a pointer.

Change Hash MarshalJSON receiver

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go
pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/transport/transport_test.go

This first attempts to use "https" for every request, falling back to
"http" if the registry matches our localhost heuristic or if it is
intentionally set to insecure via name.NewInsecureRegistry.
Fixes #279

Add http fallback

---

pkg/v1/mutate/mutate.go
pkg/v1/random/image.go
pkg/v1/stream/layer_test.go

kaniko's tar files produced error messages about truncated files when
expanding the layers.  This appears to be due to not correctly closing
the tar.Writer in all cases, before using the output.  Closing a
tar.Writer adds padding and a tar file trailer.

Close tar.Writer before using output

---

pkg/v1/v1util/zip.go
pkg/v1/v1util/zip_test.go

Fix `IsGzipped` to handle 0-byte layer tar files.
Fixes #367

Handle 0-byte layer.tar files

---

pkg/v1/config.go
pkg/v1/mutate/mutate_test.go

These are polluting our configs with default values, some of which
aren't present in the OCI config, so we should omit them if they're
empty.

Add omitempty to some config fields

---

pkg/ko/build/gobuild.go
pkg/ko/build/gobuild_test.go

Currently the entrypoint is always '/ko-app', which makes it difficult to tell which ko-built app is which from the host system.
This changes it so that a container built from the importpath
`github.com/knative/serving/cmd/autoscaler`
has an entrypoint of
`/ko-app/autoscaler`
Fixes #375

Name the app using the base of the importpath

---

pkg/v1/index.go
pkg/v1/random/index.go
pkg/v1/random/index_test.go

Update the `v1.ImageIndex` definition to be more usable and more similar to the `v1.Image` definition.
Also adds a `random.Index` as a starting point so we can test other implementations.

Random index

---

pkg/v1/remote/image.go
pkg/v1/remote/image_test.go
pkg/v1/remote/index.go
pkg/v1/remote/index_test.go
pkg/v1/remote/write_test.go

This adds support for reading an ImageIndex from a remote repository.
I refactored some of the shared code between `Index` and `Image` to a separate "fetcher" struct. We should probably pull all of this out into a separate remote client that is shared between the read and write path, since it's very similar, but that's out of scope for this PR.
See #119 
Write support incoming once this lands.

Implement remote.Index

---

pkg/crane/copy.go
pkg/gcrane/copy.go

This adds support to `crane cp` and `gcrane cp` for copying indexes.

crane/gcrane: Support copying Indexes

---

pkg/name/digest.go
pkg/name/digest_test.go

Allow tag and digest

---

pkg/name/digest.go
pkg/name/digest_test.go

This was allowing a missing digest after "@" for weak validation. That
doesn't make sense for digests because there's no way to have a default
digest.

Always validate digests in NewDigest

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go
pkg/v1/stream/layer.go

Fixes issue in https://github.com/GoogleContainerTools/kaniko/pull/599
Prior to #301 we deduped layers using `BlobSet`, but that was dropped when some layers might not be digestable ahead of time.
~~TODO: tests, I wanted to get this out in case there were comments about the overall direction.~~

Dedupe layer uploads where possible

---

pkg/v1/image.go
pkg/v1/mutate/mutate.go
pkg/v1/partial/compressed.go
pkg/v1/partial/uncompressed.go
pkg/v1/partial/with.go

It doesn't appear to be used anywhere in go-containerregistry itself, and looking at some of the users of the library I couldn't find any usage there either (sorry if I missed one!)
With the introduction of `stream.Layer`, `BlobSet` could return `stream.ErrNotComputed` if any layer was a streaming layer, which isn't a great UX. As an alternative to removing it, we could make `BlobSet` only include blobs for which it knows the digest, but I'm not sure that's a great UX either. This made me realize I'm not really sure what the use case is for `BlobSet`...
This is a backward-incompatible change in cases where some project did call `img.BlobSet()` for whatever reason, but any implementations of the `Image` interface that happen to implement `BlobSet` won't be broken by the change at least.

Remove BlobSet from Image interface

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Uploading to Quay is failing with `INVALID_REQUEST: Invalid request`. My theory is this mounting quirk, but we still need to confirm this fixes things before merging.

Only attempt to mount for MountableLayer

---

pkg/v1/remote/image.go
pkg/v1/remote/image_test.go
pkg/v1/remote/options.go

We currently rely on the registry to do fallback for us, but this is
unreliable:
* Some registries won't do it.
* This only works for amd64/linux

Resolve manifest lists to manifests in remote.Image

---

pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

Having a RepoTags entry is optional, it is possible
to write without tags using digests - making it "null"
Added convenience functions and new "Ref" variants,
since it is not possible to cast arrays of interfaces.

Allow both Tag and Digest (Reference) for write

---

pkg/v1/remote/check.go
pkg/v1/remote/check_test.go

Ideas welcome on a better name. I didn't want to add a more generic "can I (push | pull)?" method since it's already pretty trivial to pull an image, and not costly since you'll fail to pull the manifest first.
The immediate use is in Kaniko, which takes a `--destination` flag and could fail fast if the current creds don't have permission to push to that destination. `ko` could likewise fail fast before `go build`ing if the current creds don't have permission on `KO_DOCKER_REPO`.
Callers that already have an image constructed and just want to push it (e.g., `crane push`) should call `remote.Write` to avoid unnecessary calls to `initiateUpload`.

Add remote.CheckPushPermission

---

pkg/crane/copy.go
pkg/crane/digest.go
pkg/crane/get.go
pkg/crane/manifest.go
pkg/gcrane/copy.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/descriptor_test.go
pkg/v1/remote/image.go
pkg/v1/remote/image_test.go
pkg/v1/remote/index.go
pkg/v1/remote/index_test.go
pkg/v1/remote/options.go

This resolves a mismatch between how registries actually work and our
Image/ImageIndex interfaces. Since we don't know what type of artifact a
registry stores, we need some kind of union type to represent either
of them. This allows clients to reason about what type of artifact they
got back from the registry, and efficiently "cast" it to the right
implementation. This removes the need to do fallback.
remote.Descriptor embeds a v1.Descriptor, so it contains MediaType,
Size, and Digest, but it also has a Manifest field so we can access
the raw response from the registry. This is useful for crane digest and
crane manifest, where we dont' want to interpret the response, just show
what's there.
The remote.Image and remote.Index functions have been rewritten to use
remote.Descriptor under the …

Add remote.Descriptor

---

pkg/v1/google/auth.go

It's not the prettiest change ever, but it keeps the error in the general case, but allows to fallthrough in a `multikeychain`. This type of errors could be used for other chains too :angel: 
It fixes cases where using `google.Keychain` with `authn.NewMultiKeychain` where `gcloud` command is not available (see https://gist.github.com/vdemeester/c397ffb3fd19b4cc2ba3243dc4db9f83). It should use `Anonymous` instead of failing hard in that case.
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

authn/k8schain : fallthrough in case of `gcloud` command not available

---

pkg/v1/tarball/layer.go
pkg/v1/tarball/layer_test.go

This provides a more idiomatic way to create
layers from readers without having to understand Openers.

Add tarball.LayerFromReader

---

pkg/name/check.go
pkg/name/digest.go
pkg/name/options.go
pkg/name/ref.go
pkg/name/registry.go
pkg/name/repository.go
pkg/name/tag.go

This changes the Strictness parameter to be a more general Option so
that we can also pass in name.Insecure for insecure registries.
Note that by changing the name.StrictValidation and name.WeakValidation
enums to be Options, this change avoids breaking callers or introducing
new methods.
Fixes https://github.com/google/go-containerregistry/issues/416

Refactor pkg/name to use options

---

pkg/v1/mutate/mutate.go

This allows external libraries to specify a v1.ConfigFile when creating an image.

Make mutate.ConfigFile public

---

pkg/v1/remote/image_test.go

In #398 we changed the manifest resolution to default to amd64/linux but
didn't update the test, which expected resolution to use the current
runtime. Travis didn't catch this because it runs on amd64/linux.

Fix test to not depend on current runtime

---

pkg/v1/remote/write.go

Assume errors in v1.Layer.Digest are related to streaming.
Retry any errors that could be related to streaming layers after we've
uploaded all layers.
Remove any references to stream.Layer from remote.

Rewrite remote streaming layer handling

---

cmd/crane/doc/crane.md
cmd/crane/doc/crane_export.md
pkg/crane/export.go

This is useful for viewing the filesystem of a remote image without having to fiddle with assembling the layers after a `crane pull`.
For example, if you wanted to see the files in the "ubuntu" image:
```
$ crane export ubuntu - | tar tv
```

Add crane export

---

cmd/registry/main.go
pkg/registry/blobs.go
pkg/registry/error.go
pkg/registry/example_test.go
pkg/registry/manifest.go
pkg/registry/registry.go
pkg/registry/registry_test.go

- Add manifest support
- Increase Coverage
- Support monolithic, stream and chunked uploads.
- Add locks for concurrency.
- Add headers and path changes to get docker + crane working.
- Store manifest content type to get docker working with crane pushed container.
- Return spec compatible error codes everywhere.
- Log all requests (and failures).

registry: Full implementation

---

pkg/registry/example_test.go
pkg/registry/registry.go

This allows the package comment to correctly show up in go doc.

registry: Fix comment form and example name.

---

pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go
pkg/v1/remote/write.go

To close https://github.com/google/go-containerregistry/issues/431
I'm still new to Go so am especially receptive to changes. It seems like there should be tests for the retry, but I wasn't sure if there's a most idiomatic way

Retry layer upload on BLOB_UPLOAD_INVALID error

---

pkg/v1/remote/transport/basic.go
pkg/v1/remote/transport/basic_test.go

To fix https://github.com/google/go-containerregistry/issues/468

Skip sending Authorization header if it's empty

---

pkg/internal/retry/retry.go
pkg/internal/retry/retry_test.go
pkg/v1/google/list.go
pkg/v1/remote/options.go
pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go
pkg/v1/remote/transport/retry.go
pkg/v1/remote/transport/retry_test.go
pkg/v1/remote/write.go

We pretty commonly see this issue when communicating with a registry:
```
Get https://gcr.io/v2/: net/http: TLS handshake timeout
```
This causes a huge amount of pain if it's a failure within e.g. a large
CI job, since the entire thing would fail.
Fixes #77
This uses `k8s.io/apimachinery/pkg/util/wait` because we happen to already depend on it.

Add retries for temporary network issues

---

cmd/crane/cmd/append.go
cmd/crane/cmd/config.go
cmd/crane/cmd/copy.go
cmd/crane/cmd/delete.go
cmd/crane/cmd/digest.go
cmd/crane/cmd/export.go
cmd/crane/cmd/list.go
cmd/crane/cmd/manifest.go
cmd/crane/cmd/pull.go
cmd/crane/cmd/push.go
cmd/crane/cmd/rebase.go
cmd/crane/cmd/root.go
cmd/crane/cmd/validate.go
cmd/crane/cmd/version.go
cmd/crane/help/main.go
cmd/crane/main.go
cmd/gcrane/main.go
pkg/crane/append.go
pkg/crane/config.go
pkg/crane/copy.go
pkg/crane/delete.go
pkg/crane/digest.go
pkg/crane/export.go
pkg/crane/pull.go
pkg/crane/push.go

Fixes #407
This change used to be a bit more compelling, before we started using functional options for everything, since it saves a bit of boilerplate. As is, it mostly just saves parsing strings via `name.ParseReference` and typing `remote.WithAuthFromKeychain(authn.DefaultKeychain)`.
I do think this strikes a nice balance for people who don't necessarily want to learn about our abstractions but do want to do something more sophisticated than what the `crane` CLI happens to expose.

Turn crane into a library

---

cmd/gcrane/main.go
pkg/authn/keychain.go
pkg/crane/copy.go
pkg/gcrane/copy.go
pkg/logs/logs.go
pkg/v1/cache/cache.go
pkg/v1/google/auth.go
pkg/v1/google/options.go
pkg/v1/remote/options.go
pkg/v1/remote/write.go

Fixes #480
We log for two reasons:
1. Warning for something that might have gone wrong.
2. Progress for things that are going right.
This introduces logs.Warn and logs.Progress which just expose two
package level log.Loggers, which will allow consumers of this library to
override them.
cc @dgageot this will make our library not log anything by default, see `cmd/crane/main.go` for enabling progress and/or warning logs. We'll want to do the same for `ko` to keep the same behavior.

Add logs package

---

pkg/registry/blobs.go
pkg/registry/compatibility_test.go
pkg/registry/error.go
pkg/registry/example_test.go
pkg/registry/manifest.go
pkg/registry/registry.go
pkg/registry/registry_test.go
pkg/registry/tls.go
pkg/registry/tls_test.go

This handles the complexity of generating certs and forcing transports
to the server with the correct root ca. This should be usable for
replacing any given container registry in a test.

Create a tls version of the registry.New()

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go

Previously the code considered 'https://registry.example.com/' functionally different to 'https://registry.example.com:443', and similarly for 'http' and port 80.  This change always resolves Host values (which in Go may or may not be a combination of host and port) to include the host and port based on the scheme being used such that these two examples are considered functionally equivalent.
This should resolve https://github.com/google/go-containerregistry/issues/472

Resolve ports to well-known values when comparing Host values to decide whether or not to send Bearer Authorization header

---

pkg/registry/blobs.go
pkg/registry/error.go
pkg/registry/example_test.go
pkg/registry/manifest.go
pkg/registry/registry.go
pkg/registry/registry_test.go
pkg/registry/tls.go
pkg/registry/tls_test.go

Hopefully this will make sure that people understand it's current production state and fix go doc.

registry: Add a disclaimer and fix copyright headers.

---

pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go
pkg/v1/remote/write_test.go

This allows for much better debugging of the returned error.

transport: Store statuscode and body within transport.Error

---

pkg/v1/mutate/mutate.go

Missed this in https://github.com/google/go-containerregistry/pull/423 cc @dprotaso

Use layer's MediaType in mutate

---

Gopkg.lock
pkg/internal/retry/retry.go
pkg/internal/retry/retry_test.go
pkg/internal/retry/wait/kubernetes_apimachinery_wait.go
pkg/v1/remote/transport/retry.go
pkg/v1/remote/transport/retry_test.go
pkg/v1/remote/write.go

The core container pushing logic uses Kubernetes helper libraries to implement exponential backoff in the retry logic. This is a fairly small behavior but an enormous dependency, and it brings in transitive deps such as `k8s.io/klog` that conflict with other broadly used libraries (in our case, `github.com/golang/glog`).
This PR commits a trimmed-down version of `k8s.io/apimachinery/pkg/util/wait` as `github.com/google/go-containerregistry/pkg/internal/retry/wait`, containing only the code required to implement `wait.ExponentialBackoff()`.

Use a trimmed-down copy of `wait.go` to avoid large k8s.io dependency.

---

pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

Add URLs and Annotations to what you can append with mutate.Append.
This makes it possible to easily create images:
* with foreign layers and
* with annotations.
Progress towards https://github.com/google/go-containerregistry/issues/207

Expand mutate.Addendum

---

pkg/v1/empty/image.go
pkg/v1/mutate/mutate_test.go
pkg/v1/mutate/rebase_test.go
pkg/v1/mutate/whiteout_test.go
pkg/v1/random/image.go
pkg/v1/tarball/write_test.go

This inverts the dependency between empty.Image and random.Image.
Previously, empty.Image was implemented as `random.Image(0, 0)`, which is cute, but ended up duplicating things we didn't need. Instead, `random.Image` is implemented by appending `random.Layers`s to an `empty.Image`, which dramatically simplifies the implementation of `random.Image`.
In order to make that work, I needed to shuffle around some tests to avoid import cycles.
I also dropped a ton of test code that was duplicating what `validate.Image` does.

Invert empty's dependency on random

---

pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go
pkg/v1/remote/layer.go
pkg/v1/remote/layer_test.go
pkg/v1/remote/write.go

This provides direct access to a blob in a registry instead of having to
go through remote.Image.
Specifically, this is useful for:
* Accessing unreferenced layers in a registry.
* Pulling schema 1 layers.
* Inspecting the contents of a layer.
Progress towards https://github.com/google/go-containerregistry/issues/500

Add remote.Layer, remote.WriteLayer

---

pkg/crane/copy.go
pkg/gcrane/copy.go
pkg/internal/legacy/copy.go
pkg/internal/legacy/copy_test.go

Adds a new package, pkg/internal/legacy, where we can keep this without worrying about the API being terrible.
Fixes https://github.com/google/go-containerregistry/issues/500

Implement schema 1 image copying

---

pkg/v1/hash.go
pkg/v1/hash_test.go
pkg/v1/partial/with.go
pkg/v1/remote/image.go
pkg/v1/remote/image_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go
pkg/v1/tarball/image.go
pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go
pkg/v1/types/types.go
pkg/v1/types/types_test.go

Fixes https://github.com/google/go-containerregistry/issues/207
* Support downloading layers from the `URLs` field in a `remote.Image` manifest.
* Skip uploading foreign layers.
* Populate `LayerSources` when writing a `tarball.Image`.
* Read `LayeSources` when reading a `tarball.Image`.

Implement foreign layer support

---

pkg/gcrane/copy.go
pkg/gcrane/copy_test.go

This will naturally throttle us based on our concurrency.
Also adds retry with backoff in case we hit 429s, 5xxs or temporary
errors with GCR.
Fixes #424

gcrane: use a task queue when copying images

---

pkg/authn/helper.go
pkg/authn/helper_test.go
pkg/authn/k8schain/k8schain.go
pkg/authn/k8schain/k8schain_test.go
pkg/authn/keychain.go
pkg/authn/keychain_test.go
pkg/authn/multikeychain.go
pkg/authn/multikeychain_test.go
pkg/v1/google/keychain.go
pkg/v1/remote/delete.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/layer.go
pkg/v1/remote/list.go
pkg/v1/remote/options.go
pkg/v1/remote/write.go

Fixes #495
Introduces `authn.Target` which both `name.Repository` and `name.Registry` implement, so this should be backwards compat.

Update Keychain interface to accept repo

---

pkg/v1/google/auth.go
pkg/v1/remote/descriptor.go

Fixes https://github.com/google/go-containerregistry/issues/390
I don't think that there's actually ever going to be a better logging solution than https://github.com/google/go-containerregistry/pull/481 because logging is terrible, so closing this.

Fix logging TODOs

---

pkg/v1/empty/index.go
pkg/v1/fake/image.go
pkg/v1/fake/index.go
pkg/v1/image.go
pkg/v1/index.go
pkg/v1/layout/index.go
pkg/v1/mutate/mutate.go
pkg/v1/partial/compressed.go
pkg/v1/partial/uncompressed.go
pkg/v1/partial/with.go
pkg/v1/partial/with_test.go
pkg/v1/random/index.go
pkg/v1/random/index_test.go
pkg/v1/remote/index.go
pkg/v1/validate/image.go
pkg/v1/validate/index.go
pkg/v1/zz_deepcopy_generated.go

In isolation, this seems rather silly, since you can get just `RawManifest` from either, but this allows us to use a common interface between `v1.Image`,`v1.ImageIndex`, and `v1.Layer` that has enough methods to generate a minimum viable `v1.Descriptor` 🎉 
This is useful for appending things to an index, see https://github.com/google/go-containerregistry/pull/520#issuecomment-530463027
This is breaking but I suspect there aren't that many implementations of `v1.Image` outside of this library. If there are, this is a trivial method to implement (and you get it for free if you're using `partial`).

Add Size to v1.Image and v1.ImageIndex

---

pkg/v1/mutate/image.go
pkg/v1/mutate/index.go
pkg/v1/mutate/index_test.go
pkg/v1/mutate/mutate.go
pkg/v1/validate/index.go

Add an `AppendManifests` function that adds entries to the `manifests` clause of an index.
Fixes https://github.com/google/go-containerregistry/issues/474

Implement index mutation

---

pkg/authn/helper.go

Fixes #528
This is much more useful:
```
$ crane push busybox.tar gcr.io/jonjohnson-test/tarballs/busybox:docker
Reauthentication required.
ERROR: (gcloud.auth.docker-helper) There was a problem reauthenticating while refreshing your current auth tokens: Reauthentication challenge could not be answered because you are not in an interactive session.
Please retry your command or run:
$ gcloud auth login
To obtain new credentials.
2019/09/16 08:22:54 pushing gcr.io/jonjohnson-test/tarballs/busybox:docker: Get https://gcr.io/v2/token?scope=repository%3Ajonjohnson-test%2Ftarballs%2Fbusybox%3Apush%2Cpull&service=gcr.io: invoking docker-credential-gcloud: exit status 1; output: 
```

Wire up cred helper stderr

---

pkg/name/digest.go
pkg/name/errors_test.go
pkg/name/ref.go
pkg/name/tag.go

This modifies String() to return the original input and Name() returns
the defaulted string.
Fixes https://github.com/google/go-containerregistry/issues/527

Preserve input strings for name.Reference

---

pkg/gcrane/copy.go

Leftover from https://github.com/google/go-containerregistry/issues/349
Before:
```
$ gcrane cp -r gcr.io/google-containers/busybox gcr.io/jonjohnson-test/google-containers/busybox
2019/09/12 13:27:30 existing blob: sha256:aab39f0bc16d3c109d7017bcbc13ee053b9b1b1c6985c432ec9b5dde1eb0d066
2019/09/12 13:27:30 existing blob: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
2019/09/12 13:27:30 existing blob: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
2019/09/12 13:27:30 existing blob: sha256:eeee0535bf3cec7a24bff2c6e97481afa3d37e2cdeff277c57cb5cbdb2fa9e92
2019/09/12 13:27:31 mounted blob: sha256:138cfc514ce4b3f1f8d57b2f9766fcb5ffab791110bcd8610e8d762cc78d28b2
2019/09/12 13:27:31 existing blob: …
```

Clean up #349 TODO

---

pkg/v1/remote/error_roundtrip_test.go
pkg/v1/remote/transport/ping.go

I added a high level test that the operation returns an error for a
server which only returns one status code. I'll probably add a few more
cases to help find other pathways that are swallowing the error and
contained status code.

transport: Fix ping code to wrap errors in a transport.Error

---

pkg/v1/remote/image.go

The descriptor.Image() code handles docker v2schema1 images cleanly, but
the Image code resricts the list, causing certain repositories to return
ManifestUnknown for images that exist.
By using the Get function, we reduce code slightly and handle schema1
images with an error that doesn't appear to imply that the image does
not exist.

remote: Call Get() directly from remote.Image()

---

go.mod
go.sum
pkg/internal/compare/doc.go
pkg/internal/compare/image.go
pkg/internal/compare/image_test.go
pkg/internal/compare/index.go
pkg/internal/compare/index_test.go
pkg/internal/compare/layer.go
pkg/internal/compare/layer_test.go
pkg/v1/daemon/image_test.go
pkg/v1/remote/layer_test.go
pkg/v1/tarball/layer_test.go
pkg/v1/tarball/write_test.go

This drops a lot of testing boilerplate.
This is under pkg/internal for now because I'm not sure if I love the interface.

Implement pkg/internal/compare, use it

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go

Fall back to oauth flow with username/password

---

pkg/crane/pull.go
pkg/gcrane/copy.go
pkg/internal/legacy/copy.go
pkg/name/repository.go
pkg/name/repository_test.go
pkg/v1/remote/index.go
pkg/v1/remote/write.go

Fixes #563
These are useful for creating a child digest/tag from a repository, which is something we need to do in remote. Before, we were throwing away the insecure option, which this approach fixes.

Add name.Repository helpers

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

See https://github.com/bazelbuild/rules_docker/issues/1193#issuecomment-540712704
This broke because:
https://github.com/bazelbuild/rules_docker/blob/72fe2bb93e6d59c1f8823421a1b914a3058b90e2/container/go/cmd/pusher/pusher.go#L66
and 
https://github.com/docker/cli/blob/3e07fa728a3025cf4205e3dd071da703c34cf45f/cli/config/config.go#L25
don't work together. We used to parse the config file ourselves and read from the env every time we called into the keychain, but docker does this once on startup.

Re-read $DOCKER_CONFIG when we load the config file

---

pkg/v1/layout/index.go
pkg/v1/layout/index_test.go
pkg/v1/layout/testdata/test_index/blobs/sha256/2b29a2b8dea3af91ea7d0154be1da0c92d55ddd098540930fc8d3db7de377fdb
pkg/v1/layout/testdata/test_index/index.json

... rather than assuming all indexes have media type application/vnd.oci.image.index.v1+json.

Respect mediaType of index in layout

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go
pkg/v1/remote/transport/schemer.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/transport/transport_test.go
pkg/v1/remote/transport/useragent.go

These were only set for the bearer transport, but we care about basic
and anonymous as well.
Context: https://github.com/GoogleContainerTools/kaniko/pull/817

Always wrap transports for scheme and useragent

---

go.mod
go.sum
pkg/v1/stream/layer.go
pkg/v1/stream/layer_test.go
pkg/v1/tarball/layer.go
pkg/v1/tarball/layer_test.go

Resolves #572
Signed-off-by: Javier Romero <jromero@pivotal.io>

Add compression option to tarball.Layer and stream.Layer

---

cloudbuild.yaml

Supercedes #580
* Tag pushed images with the commit SHA
* Remove unnecessary tag, and just tag with `ko`
* Use official `golang` image instead of `gcr.io/cloud-builders/go` which provides wonky stuff to support pre-modules Go packages, which go-containerregistry is not. (new since #580)
The new logic is:
1. `GOPATH=/workspace/gopath go get github.com/google/ko/cmd/ko`
1. `/workspace/gopath/bin/ko publish -B github.com/google/go-containerregistry/cmd/crane -t latest -t $COMMIT_SHA`
1. `/workspace/gopath/bin/ko publish -B github.com/google/go-containerregistry/cmd/gcrane -t latest -t $COMMIT_SHA`
1. (using just-built `crane` image) `crane digest gcr.io/$PROJECT_ID/crane`
1. (using just-built `gcrane` image) `gcrane digest gcr.io/$PROJECT_ID/gcrane`

Improve cloudbuild.yaml

---

cmd/crane/cmd/config.go
cmd/crane/cmd/copy.go
cmd/crane/cmd/delete.go
cmd/crane/cmd/digest.go
cmd/crane/cmd/export.go
cmd/crane/cmd/list.go
cmd/crane/cmd/manifest.go
cmd/crane/cmd/pull.go
cmd/crane/cmd/push.go

```
$ crane pull ubuntu
Error: accepts 2 arg(s), received 1
Usage:
crane pull IMAGE TARBALL [flags]
Flags:
-c, --cache_path string   Path to cache image layers
-h, --help                help for pull
Global Flags:
-v, --verbose   Enable debug logs
accepts 2 arg(s), received 1
```
Fixes https://github.com/google/go-containerregistry/issues/433

Add better usage

---

pkg/v1/remote/transport/logger.go

Using Printf with the output of the httputil dumpers caused strange
output because the url-encoded scopes included percent characters.
We are just printing a string, so we can use Println instead of Printf.
See https://github.com/bazelbuild/rules_docker/issues/1193#issuecomment-543392322

Use Println to avoid spurious MISSING warnings

---

pkg/gcrane/copy.go

This regressed in https://github.com/google/go-containerregistry/pull/509
Fixes https://github.com/google/go-containerregistry/issues/593

Fix gcrane cp credentials

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

@jonjohnsonjr As promised, I implemented the fix we discussed. I also added a test to enforce the implementation.
See #600

Prevent asking pull scope for cross-repo mounting

---

.ko/debug/.ko.yaml
cloudbuild.yaml

Fixes https://github.com/google/go-containerregistry/issues/605
```
$ docker run -it --entrypoint "/busybox/sh" gcr.io/jonjohnson/crane:debug@sha256:3c4b1ba2483c8ef840db25beabbb4df1fb17634e471daf559157317b01033e32
Unable to find image 'gcr.io/jonjohnson/crane:debug@sha256:3c4b1ba2483c8ef840db25beabbb4df1fb17634e471daf559157317b01033e32' locally
sha256:3c4b1ba2483c8ef840db25beabbb4df1fb17634e471daf559157317b01033e32: Pulling from jonjohnson/crane
9ff2acc3204b: Already exists 
69e2f037cdb3: Already exists 
0ab175cd7cdc: Already exists 
72164b581b02: Already exists 
b707ebaa82ab: Pull complete 
Digest: sha256:3c4b1ba2483c8ef840db25beabbb4df1fb17634e471daf559157317b01033e32
Status: Downloaded newer image for gcr.io/jonjohnson/crane@sha256:3c4b1ba2483c8ef840db25beabbb4df1fb17634e471daf559157317 …
```

Publish debug images

---

pkg/gcrane/copy.go
pkg/gcrane/list.go
pkg/gcrane/root.go
pkg/v1/google/auth.go
pkg/v1/google/auth_test.go
pkg/v1/google/list.go
pkg/v1/google/list_test.go

Also ensure consistent `Use` field between duplicated commands, since
this is used to dedupe them in gcrane.

Add verbose flag to gcrane

---

pkg/v1/remote/transport/logger.go

URL-encoded stuff was getting escaped poorly.

Fix logger transport

---

pkg/crane/copy.go

Pulling and Pushing might indicate we're actually downloading and
uploading blobs, but that's (usually) not the case.

Make progress logs less scary for crane cp

---

cmd/gcrane/cmd/copy.go
cmd/gcrane/cmd/gc.go
cmd/gcrane/cmd/list.go
cmd/gcrane/cmd/root.go
cmd/gcrane/main.go
pkg/gcrane/copy.go
pkg/gcrane/copy_test.go
pkg/gcrane/options.go

This mirrors a similar change we did for crane: https://github.com/google/go-containerregistry/pull/478
The only thing I'm really comfortable with exposing as a library at the moment is the copy stuff. This PR includes `gcrane.Copy` and `gcrane.CopyRepository` (feel free to bikeshed names).
The difference between `gcrane.Copy` and `crane.Copy` is that we'll use the google-specific credential magic for gcrane.
In order to make `CopyRepository` a bit more palatable, I've added the `WithJobs` (again, happy to bikeshed names) option to specify concurrency.
Some small differences in implementation that drop the code size quite a bit:
* https://github.com/google/go-containerregistry/pull/603 allows me to stop plumbing authenticators around.
* …

Refactor pkg/gcrane quite a bit

---

pkg/v1/mutate/image.go
pkg/v1/mutate/index.go
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go
pkg/v1/types/types.go

Fixes https://github.com/google/go-containerregistry/issues/491
For reasons that are fun to explain, I need this for https://github.com/google/ko/pull/38 to work with GCR, as well :smile:

Allow mutation of image or index media types

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go

Only use oauth flow with IdentityTokens

---

pkg/authn/k8schain/k8schain.go
pkg/authn/k8schain/k8schain_aws.go
pkg/authn/k8schain/k8schain_azure.go
pkg/authn/k8schain/k8schain_gcp.go

Each files for each provider (aws, azure, gcp, …) have a "negative"
build tag, this means by default, no behaviour change, they are all
compiled — but they can be disabled using `disable-…`.
This allows a library to depend on k8schain but not having those
automatic import, or at least choose the one to enable/disable.
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Separate credentialprovider into files with buildtag 🏷

---

pkg/crane/catalog.go
pkg/internal/retry/retry.go
pkg/v1/remote/catalog.go
pkg/v1/remote/list.go
pkg/v1/remote/transport/retry_test.go

* Adds support for pagination on /v2/repo/tags/list
* Apply same logic for catalog /v2/_catalog
Instead of setting the url parameters `n` and `last` manually the logic only relies on the `Link` header as described in https://docs.docker.com/registry/spec/api/#pagination.
#549

Use Link header for pagination

---

cmd/crane/cmd/append.go
cmd/crane/cmd/export.go
cmd/crane/cmd/pull.go
cmd/crane/cmd/push.go
cmd/crane/cmd/rebase.go
cmd/crane/cmd/validate.go
cmd/crane/doc/crane_append.md
cmd/crane/doc/crane_export.md
cmd/crane/doc/crane_pull.md
cmd/crane/doc/crane_push.md
cmd/crane/doc/crane_rebase.md
cmd/crane/doc/crane_validate.md
pkg/crane/crane_test.go
pkg/crane/pull.go
pkg/crane/push.go

**What this PR does / why we need it**:
Adds the ability to push and pull from insecure registries to the crane cmd.
The flag also had to be added to a few other subcommands like export, append and etc.
**Which issue this PR fixes**:
fixes #633 
**Special notes for your reviewer**:
I wasn't sure if it's ok to change the handler map in the validate subcommand without any prior discussions, so I just added the options argument to `makeTarball` as a temporary fix so we don't have failing tests.
Let me know if it's ok to change the handler map and also what do you think is a good approach to change it.
https://github.com/google/go-containerregistry/pull/634/files#diff-67c9d71faf9a3b5faa49b6f666170f54R72

Add insecure flag to push and pull

---

cmd/crane/cmd/append.go
cmd/crane/cmd/config.go
cmd/crane/cmd/copy.go
cmd/crane/cmd/delete.go
cmd/crane/cmd/digest.go
cmd/crane/cmd/export.go
cmd/crane/cmd/list.go
cmd/crane/cmd/manifest.go
cmd/crane/cmd/pull.go
cmd/crane/cmd/push.go
cmd/crane/cmd/rebase.go
cmd/crane/cmd/root.go
cmd/crane/cmd/tag.go
cmd/crane/cmd/validate.go
pkg/crane/catalog.go
pkg/crane/config.go
pkg/crane/copy.go
pkg/crane/crane_test.go
pkg/crane/delete.go
pkg/crane/digest.go
pkg/crane/get.go
pkg/crane/list.go
pkg/crane/manifest.go
pkg/crane/options.go
pkg/crane/pull.go
pkg/crane/push.go
pkg/crane/tag.go

I realized I want to be able to inject my own transport for crane, but
that's going to be impossible if we only accept name options, so this
wraps this options (again, sigh) in a way that lets us extend to other
packages.
This also drops -i as an option for insecure (breaking, but so briefly).

Add crane.Option and make --insecure global

---

pkg/legacy/tarball/write_test.go
pkg/v1/partial/compressed_test.go
pkg/v1/partial/uncompressed.go
pkg/v1/partial/uncompressed_test.go
pkg/v1/remote/transport/basic_test.go
pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go
pkg/v1/remote/transport/transport_test.go
pkg/v1/remote/write_test.go

This also drops a bunch of test code from legacy/tarball that the `compare` package takes care of.

Add tests to pkg/v1/{partial,remote,transport}

---

pkg/authn/k8schain/k8schain.go

- This allows for credential providers to load flags before Keyring initialization
- Tests no longer appear to adjust origKeyRing
As an example, the Azure credential helper requires the [azure-container-registry-config](https://github.com/kubernetes/kubernetes/blob/387e6931e5fd63e8a7e353fa01b02a2ab218149c/pkg/credentialprovider/azure/azure_credentials.go#L40) flag to be set in order for the credential provider to report that it is [enabled](https://github.com/kubernetes/kubernetes/blob/387e6931e5fd63e8a7e353fa01b02a2ab218149c/pkg/credentialprovider/azure/azure_credentials.go#L156). Inlining `NewDockerKeyring`allows the "azure-container-registry-config" flag to be processed ahed of time and the Azure provider to be included.

Inline NewDockerKeyring

---

pkg/legacy/tarball/write.go
pkg/legacy/tarball/write_test.go
pkg/v1/partial/compressed_test.go
pkg/v1/partial/uncompressed_test.go
pkg/v1/partial/with.go
pkg/v1/partial/with_test.go

This allows access to an optional method that v1.Layers can implement to
cheaply get the size of the uncompressed contents of a layer. This is
useful in situations where you need to know the size of the contents
before writing them (e.g. pkg/legacy/tarball.Write).
I dropped the `ReadAll` call in the "slow path". This means that the `Uncompressed` bytes aren't buffered (yay), but if using a streaming layer, we might accidentally consume it. The only known uses of the legacy package _don't_ use streaming layers, so we can cross that bridge when we get to it.

Implement partial.UncompressedSize

---

pkg/v1/tarball/image.go

It fixes the following problem when pushing images:
`Dockerfile`:
```
FROM scratch
ENV foo=
```
Shell session reproducing the problem:
```
$ docker build -t 2opremio/flux:empty .
Sending build context to Docker daemon  10.75kB
Step 1/2 : FROM scratch
---> 
Step 2/2 : ENV foo=
---> Using cache
---> 3f8017fe3087
Successfully built 3f8017fe3087
Successfully tagged 2opremio/flux:empty
$ docker push 2opremio/flux:empty
The push refers to repository [docker.io/2opremio/flux]
empty: digest: sha256:3814b642f5c61a77247936fc05d926dcd96f98016cd8e5ec94b7ef18f6d44ce0 size: 314
$ crane push empty.tar 2opremio/flux:empty2
2020/01/20 15:28:43 loading empty.tar as tarball: 0 layers found in image
```
Note how Docker doesn't have a problem pushing the layerles image
With the fix in this PR:
```
$ crane …
```

crane: Allow loading layerless images

---

pkg/internal/legacy/copy.go
pkg/internal/legacy/copy_test.go
pkg/v1/remote/check.go
pkg/v1/remote/layer_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

This is breaking, but I suspect there aren't many consumers. We don't
actually need a name.Digest in order to upload a layer, it was just
easier because the writer{} took a ref. I restructured commitImage to
take the ref directly instead of stashing it away in the writer{}.
If you wanted to do a streaming layer upload with WriteLayer, you'd have
to conjure up a fake name.Digest. That is no longer required, since all
we really need is the repository.

Change signature of remote.WriteLayer

---

pkg/gcrane/copy.go
pkg/gcrane/copy_test.go
pkg/internal/httptest/httptest.go
pkg/registry/tls.go
pkg/v1/google/list.go
pkg/v1/google/list_test.go

I split off the useful parts of `registry.TLS` from pkg/registry, fixed up the marshalling/unmarshalling of `google.ManifestInfo` so that it would roundtrip through bytes, and implemented a fake GCR that returns an appropriate response when the client tries to list tags.

Add tests for gcrane.Copy[Repository]

---

cmd/crane/cmd/append.go
cmd/crane/doc/crane_append.md
pkg/crane/append.go

Allow multiple layers to be appended (via multiple -f flags, a la
kubectl apply).
Make "base" optional, which then uses empty.Image as the base.

crane append: multiple layers, empty base

---

pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go

Include http request in error message to provide context for what
failed.
Format multiple errors a bit better.
Add test coverage for when reading the response body fails.

Improve transport.Error

---

cmd/crane/cmd/pull.go
cmd/crane/doc/crane_pull.md
pkg/crane/crane_test.go
pkg/crane/pull.go

Fixes #621
This adds the --format flag with values "tarball" (default), "legacy"
(for saving pkg/legacy/tarball images, for compatibility with some
software that assumes the old format), and "oci", which saves the image
as an OCI image layout.

Add --format flag to `crane pull`

---

pkg/v1/google/auth_test.go
pkg/v1/google/keychain.go
pkg/v1/google/list.go
pkg/v1/google/list_test.go

- Use googleKeychain to authenticate to pkg.dev registries
- Handle schema difference for the list operation. GCR returns
timeUploadedMs as a string, while AR returns the same field
as int64

Make gcrane work with Artifact Registry

---

pkg/v1/mutate/image.go
pkg/v1/mutate/index.go
pkg/v1/mutate/index_test.go
pkg/v1/mutate/mutate_test.go

I tried to construct a manifest list from a set of images, but GCR
rejected it because it validated the media type differently than we
expected.
Also use partial.Descriptor because we may want to pass through info.

Tweak some index mutation logic

---

cmd/crane/cmd/auth.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_auth.md
cmd/crane/doc/crane_auth_get.md
cmd/crane/doc/crane_auth_login.md
go.mod
go.sum
pkg/authn/keychain.go
pkg/authn/keychain_test.go

Fixes #664 
Expose the rather complicated logic for resolving a config file to
credentials as "crane auth get" via the credential helper API.
Also expose a simple "crane auth login" command to make populating the
config file with basic auth simpler.

Add "crane auth" command

---

pkg/v1/daemon/image.go
pkg/v1/daemon/image_test.go
pkg/v1/daemon/options.go

Fixes #139
Rather than wrapping the docker client options (as proposed in #139),
this just allows you to pass in an entire client implementation. This
makes testing a nicer, since we can pass in a MockImageSaver, and
callers can configure the client however they'd like without us having
to keep up with the docker client dependency.
By default, we'll still use the same options (client.FromEnv) to reach
the daemon (for compatibility).

Add WithClient to daemon.Image

---

pkg/legacy/tarball/write.go
pkg/v1/partial/with.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go
pkg/v1/remote/image_test.go
pkg/v1/remote/index.go
pkg/v1/remote/layer_test.go
pkg/v1/remote/mount.go
pkg/v1/remote/write_test.go
pkg/v1/tarball/write.go

Fixes #683 
If we resolve an index to an image, we can potentially lose a lot of
information, e.g. annotations or anything in the platform that's not in
the config, which only has os/arch.
If we return a layer from an image, we can look up the original
descriptor from that image to return as well, which might include
annotations or urls. Previously, the Mountable wrapping made this not
work.

Preserve Descriptor in remote where possible

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Fixes https://github.com/google/go-containerregistry/issues/689
The defaulting logic is being deferred to accessors, which means
comparing the structs of a repo or registry will result in non-equal
references even if they're semantically equivalent. This converts them
to strings to fix that.

Compare mount targets by string

---

cmd/crane/README.md

The command to login should be `crane auth login`.

Fix GitLab CI example

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go

I would like to pass the Bearer Token generated elsewhere directly. This is because I am developing plugins of some container registries such as Harbor and Quay. These plugins receive Bearer Token directly instead of username/password and need to use it for the authentication with the registries.
```
token := "eyJhbGciOiJSUzI1NiI..." //  passed by a container registry
img, err := remote.Image(ref, remote.WithAuth(&authn.Bearer{Token: token}))
if err != nil {
return err
}
...
```

Pass RegistryToken directly

---

pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

These fields should be considered in canonical image. Upstream of a kaniko PR (tbd)

Canonical should keep OS/ARCH

---

pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

Resolves the issue raised in [this comment](https://github.com/google/go-containerregistry/pull/685#issuecomment-612885360) by @ImJasonH . 
When creating a v1/tarball manifest of multiple images, _always_ provide the order in order of the repo tags. It doesn't matter to the tarball, but it allows for us to have consistent results. It ensures tests pass, but consistency is good overall.
The sort key is just the repo tags joined together by `","`. It is simple, but it does work. I considered using the hash of the specific manifest, but that would make it too hard to eyeball. Why use complexity unnecessarily?

Consistent ordering when processing images to create a tarball manifest

---

pkg/v1/google/auth_test.go
pkg/v1/google/keychain.go

Make detection of gcr.io and pkg.dev domains stricter to avoid matching similar prefixes.  It's important that google creds aren't sent to domains other than those controlled by Google.

Make detection of gcr.io and pkg.dev domains stricter

---

pkg/crane/pull.go
pkg/v1/progress.go
pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

Initial implementation of download progress, per [the discussion here](https://github.com/google/go-containerregistry/issues/670#issuecomment-584952872) with @jonjohnsonjr .
This only does it for `v1.tarball`; it still will need to be added to `legacy.tarball` and `v1.layout`. I also have given it zero testing. The goal is to have a basis for discussion.
I chose to change the calls to `Write/MultiWrite/MultiWriteRef` rather than entirely new funcs because:
* it would create an over-proliferation of functions and be very messy
* you always can pass in `nil` to a channel arg if you don't want it (which is what I did for almost all consumers
* with go modules, versioning of consumers is easy, so breaking changes on a new commit is not a big deal.

add download progress option for v1.tarball

---

pkg/v1/cache/fs.go
pkg/v1/cache/fs_test.go

This fixes an issue when the cache has to handle with interrupted downloads of previous executions.
It solves #717

pkg/v1/cache/fs.go delete cached layer on UnexpectedEOF

---

.github/workflows/release.yml

The latter exists by default and doesn't require us to create a new
secret for RELEASE_TOKEN.

Rename RELEASE_TOKEN to GITHUB_TOKEN

---

pkg/v1/mutate/image.go
pkg/v1/mutate/rebase.go
pkg/v1/mutate/rebase_test.go
pkg/v1/random/image.go

Manifest v2 specs do not include layer entries for empty layers,
but the history in the config will include an entry for empty
layers (e.g. produced by `ENV` directive). History entries for
empty layers include `empty_layer` field set to `true`.
As a result, when rebasing and copying from the new base and
original to the rebased image, it's not sufficient to simply
iterate layers and pull from the same position/index in the
history from config. Instead, history should be iterated and
used to generate `Addendum`, while simultaneously iterating
layers, but only including the layer (and advancing the iterator)
if it's for a history item for a non-empty layer.
Since the history in config is optional per the [OCI spec][1],
iteration via layers will still happen in the event that not
all layers …

Handle rebasing images with empty layers properly

---

pkg/v1/daemon/image.go
pkg/v1/daemon/image_test.go

Fixes https://github.com/google/go-containerregistry/issues/734

daemon: Ensure we call NegotiateAPIVersion first

---

pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go

Fixes https://github.com/google/go-containerregistry/issues/737

transport: preserve unexpected json errors

---

pkg/legacy/tarball/write.go

The order of the containers in the manifest is in-determinant but does not matter. This causes builds via tools like [`rules_docker`](https://github.com/bazelbuild/rules_docker) to create non-deterministic files.

[Fix] force a specific order in manifest for hermetic builds

---

pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go

What it says on the tin
I made a test go program [here](https://gist.github.com/jchorl/24aa7797524fbb0b1b59d1d3877cb751) to force 429s. The output was:
```
...
I0803 03:21:58.695399    1477 main.go:44] body: {"errors":[{"code":"TOOMANYREQUESTS","message":"Rate exceeded"}]}
I0803 03:21:58.695412    1477 main.go:45] temporary: false
...
```
Quite obviously, go-containerregistry is not treating `TOOMANYREQUESTS` as temporary even though it is, in fact, a temporary error. This is preventing retries [here](https://github.com/google/go-containerregistry/blob/38ad4ec12b1d707307f901c6675d99e738f4d7e3/pkg/v1/remote/write.go#L377) because the error _does_ implement the `temporary` interface ([here](https://github.com/google/go-containerregistry/blob/38ad4ec12b1d707307f901c6675d99e738f4d7e3/pkg/inter …

Retry on TOOMANYREQUESTS error from ECR

---

go.mod
go.sum
pkg/v1/mutate/rebase.go
pkg/v1/mutate/rebase_test.go

Fixes [#751] for missing `os`, `architecture` and `os.version` properties after `mutate.Rebase`
* `os`, `architecture` properties are required by config spec [[1]]
* `os.version` is unspec'd but required for Windows images to run on Windows containers [[2]]
This implementation takes these three properties from newBase, which most accurately defines the newly rebased image's os/architecture. If the properties were taken from original, it would prevent reuse of de-facto ABI-compatible top layers with differing old and new base images (i.e. data-only top layers rebased from amd64 to arm, Windows os.version upgrades). 
This does not address additional, optional config properties that are currently being omitted during rebase such as `author` and `created`, which I feel could be addressed in a …

Fix for rebase omitting os/arch config properties

---

pkg/v1/remote/transport/bearer.go

Fixes https://github.com/google/go-containerregistry/issues/757

Don't overwrite query in realm for token exchange

---

.travis.yml

I noticed that go 1.12 with GO111MODULE=on takes over 20 minutes to run. Let's drop it in favor of 1.14, given that even 1.15 has been released already.

Test go 1.14, not 1.12

---

pkg/name/tag.go

A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of **128 characters**.

Fix incorrect tag size limit

---

go.mod
go.sum
pkg/v1/remote/write.go
vendor/modules.txt

"The request Body, if non-nil, will be closed by the underlying
Transport, even on errors."
https://golang.org/pkg/net/http/#Client.Do
Fixes #707

[remote] Don't close streaming layers ourselves

---

go.mod
go.sum
pkg/v1/remote/descriptor.go
pkg/v1/remote/descriptor_test.go
vendor/golang.org/x/tools/go/packages/golist.go
vendor/golang.org/x/tools/go/packages/golist_overlay.go
vendor/modules.txt

fixes #769 
Lend me your nitpicks! There's a bit of copypasta here but I didn't want to over-aggressively DRY things up.

add remote.Head

---

cmd/crane/cmd/auth.go
pkg/gcrane/copy_test.go
pkg/v1/tarball/README.md

Produced via:
```shell
export FILES=( $(find . -type f -not -path './vendor/*' -not -path './third_party/*' -not -path './.git/*') )
misspell -w "${FILES[@]}"
```
/cc @jonjohnsonjr @ImJasonH
/assign @jonjohnsonjr @ImJasonH

[Automated] Fix misspellings

---

pkg/v1/google/list.go
pkg/v1/google/options.go

Added `WithContext` function, which implements `google.ListerOption`. This enables us to pass `context.Context` so that we could cancel sending HTTP requests. This PR won't change the default behavior since [`(*http.Client).Get`](https://golang.org/src/net/http/client.go?s=16191:16251#L460) wraps [`http.NewRequest`](https://golang.org/src/net/http/request.go?s=27051:27120#L802) and [`(*http.Client).Do`](https://golang.org/src/net/http/client.go?s=20422:20474#L575) and `http.NewRequest` wraps [`http.NewRequestWithContext`](https://golang.org/src/net/http/request.go?s=28365:28466#L828) with `context.Background`.

Add WithContext to google.ListerOption

---

pkg/crane/digest.go
pkg/crane/get.go

```
$ crane digest ubuntu
sha256:bc2f7250f69267c9c6b66d7b6a81a54d3878bb85f1ebb5f951c896d13e6ba537
```
```
$ go  run  ./cmd/crane/ digest ubuntu
sha256:bc2f7250f69267c9c6b66d7b6a81a54d3878bb85f1ebb5f951c896d13e6ba537
```
This wouldn't count as a "pull" from Dockerhub, which might be helpful in some cases.

Implement `crane digest` using a HEAD request

---

hack/update-codegen.sh
pkg/v1/progress.go

Updates hack/update-codegen.sh to use the pinned code-generator version
to avoid always pulling in the latest release with go get.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Added deepcopy-gen directive to avoid generating DeepCopy methods for
Update type, which fails generation due to embedded error interface not
supporting DeepCopy methods
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Fixes #782

Use pinned k8s.io/code-generator for codegen

---

pkg/crane/copy.go
pkg/crane/digest.go
pkg/crane/manifest.go
pkg/crane/options.go

Add platform option to crane copy and digest. If the remote reference is an index/list it only copies the image which matches the specified platform.
This would be a possible solution for #741

Add platform option to crane copy and digest

---

pkg/crane/options.go

Produced via:
```shell
export FILES=( $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print) )
goimports -w "${FILES[@]}"
gofmt -s -w  "${FILES[@]}"
```
/cc @jonjohnsonjr @ImJasonH
/assign @jonjohnsonjr @ImJasonH

[Automated] Format Go code

---

cmd/crane/cmd/root.go
cmd/crane/cmd/util.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_append.md
cmd/crane/doc/crane_auth.md
cmd/crane/doc/crane_auth_get.md
cmd/crane/doc/crane_auth_login.md
cmd/crane/doc/crane_blob.md
cmd/crane/doc/crane_catalog.md
cmd/crane/doc/crane_config.md
cmd/crane/doc/crane_copy.md
cmd/crane/doc/crane_delete.md
cmd/crane/doc/crane_digest.md
cmd/crane/doc/crane_export.md
cmd/crane/doc/crane_ls.md
cmd/crane/doc/crane_manifest.md
cmd/crane/doc/crane_pull.md
cmd/crane/doc/crane_push.md
cmd/crane/doc/crane_rebase.md
cmd/crane/doc/crane_tag.md
cmd/crane/doc/crane_validate.md
cmd/crane/doc/crane_version.md
pkg/crane/options.go
pkg/v1/remote/index.go

Adds a `--platform` option for the crane CLI tool.
I added a if-statement in `pkg/crane/options.go` that we don't get a nil pointer dereference if WithPlatform is called with nil. We could also catch this in cmd/crane/cmd/root.go` but I think it would in general make sense to avoid the nil pointer dereference.
I changed the error output in `pkg/v1/remote/index.go` to the form `os/arch`. This is not necessary but i think we should use the same form in the error output and the flag. I think this is quite arbitrary but I prefer os/arch over arch/os.

Add --platform CLI option for crane

---

pkg/v1/google/auth.go
pkg/v1/google/auth_test.go

Before, we were taking advantage of the fact that GCR will allow you to
just send an access token as bearer auth, but apparently this breaks
`gcrane cp` if it's your first push to a registry, so this change
returns basic auth to force us to always do a token exchange.

Return basic auth from google.Keychain

---

.github/workflows/knative-go-test.yaml
pkg/gcrane/copy_test.go

By having pkg/crane/copy_test.go set up its fake registry at `gcr.io`, this seems to trigger behavior that ends up looking for  default GCP credentials to authorize pushes/pulls. This works fine when tests run in GCB, and presumably on most of our local workstations, where GCP creds happen to be available, but [fails on GitHub Actions](https://github.com/google/go-containerregistry/pull/792#issuecomment-714163492), where creds are not available.
Instead of calling our fake registry "gcr.io", this change renames it to "xcr.io".
This change includes the Unit Tests action being added by #792, to check that this change fixes the unit test failure.

Remove hidden unit test dependency on GCR creds

---

.github/workflows/knative-verify.yaml
hack/update-codegen.sh
pkg/v1/doc.go
pkg/v1/image.go
pkg/v1/index.go

Also include `knative-verify.yaml` to make sure this passes @mattmoor's automated GitHub Actions.
Hopefully fixes the last of errors blocking https://github.com/google/go-containerregistry/pull/792 🤞

Update codegen step to use vendored codegen tools

---

.goreleaser.yml
.travis.yml
cmd/registry/test.sh
pkg/v1/cache/fs.go
pkg/v1/cache/fs_test.go
pkg/v1/layout/image_test.go
pkg/v1/mutate/mutate.go
pkg/v1/tarball/image.go
pkg/v1/tarball/layer.go
pkg/v1/validate/layer.go

Fixes #778 
With these changes, all tests pass running on a Windows system with Docker in Linux container mode.
One test file cannot run if Docker is in Windows container mode because crane can only pull Linux containers.
I'm not normally a Go developer, so let me know if I need to make any changes to how I've done anything here.
Please take a hard look at the "unclosed ReadClosers" fix, as that one is the most involved and has the most potential for me to have done something incorrectly.

Add Windows support - Fix tests, enable CI, and release Windows binaries

---

README.md

This won't report a status until https://github.com/google/go-containerregistry/pull/792 adds the action for the master branch.
cc @mattmoor

Add GitHub Actions badge for build status

---

pkg/crane/push.go
pkg/registry/manifest.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/multi_write_test.go

This method takes multiple images or manifest lists, and attempts to
efficiently upload all of them in parallel, deduplicating shared layer
and config blobs and avoiding unnecessary auth token exchanges.
Blobs are uploaded in parallel first, then manifests are tagged in order
with as much parallelism as we can support.
This method is currently limited in that:
- all images must be getting uploaded to the same repository (to
simplify auth and transports), and
- no image may contain streaming layers (to simplify digests), but both
of these can be removed in future changes.
- blobs are uploaded and manifests are tagged in parallel with a
constant max parallelism, which should be a user-controlled option.

Add remote.MultiWrite

---

pkg/v1/remote/descriptor.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/options.go
pkg/v1/remote/write.go

- default parallel is 4
- an error is returned if WithParallel is called with a value <=0 or >100
We can probably reuse this to fetch and push blobs elsewhere in remote.
MultiWrite'ing 123 distroless images with `WithParallel(100)` took 4s compared to 11s for the default.

Add remote.WithJobs and use it in remote.MultiWrite

---

pkg/v1/tarball/write.go

Manifest is marshalled repeatedly.

Fix error when calculating tarball size of manifest

---

pkg/v1/google/auth.go
pkg/v1/google/auth_test.go

Add a NewTokenSourceAuthenticator function that converts an
oauth2.TokenSource into an authn.Authenticator, for convenience.
Make NewEnvAuthenticator actually pull down a token to make sure we
actually found valid credentials, for use in google.Keychain.
Remove some unit tests that relied on us not doing that.
Fixes https://github.com/google/go-containerregistry/issues/806

Fix some weirdness in google.Keychain

---

cloudbuild.yaml

- consolidate golang steps into a single step for readability
- symlink /workspace into $GOPATH
- install ko from release, instead of from head

Rewrite cloudbuild.yaml and publish with --platform=all

---

cloudbuild.yaml

Fixes https://github.com/google/go-containerregistry/issues/810

Fix debug images

---

pkg/v1/layout/write.go

expose v1/layout.WriteImage and WriteIndex

---

pkg/v1/remote/multi_write.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Right now we are just passing through cherrypicked options from
WriteIndex to other WriteIndex and Write calls. This isn't sustainable
as we add more options, since we'd have to keep these in sync.
Instead, for WriteIndex, we can reuse the writer by pulling the
implementation out into writer.writeIndex.
For Write, since we do scope calculation based on layers, we can't reuse
the writer because we don't do scope calculation for WriteIndex.

Make sure options are propagated to child Writes

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go
pkg/internal/redact/redact.go
pkg/v1/google/auth.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go
pkg/v1/remote/layer.go
pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/logger.go
pkg/v1/remote/transport/logger_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

1. Drop places that can log creds. May bring this back with build tags?
2. Introduce pkg/internal/redact to hold a context that signals we
should omit the body when dumping logs. Maybe this should live in
the logs package, but internal for now should be fine.
3. Stop logging the request and response body for blobs and token
responses.

Revamp debug logs

---

pkg/v1/remote/transport/ping.go

I see that registry ping does not have timeout handling. The makeFetcher function clearly has a ctx timeout handling. Why is it not set during ping? I currently set the easiest 3 second timeout.

add：registry ping timeout

---

pkg/v1/remote/descriptor.go
pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go
pkg/v1/remote/transport/logger.go

Fixes https://github.com/google/go-containerregistry/issues/825
Return "unexpected status code" instead of "unsupported".
Instead of just printing the status code, include the http.StatusText.
While debugging this, I encountered more MISSING stuff in the debug logs
for URLs. Fix that.
Document that `remote.Head` errors can be retried with `remote.Get` to get more details.

Improve transport.Error text

---

pkg/name/options.go
pkg/name/ref_test.go
pkg/name/registry.go
pkg/name/registry_test.go
pkg/name/tag.go
pkg/name/tag_test.go

Adds default registry and default tag options to `pkg/name` such that a user may configure their own defaults. Also move defaulting logic to tag / registry construction rather than methods called on the objects. See individual commits for how this maintains compatibility with existing behavior.
/cc @jonjohnsonjr @ImJasonH 
Fixes #805

Add ability to override default registry and tag in pkg/name

---

go.mod
pkg/v1/match/match.go
pkg/v1/match/match_test.go
pkg/v1/platform.go
pkg/v1/platform_test.go

Starts to address #821 
* creates a `ManifestMatcher` and utilities that can be used to find manifests that match the provided matcher
* provides convenience matcher utilities to match by annotation, media-types, name (specific annotation), platform
* provides a `FindManifests` that takes a `v1.ImageIndex` and returns the manifests in it that match. This is useful in its own right, but will be even more useful later for tree walking.
Some questions and follow-ons:
* is this the right location for it? `partial` was suggested but seems, well, off. This _is_ a utilities package, but mostly seems to have internal utils, although it still works better than `partial`. I think this could handle being renamed to `util` since `v1/v1util` is a mouthful.
* while this is really simple, it doesn't …

match package with matcher and utils to filter v1.Descriptors; v1.Platform.Equals utility

---

pkg/v1/mutate/mutate_test.go
pkg/v1/random/image.go

`go vet` regularly complains about these two unkeyed fields. It doesn't really affect anything, but might as well have good hygiene.

fix vet complaint

---

pkg/v1/remote/transport/ping.go

Mitigate https://github.com/google/go-containerregistry/issues/832
Will send real fix in a follow-up.

Set longer timeout for ping

---

pkg/internal/legacy/copy.go
pkg/v1/google/list.go
pkg/v1/remote/catalog.go
pkg/v1/remote/delete.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/list.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go
pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/write.go

Fixes https://github.com/google/go-containerregistry/issues/832
Add transport.NewWithContext.
Use the provided context for the initial ping request and token
exchange.
Subsequent token exchanges (to refresh) will use the context of the
incoming request in RoundTrip.
Drop the hardcoded ping timeout.
Use transport.NewWithContext everywhere that's easily plumbable.

Plumb contexts through transport.New

---

pkg/v1/partial/index.go
pkg/v1/partial/index_test.go
pkg/v1/types/types.go
pkg/v1/types/types_test.go

Add FindManifests utility, that allows one to pass a `v1.ImageIndex` and a `match.Matcher`, and get back the `v1.Descriptor` entries in the index that match.
This is a spin-out from #823 and will include the salient original comments below.
We expect to have several more such utilities that build on `Matcher` in this PR and/or others before it is done.

add FindManifests

---

go.mod
pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/bearer_test.go
pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go
vendor/github.com/docker/distribution/registry/client/auth/challenge/addr.go
vendor/github.com/docker/distribution/registry/client/auth/challenge/authchallenge.go
vendor/modules.txt

This allows us to recover from insufficient scope errors.
This PR introduces a dependency on `github.com/docker/distribution/registry/client/auth/challenge`. We already had an indirect dependency on it through the daemon package, so maybe not a huge deal?

Parse WWW-Authenticate challenges on retry

---

.goreleaser.yml
.travis.yml
pkg/v1/google/auth_test.go
pkg/v1/remote/multi_write_test.go

Fixes https://github.com/google/go-containerregistry/issues/850

Add support for arm and arm64

---

cmd/crane/cmd/root.go
cmd/crane/cmd/version.go
pkg/crane/options.go
pkg/v1/remote/options.go
pkg/v1/remote/transport/basic.go
pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/transport/transport_test.go
pkg/v1/remote/transport/useragent.go

Fixes https://github.com/google/go-containerregistry/issues/830

Implement better user agent support

---

.goreleaser.yml
pkg/v1/remote/transport/useragent.go

For most things consuming this package, they will depend on an actual
released version of go-containerregistry. When we release
go-containerregistry itself, the binaries are built at the same version
as the library, which means that they don't depend on an actual released
version of go-containerregistry, so the version in debug info is just
"(devel)". For our own release, we will just set it to the tag.
<hr>
Tested via:
```
$ goreleaser --snapshot --skip-publish --rm-dist && ./dist/crane_linux_amd64/crane ls -v ubuntu 2>&1 | grep -i agent
User-Agent: crane/v0.2.1-next go-containerregistry/v0.2.1-next
User-Agent: crane/v0.2.1-next go-containerregistry/v0.2.1-next
User-Agent: crane/v0.2.1-next go-containerregistry/v0.2.1-next
```
Before:
```
$ goreleaser --snapshot --skip-publish --rm-dist …
```

Set transport.Version via ldflags for release

---

pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go

Currently, we just return the last one, which is very misleading if
you're using self-signed certs for a domain that allows http fallback
(e.g. localhost).
Fixes https://github.com/google/go-containerregistry/issues/738

Return both https and http errors on ping fallback

---

pkg/v1/remote/write.go

Fixes https://github.com/google/go-containerregistry/issues/862
Also, refactor unpackTaggable a bit to ensure we only call RawManifest once.

Expand godoc for remote.Tag

---

pkg/v1/remote/transport/logger.go

This is currently always set, but we should only set it if there are
actually credentials being redacted, so that we can tell if the header
was set or not.
Noticed this in https://github.com/google/go-containerregistry/issues/861

Fix misleading Authorization: <redacted>

---

pkg/v1/match/match.go
pkg/v1/match/match_test.go

Option to:
* `match.Platforms([]v1.Platform)` for any one of them.
* `match.Digest(v1.Hash)`
* `match.Digests([]v1.Hash)` for any one of them.
Also tests, of course.

match.Platforms and match.Digests

---

pkg/crane/append.go
pkg/crane/push.go
pkg/v1/stream/layer.go

Fixes #707 as well
It's annoying that `crane append` is hard to use with one-liners, which
is the secret goal of most crane commands. We now stat the layer files
and use a streaming layer for anything that's not a regular file, which
includes named pipes, which fail if we try to open them multiple times.
Now you can do this:
```
$ crane append -f <(tar -c some-dir/ -f -) -t $IMAGE
```

Fix `crane append` for named pipes

---

pkg/v1/tarball/layer.go
pkg/v1/tarball/layer_test.go
pkg/v1/v1util/zip.go

Today `tarball.LayerFromOpener` must either compress or decompress its input based on which it receives.
Virtually all clients of this interface have an uncompressed tarball they want to turn into a layer, but the API we have presents two fun problems.
1. If we simply present the uncompressed tarball (as most clients do) then we will often end up compressing the layer (expensive!) twice.  The first time is to compute the layer's digest, and the second is typically to publish the layer as part of `remote.Write`.
2. If we present a precompressed tarball (as ko does), then we will have an extra decompression (less expensive, but still redundant) to compute the diff id.
This refactors the layer to store an opener for each form of the layer.  The constructor sniffs whether the layer is …

Refactor to support caching compression.

---

cmd/gcrane/cmd/gc.go
cmd/gcrane/cmd/list.go

https://github.com/google/go-containerregistry/pull/845 introduces `gcrane.Keychain`.
This PR uses `gcrane.Keychain` for not only crane-inherit commands(ex. pull) but also gcrane-specific commands(gc/ls).

Use gcrane.Keychain for not only crane-inherit commands but also gcrane-specific commands.

---

pkg/v1/layout/write.go
pkg/v1/layout/write_test.go
pkg/v1/mutate/index.go
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

Fixes #842 
adds the following to `v1/layout`:
* `RemoveDescriptors(matcher match.Matcher)` - removes from `index.json` any descriptors that match 
* `ReplaceDescriptor(desc v1.Descriptor, matcher match.Matcher)` - equivalent of `RemoveDescriptors(matcher)` followed by `AppendDescriptor(desc)`
* `ReplaceImage(image v1.Image, matcher match.Matcher)` - equivalent of `RemoveDescriptors(matcher)` followed by `AppendImage(image)`
* `ReplaceIndex(index v1.ImageIndex, matcher match.Matcher)` - equivalent of `RemoveDescriptors(matcher)` followed by `AppendIndex(index)`
None of these does garbage collection in the blobs dir, which is a completely separate topic, and should be handled under separate cover.

add to layout replacedescriptor and removedescriptor

---

cmd/crane/cmd/auth.go
cmd/crane/cmd/root.go
cmd/gcrane/main.go

NewCmdAuthLogin now requires you to pass in your usage string, so that it is
no longer hard-coded to "crane auth".
Also log the config file that we used.

Fix some login issues

---

pkg/v1/google/options.go
pkg/v1/remote/options.go

This should be slightly less confusing the first time you see it, we can look at removing this entirely by skipping ping and only falling back on 401, but that might take a while to implement.

Include target resource in credential warning

---

cmd/crane/cmd/optimize.go
cmd/crane/cmd/root.go
pkg/crane/optimize.go
pkg/v1/tarball/layer.go
pkg/v1/tarball/layer_test.go

This is a hidden command, which roundtrips a remote image to a target image through `tarball.LayerFromOpener(layer.Uncompressed)`.
Right now this does nothing to force estargz (still need `GGCR_EXPERIMENT_ESTARGZ=1`) or prioritize files (need `estargz.WithPrioritizedFiles(foo)`), but want to start the convo.
Fixes: https://github.com/google/go-containerregistry/issues/878

Start to flesh out crane optimize.

---

pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

This PR just adds some validation to ensure we're not producing invalid manifests. `null` might be a valid digest but I can't imagine any user intentionally producing an image with a `null` manifest (Docker can't import that or do anything useful with it).
I found a weird quirk in [kaniko](https://github.com/GoogleContainerTools/kaniko) where they were passing no refs into `WriteToFile`. Unfortunately, this produced a `nil` manifest, which json-encoded to `null` (valid json!), so I ended up with a tarball with only a `manifest.json` with the contents `null`.
Of course, ECR and Docker were happy to accept this tarball and just... silently do nothing with it.
I opened a [PR](https://github.com/moby/moby/pull/41842) to fix docker loads with a `null` manifest. I'll also open a PR to kaniko to …

fail computing manifest if no refs are provided

---

cmd/crane/cmd/auth.go

Before, this would just print the AuthConfig that we get back from the
config file read. This is often what we want, but it prevents crane from
acting as a credential helper itself.
By converting back to the credential helper structs, we can use crane as
a meta-credential-helper that can multiplex over anything in your config
file.

crane auth get: convert back to credentials

---

cmd/crane/cmd/optimize.go
pkg/crane/optimize.go
pkg/crane/optimize_test.go

Progress towards https://github.com/google/go-containerregistry/pull/902#issuecomment-756365992

Drop k8s.io/apimachinery/pkg/util/sets

---

pkg/crane/digest.go

This allows to use crane.Digest on images with a v1 schema.
Fixes #906

Fix crane digest for v1 and platform option

---

pkg/v1/google/auth_test.go

Workaround for https://github.com/google/go-containerregistry/issues/908

Temporarily disable gcloud tests for darwin

---

pkg/v1/google/list.go
pkg/v1/google/list_test.go

This json.Number thing was added when AR was returning the wrong thing,
now they are consistent, so we should be too.
This partially reverts https://github.com/google/go-containerregistry/pull/667 now that it's no longer needed.

Make gcrane ls --json output consistent

---

pkg/v1/tarball/write.go
pkg/v1/tarball/write_test.go

Fixes https://github.com/google/go-containerregistry/issues/890

Always include tag in tarball refs

---

pkg/authn/k8schain/README.md

The signature has changed since the original README was created.

doc: add context.Context to examples

---

pkg/crane/crane_test.go
pkg/registry/manifest.go
pkg/registry/registry_test.go

I was learning this repo to try to use in one personal thing and saw that some tests were pending to add.
This PR tries to implement the tests for `crane.Delete`, I'm not 100% if it is correct but it is a tryout 😄 
if sounds reasonable I will try to implement the other missing tests
/cc @jonjohnsonjr

implement delete manifest tests

---

cmd/crane/README.md

relates to #914
```
$ brew install crane
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/crane-0.4.0.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/cc13961cd45cac3656448c7a3598a9805911ee6e76f5552aa26b3a14c55f57ba?response
######################################################################## 100.0%
==> Pouring crane-0.4.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/crane/0.4.0: 5 files, 8.8MB
```

doc: add homebrew install

---

pkg/authn/authn.go

`cli/cli` points to github cli while AuthConfig refers to `docker/cli`

fix(authn): minor fix in reference link

---

pkg/v1/internal/gzip/zip.go
pkg/v1/stream/layer.go

Use a bufio.Writer to buffer gzipped output while we are reading from
the other end of an io.Pipe to allow gzip to keep compressing its input.
A 64K buffer was chosen for its humor value. The default size of
bufio.Writer was too small when testing against a local registry.
Increasing beyond 64K didn't seem to have any noticeable effect. It
might make sense to make this smaller, but I don't see a reason to worry
about it ATM.
Fixes https://github.com/google/go-containerregistry/issues/920
In local testing, this improved write speed from ~8MB/s to ~30MB/s. Against an actual registry (Docker Hub or GCR), this seems to improve things by ~30%.

Buffer the output of gzip.Writer to avoid stalling

---

.gitattributes

[I recommended this in a code review in September 2019](https://github.com/google/go-containerregistry/pull/462#discussion_r328430853). What a fool I was then.

Don't consider go.mod as generated, because it's not

---

pkg/v1/remote/multi_write.go
pkg/v1/remote/multi_write_test.go
pkg/v1/remote/options.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Support non-distributable layers in Write and MultiWrite

---

pkg/v1/layout/write.go
pkg/v1/layout/write_test.go

We already can WriteBlob, so we should be able to RemoveBlob.

Delete layout blob

---

pkg/crane/crane_test.go
pkg/registry/manifest.go
pkg/registry/registry.go
pkg/registry/registry_test.go

as a continuation of in intention of the work here: https://github.com/google/go-containerregistry/pull/915
This PR implements the `ListTags` tests
All feedback are welcome
/assign @jonjohnsonjr

implement listTags tests

---

pkg/crane/crane_test.go

Was working without internet and noticed this took a long time.

Prevent test from hitting Docker Hub

---

pkg/v1/cache/cache.go
pkg/v1/cache/cache_test.go

cache: lazily pull contents to populate cache

---

pkg/v1/layout/options.go
pkg/v1/layout/write.go

If we want to add anything other than descriptor mutators as options, we
need a place to do that, so this introduces an options struct that holds
options and thunk-ifies the existing descriptor mutators.

Thunk-ify layout options

---

pkg/v1/remote/write.go

Holdover TODO from #803 that I noticed while working on progress updates

Support WithJobs in remote.Write

---

pkg/name/ref.go
pkg/name/ref_test.go

Makes testing and initializing other `const`ish References less annoying

Add MustParseReference

---

pkg/crane/crane_test.go
pkg/registry/manifest.go
pkg/registry/registry.go
pkg/registry/registry_test.go

as a continuation of in intention of the work here: https://github.com/google/go-containerregistry/pull/915
This PR implements the `Catalog` tests
Feedbacks are welcome
/assign @jonjohnsonjr

implement catalog tests

---

hack/presubmit.sh
pkg/name/internal/must_test.go
pkg/name/internal/must_test.sh
pkg/name/ref.go
pkg/name/ref_test.go

MustParseReference only accepts consts

---

pkg/v1/remote/multi_write.go

https://github.com/google/go-containerregistry/pull/958 added support for `WithJobs` to `remote.Write`, etc., and added context timeout/cancellation handling (correctly, we think) at the same time.
This change ports that context handling to `remote.MultiWrite` (correctly, we think). If it's not correct, it's at least consistently incorrect.

Use errgroup consistently in MultiWrite

---

pkg/gcrane/copy_test.go
pkg/v1/remote/check_e2e_test.go

In addition to these usages, `pkg/v1/remote` tests also have [`mustNewTag`](https://github.com/google/go-containerregistry/blob/bea57adbec389354c16a3db17a81759529dd8ff5/pkg/v1/remote/write_test.go#L49), which regularly takes a var string to be able to be derived from a dynamically-generated in-memory host.

Use name.MustParseReference in some tests

---

pkg/v1/remote/multi_write.go
pkg/v1/remote/multi_write_test.go
pkg/v1/remote/options.go
pkg/v1/remote/progress_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Fixes https://github.com/google/go-containerregistry/issues/952
Shoutout to @DennisDenuto who paired with me on this 🎉 
- supported in `remote.WriteLayer`, `remote.Write`, `remote.WriteIndex`, `remote.MultiWrite`
- given update chan is closed when write completes
- an error is sent along the chan if there are any non-temporary errors uploading
- if a layer already exists or is mounted, progress updates immediately to account for that
- if layer upload fails and is retried, progress goes backward and goes back up
https://github.com/google/go-containerregistry/commit/d7fe93870768a18d524d5379b5d97480ab7715b0 demonstrates how easy it is to consume this channel, by hacking in an upload progress bar for `crane cp` (not part of this PR)
Fixes #852 as well as a bonus ⏩

Support WithProgress for remote Writes

---

pkg/crane/digest.go
pkg/crane/digest_test.go
pkg/v1/hash.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/descriptor_test.go

```
$ crane digest registry.access.redhat.com/ubi8/ubi-minimal
2021/03/20 10:19:50 No matching credentials were found for "registry.access.redhat.com/ubi8/ubi-minimal", falling back on anonymous
2021/03/20 10:19:51 computing digest: too many parts in hash: 
```
_My, what a very unhelpful error message that is!_ 🤔 
```
$ go run ./cmd/crane digest registry.access.redhat.com/ubi8/ubi-minimal
2021/03/20 10:20:10 No matching credentials were found for "registry.access.redhat.com/ubi8/ubi-minimal", falling back on anonymous
2021/03/20 10:20:10 HEAD request failed, falling back on GET: response did not include Docker-Content-Digest header
2021/03/20 10:20:10 No matching credentials were found for "registry.access.redhat.com/ubi8/ubi-minimal", falling back on anonymous …
```

crane digest: fallback to GET when HEAD fails

---

pkg/v1/remote/write.go

As discussed with @jonjohnsonjr . We already have [remote.Tag](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote#Tag) which uploads a manifest and references it with a tag. However, there also is the ability in the API to upload a manifest and just reference it via its digest, just like any other blob. Eventually, the manifest should be referenced by another manifest or a tag, but those are independent.

Add remote.Digest() to upload a manifest via digest

---

cmd/crane/cmd/digest.go
cmd/crane/doc/crane_digest.md
pkg/crane/crane_test.go
pkg/crane/push.go

Fixes https://github.com/google/go-containerregistry/issues/895

Add --tarball to crane digest

---

cmd/gcrane/cmd/copy.go
cmd/gcrane/cmd/gc.go
cmd/gcrane/cmd/list.go
pkg/gcrane/copy.go
pkg/gcrane/options.go
pkg/v1/google/list.go
pkg/v1/google/options.go

This allows us to plumb a user-agent everywhere, and makes some things a
bit more consistent. This is getting unwieldy, but it works.
While working on https://github.com/google/go-containerregistry/pull/985 I noticed that we were dropping the useragent in a few places, which is upsetting. This should fix that.

Rework gcrane options

---

pkg/v1/google/list.go
pkg/v1/google/list_test.go

If we don't see the GCR-specific response, just continue paging
through results so we can return a reasonable answer for non-Google
registries.
Fixes https://github.com/google/go-containerregistry/issues/984
```
$ gcrane ls -v quay.io/prometheus/prometheus | wc -l
2021/04/19 17:34:51 No matching credentials were found for "quay.io", falling back on anonymous
2021/04/19 17:34:51 --> GET https://quay.io/v2/
2021/04/19 17:34:51 GET /v2/ HTTP/1.1
Host: quay.io
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
2021/04/19 17:34:51 <-- 401 https://quay.io/v2/ (352.624355ms)
2021/04/19 17:34:51 HTTP/2.0 401 Unauthorized
Content-Length: 4
Content-Type: text/html; charset=utf-8
Date: Tue, 20 Apr 2021 00:34:51 GMT
Docker-Distribution-Api-Version: registry/2.0
Server: nginx/1.12.1 …
```

Paginate responses for gcrane

---

pkg/v1/daemon/image.go
pkg/v1/daemon/image_test.go
pkg/v1/daemon/options.go
pkg/v1/daemon/write.go
pkg/v1/daemon/write_test.go

Fixes https://github.com/google/go-containerregistry/issues/857
Use options for everything, including injecting clients for testing.
Add WithContext option.
Un-thunkify some of daemon.Image to make it a bit clearer.
Add more test coverage: actually caught one bug where we were returning
the wrong error if we failed to read from the daemon response body.

Refactor pkg/v1/daemon

---

cmd/crane/cmd/append.go
cmd/crane/cmd/mutate.go
cmd/crane/cmd/root.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_mutate.md
cmd/crane/recipes.md
pkg/crane/pull.go
pkg/crane/push.go

Fixes https://github.com/google/go-containerregistry/issues/281
```
$ crane config $(go run ./cmd/crane mutate gcr.io/kontaindotme/mutated --entrypoint "blah blah blah" --label foo=bar) | jq .config
...
{
"Entrypoint": [
"blah",
"blah",
"blah"
],
"Env": [
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
],
"Labels": {
"bar": "baz",
"foo": "bar"
}
}
```
(`bar=baz` was previously set during testing)

Add crane mutate to set labels and entrypoint

---

cloudbuild.yaml
cmd/crane/README.md
cmd/gcrane/README.md

Fixes #755 
When the tag name is set, this will produce images like:
- `gcr.io/go-containerregistry/crane:vX.Y.Z`
- `gcr.io/go-containerregistry/crane:debug-vX.Y.Z`
When the tag name is not set (building an untagged commit), it will produce images as normal (e.g., `gcr.io/go-containerregistry/crane:abcdef` and `:latest`).
Also update the `ko` version used to build images, and fail if using an unset env var.

Tag crane/gcrane images with Git tag

---

pkg/v1/daemon/options.go
pkg/v1/daemon/write_test.go

We exposed ImageOption, so we need to keep that symbol alive.
Also fix some linter complaints.

Fix backward-incompat issues in daemon

---

pkg/v1/google/list.go

We were hitting this warning when listing an empty repository, which
doesn't make sense.

Don't warn about fallback unless we need to

---

pkg/v1/google/list.go
pkg/v1/google/list_test.go

Accidentally dropped top-level repo listing in gcrane for paginating
responses.

Fix gcrane top-level listing

---

internal/legacy/copy.go
internal/legacy/copy_test.go
pkg/crane/copy.go

The schema 1 copying code was very hacked together, but remote.Put
simplifies things a bit. This extends some of the crane/gcrane options
down through to legacy.CopySchema1.
Fixes https://github.com/google/go-containerregistry/issues/1006

Propagate remote options through schema 1 copies

---

.goreleaser.yml

This is shamelessly yanked from the default `name_template:` value: https://goreleaser.com/customization/archive/ (which it appears was adjusted here just to remove project version from the filenames).
I decided not to include the 32bit MIPS bit too because honestly, I'm not sure why folks would be doing 32bit MIPS.
(This should result in filenames like `go-containerregistry_Linux_armv6.tar.gz` instead of `go-containerregistry_Linux_arm.tar.gz`, since `goarm:` upstream defaults to `[6]`.)

Update goreleaser config to include arm version

---

cmd/crane/cmd/root.go
cmd/crane/cmd/validate.go
cmd/crane/main.go
cmd/gcrane/main.go

crane validate should exit with a non-zero status code if validation
fails.
We should not double-print error messages, because RunE does that for
us.
Disable usage message on errors, as that obfuscates the error. Invalid
commands still print usage.

Fix RunE error handling

---

cmd/crane/cmd/validate.go
cmd/crane/doc/crane_validate.md
pkg/v1/layout/image.go
pkg/v1/layout/image_test.go
pkg/v1/partial/README.md
pkg/v1/partial/compressed_test.go
pkg/v1/partial/uncompressed_test.go
pkg/v1/partial/with.go
pkg/v1/partial/with_test.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go
pkg/v1/remote/layer.go
pkg/v1/remote/layer_test.go
pkg/v1/remote/mount.go
pkg/v1/validate/image.go
pkg/v1/validate/index.go
pkg/v1/validate/layer.go
pkg/v1/validate/options.go

Fixes #838 
Add validate.Fast option
Add Exists to remote layers
Add Exists to layout
Add Exists to partial
Simplify some of our typechecking logic with unwrap().
Stop double-wrapping layoutImage layers.

Add --fast flag to crane validate

---

pkg/v1/google/auth.go

Previously, this was storing a single exec.Command, but that gets
consumed when it gets Run, failing with:
exec: already started
This will re-exec the gcloud when needed.

Re-exec gcloud token source when we refresh

---

internal/and/and_closer.go
internal/estargz/estargz.go
internal/gzip/zip.go
internal/verify/verify.go
pkg/v1/cache/cache.go

1. Typo
2. Missing package doc comment
3. Tautological conditional

Fix various lint issues

---

cmd/crane/README.md
cmd/gcrane/README.md

When running the specified command you get - 
```
$ go install github.com/google/go-containerregistry/cmd/crane                                                                                                                                                                  ✘ 127
go install: version is required when current directory is not in a module
Try 'go install github.com/google/go-containerregistry/cmd/crane@latest' to install the latest version
```

Fix install instructions for crane

---

cmd/crane/cmd/root.go
cmd/crane/main.go
cmd/gcrane/cmd/copy.go
cmd/gcrane/cmd/gc.go
cmd/gcrane/cmd/list.go
cmd/gcrane/main.go
internal/signal/go116.go
internal/signal/signal.go
pkg/crane/options.go
pkg/gcrane/options.go

Fixes https://github.com/google/go-containerregistry/issues/912
Also, use signal.NotifyContext for cancelling the ctx.
Also, don't log errors twice now that we're using RunE.

Plumb context through crane and gcrane

---

pkg/gcrane/options.go

This allows overriding the use of gcrane.Keychain

Add auth options to gcrane

---

README.md

This seems to be broken anyway, e.g. failing with OOM.

Remove report card

---

cmd/crane/cmd/copy.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_copy.md

Found about this little secret on [Knative Slack channel](https://knative.slack.com/archives/C93E33SN8/p1622662578076900) that `crane copy` retains the digest value when copying images
Very important to know for some uses cases around security and secure supply chain

update to add that crane retains the digest

---

pkg/v1/remote/multi_write_test.go
pkg/v1/remote/progress_test.go
pkg/v1/remote/write.go

- only retry on certain 'temporary' http status codes
- add tests to ensure retries do not occur on 'non-temp' http status
codes. And to make sure progress bar still works when retrying
Attempts to fix: https://github.com/google/go-containerregistry/issues/1038
Note:
Running `hack/presubmit.sh` resulted in the following:
```
~/workspace/go-containerregistry/pkg/authn/k8schain ~/workspace/go-containerregistry ~/workspace/go-containerregistry
go: github.com/google/go-containerregistry@v0.5.2-0.20210601193515-0ffa4a5c8691 requires
cloud.google.com/go@v0.83.0: missing go.sum entry; to add it:
go mod download cloud.google.com/go
~/workspace/go-containerregistry ~/workspace/go-containerregistry
```
This seems to me unrelated to the change in the PR... tried to go mod download …

Add retry when commiting a manifest

---

pkg/v1/tarball/image.go

Fixes https://github.com/google/go-containerregistry/issues/1032

load manifest form tar file

---

pkg/v1/tarball/image.go

Reverts google/go-containerregistry#1033  It`s my mistake It doesn't work like we expected，I will create a new  pr soon

Revert "load manifest form tar file"

---

internal/verify/verify.go
internal/verify/verify_test.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go

This prevents cases where a descriptor says it describes a 100-byte blob, but then serves 1TB blob, which could lead to resource exhaustion. Instead, we'll only read as many bytes as the descriptor claims there should be, and fail if the digest doesn't match after reading that many. This also verifies the content isn't shorter than described.
This adds a HEAD request to `remote.Layer` to fetch the size of the blob before reading and verifying it. If that's not acceptable we could work around it.

Verify size in verify.ReadCloser

---

pkg/name/registry.go
pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go

Imporve the fallback logic in `ping`. Not try `https` if the registry is intentionally set to insecure so that we can avoid long delays on http-only registry (which may directly drop the packet to port 443 rather than answer with a RST).
Fixes https://github.com/GoogleContainerTools/kaniko/issues/970
It still keep https://github.com/google/go-containerregistry/issues/279 solved.

Avoid trying https for insecure registries

---

pkg/gcrane/options.go
pkg/gcrane/options_test.go

Also add some silly tests for coverage.

Add WithTransport to gcrane

---

pkg/name/registry.go
pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go

This reverts commit 9e56ddd8e43fa8030579d2588c763ae2c4e34604.
See https://github.com/google/go-containerregistry/issues/1047
cc @pangsq

Revert "Avoid trying https for insecure registries (#1002)"

---

.github/workflows/build.yaml
.github/workflows/test.yaml

Follow up on the comment: https://github.com/google/go-containerregistry/pull/943#issuecomment-824153837
we keep the go mod pinned to 1.14 but maybe we can test with 1.14/1.15/1.16 to make sure both three is green
/assign @jonjohnsonjr

ci: test/build with go 1.14/1.15/1.16

---

cmd/crane/cmd/root.go

when using the `--insecure` flag ignore the TLS validation.
Please let me know if this is ok or what are your thoughts
/assign @jonjohnsonjr 
Fixes: https://github.com/google/go-containerregistry/issues/1024

crane: ignore TLS certificate validation when using --insecure flag

---

pkg/crane/digest.go
pkg/crane/get.go

This returns a v1.Descriptor, so it's possible to detect the media type,
digest, and size of a remote artifact.

Implement crane.Head

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md
pkg/v1/mutate/image.go
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Hello, this PR will add overriding manifest annotations support to crane's `mutate` command, it will work like the following picture:

added support for overriding manifest annotations

---

pkg/authn/k8schain/k8schain.go
pkg/authn/k8schain/k8schain_test.go

The k8schain package creates a new keychain by resolving Kubernets
secrets from service accounts and other image pull secrets specified by
name. The k8s client gets the full secret content for these named
resources.
Sometimes it's desirable to pull the content of a secret from a cache,
or to watch a resource for changes in a controller. In this situation
it would be helpful to create a k8schain directly from resolved secrets,
without making calls to the k8s api server.
This change refactors the existing k8schain.New() method to separate the
resolution of secrets from the creation of the keychain. This is only a
refactoring of existing behavior to shortcut the k8s api lookups. There
is no change in existing behavior for the keychain.
Added:
k8schain.NewFromPullSecrets(context.Context, …

Create a k8schain directly from pull secrets

---

.goreleaser.yml

Document released images in release notes

---

cmd/crane/cmd/root.go

Missed this in review. We clobber the HTTPHeaders immediately after by
having two WithTransport options.

Don't overwrite WithTransport option

---

pkg/v1/remote/progress_test.go

```
$ go test -race ./pkg/v1/remote -run=TestMultiWrite_Progress_Retry -count=10
ok  	github.com/google/go-containerregistry/pkg/v1/remote	60.598s
```

Avoid race in progress_test.go

---

pkg/v1/remote/write.go

Some registries expect this.
Fixes https://github.com/google/go-containerregistry/issues/1018

Set Content-Type to application/octet-stream

---

internal/verify/verify.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go
pkg/v1/remote/layer.go

Sometimes Content-Length isn't set, and sometimes we don't know what it
should be. Do our best regardless.
Fixes https://github.com/google/go-containerregistry/issues/1061

Only verify size if we can

---

pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go

It might happen there are multiple `www-authenticate` headers returned from a registry, e.g. `Negotiate` and `Basic`. In the current code, in such situation the first challenge would be picked with no further checks, which would result eventually in `unrecognized challenge` error failing the whole build, even though `Basic` challenge could be used instead. `pickFromMultipleChallenges` function was added to loop through the challenges in search for a supported one.

Handle multiple www-authenticate headers

---

pkg/v1/remote/list.go
pkg/v1/remote/list_test.go

`ListWithContext` is kinda gross when we also have `List(..., remote.WithContext(ctx)` -- let's deprecate it.
edit: the rest is no longer relevant, but useful for context:
~This led a test to fail because the /v2/ request fails on a cancelled context, which I think is good because we shouldn't ignore the provided context for that ping request. In fixing that, I wanted to make the test check for whether the error `errors.Is(context.Canceled)`, but that was stymied by `transport.NewTransportWithContext` losing that information when it does it's little multi-error thing.~
```
list_test.go:115: error was not context.Canceled, got Get "https://127.0.0.1:60957/v2/": context canceled; Get "http://127.0.0.1:60957/v2/": context canceled
```
Gross.
So we have a couple options:
1. change the test to …

Straighten out remote.List{WithContext}

---

cmd/crane/recipes.md

```
$ crane manifest gcr.io/buildpacks/builder:v1 | jq '.config.size + ([.layers[].size] | add)'
238034322
$ crane manifest gcr.io/buildpacks/builder:v1 | jq '.config.size + ([.layers[].size] | add)' | numfmt --to=iec
228M
```

Add recipe to calculate image size

---

pkg/v1/static/layer.go
pkg/v1/static/static_test.go

Mainly copied from [cosign](https://github.com/sigstore/cosign/blob/0fdfaa93446aefba72af08a43d2833dc5f5e2d08/pkg/cosign/remote/remote.go#L198), with basic tests, and a `sync.Once` around `Digest()`.

Add static.NewLayer

---

cmd/crane/cmd/append.go
cmd/crane/doc/crane_append.md
go.mod
go.sum
vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go
vendor/modules.txt

This flag instructs crane append to annotate the resulting image with
information about the base image (name and current digest). This flag is
false by default.

Add --set-base-image-annotations flag to crane append

---

pkg/v1/remote/catalog.go
pkg/v1/remote/list.go
pkg/v1/remote/options.go

I recently found that the GitHub Container Registry doesn't support pagination, so I'm limited to 1000 tags when using the library (rel https://github.community/t/pagination-when-listing-image-tags-does-not-work/194586).
I've added an option that allows disabling the default limit of 1000 tags when requesting image tags.

feat: ability to set page size for tags list and catalog calls

---

cmd/crane/cmd/flatten.go
cmd/crane/cmd/root.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_flatten.md
pkg/crane/crane_test.go
pkg/crane/push.go

This is adapted from #735 but changes the UX a bit to match what we've come to expect from crane.
Add pkg/crane.Upload as well, for uploading a layer.
Closes https://github.com/google/go-containerregistry/pull/1103
---
```
$ crane manifest gcr.io/kaniko-project/executor | jq .
```
```json
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"config": {
"mediaType": "application/vnd.docker.container.image.v1+json",
"size": 3707,
"digest": "sha256:1c812ffa8ec16797474d59cdb7667439e6bc26eb6054f7257b9016bdbc452d11"
},
"layers": [
{
"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
"size": 14219823,
"digest": "sha256:94ed89128ee0d8b28f7cf724c516e51c041424c4bd5bb125fecfeeb76307eb9c"
},
{
"mediaType": …
```

Add crane flatten

---

pkg/v1/mutate/mutate.go

When flattening a filesystem, we have to clean filepaths so that
we don't have duplicate filepaths in the resulting image, as per the OCI
spec (and tar-split throwing a fit if we don't do this).

Clean filepaths in mutate.Extract

---

pkg/v1/remote/transport/error.go

Related to: https://github.com/google/go-containerregistry/issues/1113 
Keeping this PR in draft since there are other details to discuss in #1113 
Authored-by: Dennis Leon <leonde@vmware.com>

Change logic around whether an error is 'Temporary'

---

pkg/legacy/tarball/write_test.go
pkg/v1/mutate/image.go
pkg/v1/mutate/index.go
pkg/v1/mutate/index_test.go
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

I noticed that `cosign` was taking advantage of a bug in the mutate package
where the `Manifest()` returns a mutable copy of it's internal state, which
allowed them to permanently alter the result of `Manifest()`.  This mutability
violates the philosophy of our abstractions, and should not be allowed, so
this change ensures that each of the methods returning state in the `mutate`
package return a `.DeepCopy()` instead.  In `image` this included the
`configFile`, and `manifest`.  In `index` this included the `indexManifest`.
I have added tests that when the returned copies are mutated, a subsequent
invocation of the getter will return a pristine copy.
Since I'm not completely heartless, I am also adding a new
`mutate.ConfigMediaType` method to enable `cosign` to perform the alteration
they …

Make `mutate` constructs immutable.

---

pkg/v1/daemon/image.go
pkg/v1/daemon/image_test.go
pkg/v1/daemon/options.go

Fix https://github.com/google/go-containerregistry/issues/627
A faster way of getting an image ID is really useful for caching. We don't want to call `docker save` if we already have the image information in the cache. For example, in our case, we should skip scanning vulnerabilities of the image when the scan result exists in the cache. The cache key is an image ID, so it is enough to call `docker inspect` to know only the image ID.
This implementation is based on `computed()` as below.
https://github.com/google/go-containerregistry/blob/45aaa6c000ebf2acacad9beef7c82667ec51662c/pkg/v1/mutate/image.go#L51
The downside is that `daemon.Image` doesn't return an error and it might return an error when each method is called (https://github.com/knqyf263/go-containerregistry/commit/881e16e70fdf79 …

feat(daemon): lazy image saving

---

pkg/v1/daemon/image.go

For example, if `LayerByDiffID` of `daemon.Image` is called twice in parallel, `initialize` might be called twice at the same time. Then, `tarball.Image` might be called twice. It is not efficient, so this PR locks `initialize()` before checking `i.tarballImage` for nil so that it will not be initialized twice.
Please let me know if you prefer `sync.Once`. Note that we need to keep `err` in the `image` struct like `imageOpener`.
https://github.com/google/go-containerregistry/blob/c3aee497b158a4c0e4da6584668637ac6b0b13a3/pkg/v1/daemon/image.go#L46
https://github.com/google/go-containerregistry/pull/1121

feat(daemon): avoid multiple initialization

---

pkg/gcrane/copy.go

Missed this when refactoring a while back. We want options to get
proagated down into the image copying logic.

Propagate crane options through gcrane cp -r

---

pkg/v1/remote/multi_write.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

When you Wait() on an errgroup, the underlying context gets cancelled,
so calling Wait() twice will break if you correctly propagate contexts.
We weren't propagating contexts correctly, so this kind of worked
before, but if we actually want to leverage contexts better we should
fix this :)

Don't reuse errgroups, propagate contexts better

---

pkg/v1/google/list.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/multi_write_test.go
pkg/v1/remote/options.go
pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/logger.go
pkg/v1/remote/transport/retry.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/transport/transport_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

Related to https://github.com/google/go-containerregistry/issues/1114
Adds the following 4 options:
- WithRetryHTTPBackoff
- WithRetryHTTPPredicate
- WithRetryTransportBackoff
- WithRetryTransportPredicate
Went with a finer level API around configuring these (in my head) 2 groups of retry logic (low-level transport errors and higher level HTTP errors).
I was also aiming to keep the 'default' retry logic values the same (if these options are not provided).

Make retrying transport and http errors configurable 

---

.github/workflows/analyze.yaml

These were dropped in #1016 and I don't remember why. The result is that code scanning alerts have been disabled since May: https://github.com/google/go-containerregistry/security/code-scanning

Re-enable codeql analysis

---

cmd/crane/recipes.md

I found this useful in debugging a [kaniko issue](https://github.com/GoogleContainerTools/kaniko/issues/702#issuecomment-949649212).

recipe: Document diffing filesystem contents

---

.golangci.yaml
pkg/v1/daemon/image.go
pkg/v1/google/auth.go
pkg/v1/google/list.go
pkg/v1/remote/transport/transport_test.go
pkg/v1/remote/write.go

This previously wasn't linting anything, despite it being in our (copied from Knative forever ago) [Code Style check](https://github.com/google/go-containerregistry/runs/4083873412?check_suite_focus=true), because the repo didn't have a `.golangci.yaml`.
I've disabled most linters that either didn't run for me locally, or had a bunch of false positives. If we feel like fixing these later we can.
cc @mattmoor thanks for catching this.

Enable golangci-lint

---

pkg/v1/remote/transport/ping.go

Debugging why requests to an insecure registry seem to hang, I noticed that there are 3+ requests to the https endpoint before it falls back to http (at that point my logs truncate because the test was over).  The time between the request being issued and completing in the roundtripper was ~30s each.
This change gives each ping a generous 5s timeout to complete each request.

Give the ping context a timeout.

---

pkg/registry/README.md

Fixes https://github.com/google/go-containerregistry/pull/1158
@mattmoor would the presence of this README have helped prevent the situation in #1158 ?

Add pkg/registry/README.md documenting expectations

---

go.mod
go.sum
pkg/authn/k8schain/go.sum
vendor/modules.txt

Closes https://github.com/google/go-containerregistry/pull/1160
```
go get -u github.com/docker/docker@latest
go mod tidy
go mod vendor
```
This dependency has a vulnerability (https://nvd.nist.gov/vuln/detail/CVE-2021-41092) which I don't think we're actually susceptible to, but upgrading is easy and should quiet down any vulnerability scanners that find it.

Bump docker/docker dependency to v20.10.10

---

pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go

**Warning: breaking change.**
Kaniko uses this project and uses `mutate.Canonical` when the `--reproducible` flag is set. This is advertised as resetting the dates, so that the build becomes reproducible. However, it also resets the `CreatedBy` field, due to improper copying.
Example `docker history <img>` **without** `--reproducible`:
```
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
0c0d4077e9d6   292 years ago   COPY debug-page /app/debug-page                 1.51kB
<missing>      292 years ago   COPY --from=builder-dev /app/dist /app/dist     196kB
<missing>      292 years ago   COPY --from=builder-prod /app/node_modules /…   47.9MB
<missing>      292 years ago   COPY package.json config-localdev.json confi…   5.43kB
<missing> …
```

Do not forget CreatedBy in mutate.Canonical 

---

pkg/v1/remote/write.go

Noticed while pushing nested indexes, we lose authentication options
when attempting to upload a nested index with `WriteIndex`.
This PR ensures options are maintained and passed to recursive calls
to `writeIndex`.

Pass Options when recursively calling writeIndex

---

cmd/crane/cmd/root.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_append.md
cmd/crane/doc/crane_auth.md
cmd/crane/doc/crane_auth_get.md
cmd/crane/doc/crane_auth_login.md
cmd/crane/doc/crane_blob.md
cmd/crane/doc/crane_catalog.md
cmd/crane/doc/crane_config.md
cmd/crane/doc/crane_copy.md
cmd/crane/doc/crane_delete.md
cmd/crane/doc/crane_digest.md
cmd/crane/doc/crane_export.md
cmd/crane/doc/crane_flatten.md
cmd/crane/doc/crane_ls.md
cmd/crane/doc/crane_manifest.md
cmd/crane/doc/crane_mutate.md
cmd/crane/doc/crane_pull.md
cmd/crane/doc/crane_push.md
cmd/crane/doc/crane_rebase.md
cmd/crane/doc/crane_tag.md
cmd/crane/doc/crane_validate.md
cmd/crane/doc/crane_version.md
pkg/v1/remote/index.go

Windows images present some unique challenges and one of those challenges is being able to pull a specific OS version. This especially comes into play when working with a manifest like the k8s.gcr.io/pause:3.6 which doesn't offer tags specific to Windows OS version. 
Here is an example use case:
```
crane pull --platform windows/amd64 --osversion 10.0.17763.2114 k8s.gcr.io/pause:3.6 windows-1809.tar
```
Without the version specified Windows Server 2022 would have been pulled.

Adding OS version to Crane for better Windows support.

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md

Just reading the docs and found a spelling mistake - this is especially funny because I've used "entrypoing" so many times (accidentally) in commands it must be the case that our fingers have similar deviance!  :laughing: 
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

spelling: entrypoing->entrypoint

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

Fixes #1145 
This changes `authn.DefaultKeychain` to always check Podman's preferred auth config location (`${XDG_RUNTIME_DIR}/containers/auth.json`) for auth configuration first, and only if that file doesn't exist, fallback to using Docker's `config.Load` and `${DOCKER_CONFIG}` to look for the user's registry auth config.
This matches Podman's [documented behavior](https://docs.podman.io/en/latest/markdown/podman-login.1.html):
> The default path for reading and writing credentials is ${XDG_RUNTIME_DIR}/containers/auth.json. Podman will use existing credentials if the user does not pass in a username. Podman will first search for the username and password in the ${XDG_RUNTIME_DIR}/containers/auth.json, if they are not valid, Podman will then use any existing credentials found in …

Check for Podman's auth.json in DefaultKeychain

---

.golangci.yaml
cmd/crane/cmd/root.go
pkg/v1/mutate/mutate.go
pkg/v1/random/image.go
pkg/v1/tarball/image.go

Better than nothing, and it should prevent future `gosec` findings from sneaking in at least.

Enable gosec, exempt tests, ignore others

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

This reverts commit 309df099955fd39ceecfdaf7bb1a62122794c39d.
Fixes https://github.com/google/go-containerregistry/issues/1183

Revert "Check for Podman's auth.json in DefaultKeychain (#1181)"

---

go.mod
go.sum
pkg/authn/k8schain/go.sum
pkg/authn/keychain.go
pkg/authn/keychain_test.go
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/README.md
vendor/github.com/mitchellh/go-homedir/go.mod
vendor/github.com/mitchellh/go-homedir/homedir.go
vendor/modules.txt

This is a second attempt after https://github.com/google/go-containerregistry/pull/1181, reverted in https://github.com/google/go-containerregistry/pull/1184 due to https://github.com/google/go-containerregistry/issues/1183
The bug seems to be that if `$DOCKER_CONFIG` was unset, we would never look for `$HOME/.docker/config.json`, which `config.Load` does.
The order should be:
1. look for `$HOME/.docker/config.json` <-- missing before; very common
2. look for `$DOCKER_CONFIG/config.json`
3. look for `$XDG_RUNTIME_DIR/containers/auth.json` (Podman auth)
This is now reflected in this PR, with a unit test that builds up each option from 3->1 and checks that the correct auth config is used.
I'm open to more ideas about how to test this better, in case there are more edge cases I'm still not …

Attempt 2: Check for Podman's auth in DefaultKeychain

---

.github/workflows/e2e.yaml
cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md
internal/windows/windows.go

```
$ crane config $(
go run ./cmd/crane mutate \
--entrypoint=dotnet,craneapp.dll \
phillipsj/craneapp:0.1.0 \
-t gcr.io/imjasonh/craneapp:0.1.0) | jq .config.Entrypoint
...
[
"dotnet",
"craneapp.dll"
]
```
This might fix the issue with malformed Windows images created by `crane mutate --entrypoint`, based on Jon's findings -- https://github.com/moby/moby/issues/33373#issuecomment-522189149
cc @phillipsj

Accept multiple entrypoint values in crane mutate

---

cmd/crane/cmd/export.go
internal/gzip/zip.go
pkg/crane/export.go
pkg/crane/export_test.go
pkg/v1/partial/compressed.go

Default second arg to stdout so I don't have to type "-".
For images with a single layer, avoid calling mutate.Extract to flatten
the filesystem, instead we just write the uncompressed bytes to stdout.
In order to make that work, partial.Compressed now actually detects
whether the payload is gzipped or not when calling Uncompressed instead of just
assuming all blobs are compressed (and failing).
Fixes https://github.com/google/go-containerregistry/issues/1150

Make crane export more ergonomic

---

pkg/v1/remote/multi_write_test.go
pkg/v1/remote/transport/transport.go

Previously we would eschew any kind of wrapper if the ping returned a
200, but this means we don't correctly respond to challenges after the
initial ping. This is a half-fix, but for now we just assume basic if
the ping returns a 200 so that (at least) basic auth registries will
work.

Always use basic for anonymous pings

---

cmd/crane/cmd/root.go
cmd/crane/cmd/util.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_append.md
cmd/crane/doc/crane_auth.md
cmd/crane/doc/crane_auth_get.md
cmd/crane/doc/crane_auth_login.md
cmd/crane/doc/crane_blob.md
cmd/crane/doc/crane_catalog.md
cmd/crane/doc/crane_config.md
cmd/crane/doc/crane_copy.md
cmd/crane/doc/crane_delete.md
cmd/crane/doc/crane_digest.md
cmd/crane/doc/crane_export.md
cmd/crane/doc/crane_flatten.md
cmd/crane/doc/crane_ls.md
cmd/crane/doc/crane_manifest.md
cmd/crane/doc/crane_mutate.md
cmd/crane/doc/crane_pull.md
cmd/crane/doc/crane_push.md
cmd/crane/doc/crane_rebase.md
cmd/crane/doc/crane_tag.md
cmd/crane/doc/crane_validate.md
cmd/crane/doc/crane_version.md

This removes the --osversion flag, and lets users specify the osversion
in the --platform flag itself, separated by a ":"
For example:
crane manifest golang:1.17 --platform=windows/amd64:10.0.17763.2366
This matches the proposed behavior in https://github.com/google/ko/pull/536
cc @phillipsj -- is this format acceptable for your uses? `ko` has a stronger need to be able to specify the osversion in the platform, since it allows specifying multiple values, but I'd really like to keep them aligned if we can.

Support specifying osversion in the --platform flag

---

.github/workflows/e2e.yaml
cmd/crane/cmd/push.go
cmd/crane/doc/crane_push.md
go.sum

This adds an `--image-refs` flag to `crane push` similar to the flag
I recently added to `ko`, which emits a file containing the digests
of the various images published by the command.
The intention of this flag is to work well with things like Tekton
Chains' `IMAGES` result for attesting to how a bunch of images were
produced.

Add `--image-refs` to `crane push`.

---

cloudbuild.yaml

I was able to successfully `gcloud builds submit .` with this, so I think it should fix things.

Fix krane build

---

pkg/v1/remote/transport/error.go
pkg/v1/remote/transport/error_test.go

For registries that return a structured error containing UNAVAILABLE, we
weren't retrying because this error code isn't define in any specs;
however, it is used in the wild!

Add UnavailableErrorCode

---

pkg/authn/README.md
pkg/authn/keychain.go
pkg/authn/keychain_test.go

See https://github.com/google/go-containerregistry/pull/1225#issuecomment-1004160197
This adapts an implementation of Docker's [`credentials.Helper`](https://pkg.go.dev/github.com/docker/docker-credential-helpers/credentials#Helper) to be used as an `authn.Keychain`, e.g.:
```golang
kc := authn.NewMultiKeychain(
authn.DefaultKeychain,
google.Keychain,
authn.NewKeychainFromHelper(ecr.ECRHelper{ClientFactory: api.DefaultClientFactory{}}),
authn.NewKeychainFromHelper(credhelper.NewACRCredentialsHelper()),
...
)
```

Add docker cred helper adapter in pkg/authn

---

.github/workflows/e2e.yaml
cmd/crane/cmd/pull.go
pkg/crane/pull.go

Prior to this, we'd also resolve an index to an image when using crane
pull. For OCI Layouts, we can actually pull the whole index, so when
--format=oci and --platform is unset, just do that.

crane pull: support pulling index to OCI Layout

---

pkg/v1/mutate/image.go
pkg/v1/mutate/index.go
pkg/v1/mutate/mutate_test.go

pkg/v1/mutate: fill in mediaType for OCI

---

.github/workflows/ecr-auth.yaml

This uses github OIDC federation to impersonate an AWS role on an account owned by Chainguard, Inc. that I created for the sole purpose of testing this.
This tests both `crane` with the `ecr-login` credential helper and `krane` with the `k8schain` library.
WIP is until this uses `pull_request_target`

Start testing ECR authentication.

---

pkg/v1/layout/write.go
pkg/v1/layout/write_test.go
pkg/v1/stream/layer.go
pkg/v1/stream/layer_test.go
pkg/v1/validate/image.go

This pull request was prompted by https://github.com/linuxkit/linuxkit/pull/3748.
Linuxkit, which uses an oci-layout cache, suffers the need for frequent cache clears, because interrupted downloads of layers results in images which fail `validate.Image` but cannot be repaired with a subsequent `(layout.Path).ReplaceImage`. This is due to the underlying call to `(layout.Path).WriteBlob` which does not overwrite existing files, even if they are smaller than the size the manifest claims they should be.
I found these comments in `pkg/v1/layout/write.go`:
```
// TODO: A streaming version of WriteBlob so we don't have to know the hash
// before we write it.
// TODO: For streaming layers we should write to a tmp file then Rename to the
// final digest.
```
I believe that this PR addresses both …

Use Temp File For `layout.{Write,Append,Replace}` Image/Index Methods

---

pkg/authn/keychain.go

This is similar to what happens when the package looks for Docker's
config.json, it ignores any error (not found, permissions denied, …)
and pass on.
This should help https://github.com/tektoncd/chains/issues/320 not to happen for example.
Signed-off-by: Vincent Demeester <vdemeest@redhat.com>
/cc @imjasonh @mattmoor @concaf

pkg/authn: return Anonymous on podman auth.json errors

---

pkg/v1/layout/write.go

Ensure that layer is closed before renaming file in layout

---

cloudbuild.yaml

`KO_CONFIG_PATH=./.ko/debug` was being interpreted as relative to `cmd/krane` when we `cd`'d into it. Making it an absolute path fixes this.
Fixes https://github.com/google/go-containerregistry/issues/1262
Tested locally and produced `gcr.io/imjasonh/krane:debug`:
```console
$ docker run --rm --entrypoint sh gcr.io/imjasonh/krane:debug -c "ls /"
bin
boot
busybox
...
```

Fix krane:debug image to include shell

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

- only pass RegistryStr, since helpers don't expect to see repo paths,
and might not handle them correctly
- if the returned username is "<token>", interpret the returned password
as an identity token
- add unit tests to cover both of these behaviors
This builds on the excellent work done by @simongottschlag in https://github.com/google/go-containerregistry/pull/1256, and adds unit tests.

Fix NewKeychainFromHelper

---

.github/ISSUE_TEMPLATE/crane_bug_report.md
.github/ISSUE_TEMPLATE/ggcr_bug_report.md

The `:` in the name seems to confuse the YAML parser, and as a result these issue templates are not available at https://github.com/google/go-containerregistry/issues/new/choose

Fix issue templates

---

pkg/v1/remote/options.go

We see EOF when the server closes a connection without sending an
appropriate "Connection: close" header. The http Client attempts to
reuse a connection, but it fails with EOF because that connection is
closed. For idempotent requests, the http client will handle this for
us, but because this is a POST request, we just get the EOF back.

Add EOF to remote default retry predicate

---

pkg/v1/daemon/image.go

Currently, daemon.Image is so lazy that non-existent images don't return
an error. This changes ensures that the image actually exists by asking
the daemon for its Image ID.
Fixes https://github.com/google/go-containerregistry/issues/1186

Eagerly fetch image ID in daemon.Image

---

.github/workflows/ghcr-auth.yaml
cmd/krane/main.go
pkg/authn/github/keychain.go
pkg/authn/github/keychain_test.go

Add pkg/authn/github.Keychain to authenticate with ghcr.io

---

pkg/v1/google/auth_test.go
pkg/v1/google/keychain.go

If `google.Keychain` is used with `NewMultiKeychain`, it will be selected to provide credentials to pull or push images for images in GCR/AR. If, in this case, Application Default Credentials aren't configured and `gcloud` is not available or configured to provide credentials, the keychain will fail, even if the image is otherwise publicly available.
With this change, if the env credential lookup and `gcloud` credential lookup both fail, instead of returning an error, `google.Keychain` will fallback to return `authn.Anonymous` instead. In this case, `NewMultiKeychain` will fall through each option in turn, until finally using `authn.Anonymous` if none match and provide credentials.

Fallback to anonymous if env or gcloud are not configured

---

pkg/v1/google/auth.go

This should reduce log spam to stderr for clients using google.Keychain
when they don't have Google auth configured.

Pass gcloud stderr to logs.Warn

---

pkg/crane/filemap.go
pkg/crane/filemap_test.go
pkg/v1/tarball/layer.go

See https://twitter.com/ariadneconill/status/1491913976795602947
Also mark the method as `Deprecated`, and reimplement our own only usage of it in `pkg/crane.Layer(filemap)` using `tarball.LayerFromOpener` instead.

LayerFromReader: buffer contents to a temp file instead of in memory

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

This enables the case where a config's auth section can specify different auth per repository within the same registry.
This seems to be the root cause of https://github.com/GoogleContainerTools/kaniko/issues/687

Check docker config auths for repo and registry

---

.github/workflows/e2e.yaml

GitHub Actions recently updated the Windows version used by
windows-latest, which is no longer compatible with the nanoserver:1809
base image used in our Windows e2e test.
Using :ltsc2022 instead should ensure we have a compatible image.
Example successful run: https://github.com/imjasonh/go-containerregistry/runs/5202498982

Fix Windows e2e test

---

pkg/authn/kubernetes/keychain.go
pkg/authn/kubernetes/keychain_test.go

Previous PR broke this case - https://github.com/google/go-containerregistry/pull/1299
Added a test

authn/kubernetes - fix index.docker.io case

---

.github/workflows/boilerplate.yaml
.github/workflows/donotsubmit.yaml
.github/workflows/style.yaml

I created these so we could more centrally manage them for folks.  We can snap a release and use `@v1` instead of `@main` (and manage with dependabot) but I wanted to test the waters.
If y'all are interested in this, I can do the same for `ko` next.

Take advantage of Chainguard maintained versions of various actions.

---

pkg/authn/keychain_test.go

Cover a couple special paths in keychain unit tests.

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md

Support passing crane mutate an output as a tar. Append has it and it is useful for all kinds of more complex build and push flows

Add output option to mutate to save to a tar file and not push to a registry (same as append)

---

pkg/v1/remote/multi_write_test.go
pkg/v1/remote/write.go

Currently we just fail outright if the registry returns a 500 during a
blob HEAD because it's not included in the retry logic. This is not
ideal, especially in cases where an upload actually succeeded but we
never got a response from the server so we're re-uploading a blob for no
reason.

Include blob existence checks in retries

---

cmd/crane/rebase_test.sh
hack/presubmit.sh

`rebase_test.sh` hasn't been running in CI 😱 
Luckily it seems to still pass.

Add rebase_test.sh to hack/presubmit.sh

---

cmd/crane/cmd/export.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_export.md
pkg/crane/export.go

Implementation for #1273.
The goal is to read from stdin if the first argument is "-".
```
./crane export - ubuntu.tar < test.tar
```
~~I was not able to trace what is wrong with reading from `os.Stdin`, and my Go skills are not that good to understand it from the code.~~

crane export: Support reading tarball from a stream

---

pkg/v1/remote/transport/bearer.go

This is an attempt to work around some interesting behavior from
DockerHub.
> This query parameter should be specified multiple times if there is
> more than one scope entry from the WWW-Authenticate header.
https://docs.docker.com/registry/spec/auth/token/#requesting-a-token
It would stand to reason that we shouldn't specify scope multiple times
if there is only one (space-separated) scope in the header.

Don't parse challenge's scopes, put them first

---

hack/presubmit.sh

Otherwise they are still installed in `~/go/bin`.

Fix isolation of presubmit tools

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md

This flag sets the `User` property of the container config. 
Tested with:
```
go run cmd/crane/main.go mutate <my image> --user="12:34"
```
Fixes #1309

Add --user flag to crane mutate

---

pkg/authn/k8schain/k8schain.go

This speeds up instances where the credentials are in image pull secrets

use k8s keychain first

---

pkg/v1/random/index.go
pkg/v1/random/index_test.go

`random.Index()` does not set media type on it's return value's underlying `v1.IndexManifest`, which is accessible to callers.

fix(v1/random): set MediaType in `randomIndex.manifest`

---

pkg/v1/remote/options.go

fix(v1/remote): return an error if both auth and keychain are set

---

pkg/authn/k8schain/go.mod
pkg/authn/kubernetes/go.mod
pkg/authn/kubernetes/keychain.go
pkg/authn/kubernetes/keychain_test.go

Prior we weren't matching host names and partial paths properly
This was breaking Gitlab and Azure tag to digest resolution in Knative (https://github.com/knative/serving/issues/12761)

authn.kubernetes.Resolve now behaves exactly like Kubernetes

---

.github/workflows/build.yaml
.github/workflows/bump-deps.yaml
.github/workflows/e2e.yaml
.github/workflows/ecr-auth.yaml
.github/workflows/ghcr-auth.yaml
.github/workflows/presubmit.yaml
.github/workflows/release.yml
.github/workflows/stale.yaml
.github/workflows/style.yaml
.github/workflows/test.yaml
pkg/v1/remote/transport/error_test.go
pkg/v1/remote/write_test.go

- update go action to always get the latest available
- update some jobs to use go 1.17
- add go1.18 to be tested as well
- update golangci-lint to 1.45.2

update go action to always get the latest available and other updates

---

pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/transport/transport_test.go

Fixes https://github.com/google/go-containerregistry/issues/1359

transport: Don't pass default service if unset

---

pkg/v1/config.go

Signed-off-by: Markus Lippert <lippertmarkus@gmx.de>
By mutating an image, the configfile is copied. When the source image is e.g. linux/arm/v7 the variant is currently not copied as its not part of the ConfigFile struct.
This field is usually part of the config https://github.com/opencontainers/image-spec/blob/main/image-index.md#platform-variants:
`crane config mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine-arm64v8`
```diff
{
...
"architecture": "arm64",
"os": "linux",
+    "variant": "v8"
}
```

fix(ConfigFile): Add Variant

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md

Signed-off-by: Markus Lippert <lippertmarkus@gmx.de>

feat(crane): allow setting the repository to push by digest

---

pkg/authn/k8schain/k8schain.go

supercedes #1367
cc @vpnachev
#1346 only prioritized the k8s secrets when using `New`, not `NewFromPullSecrets`.

k8schain: prioritize imagePullSecrets over implicit auth

---

pkg/v1/cache/cache.go
pkg/v1/cache/cache_test.go

feat(cache): cacheable v1.ImageIndex

---

cmd/crane/cmd/rebase.go

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Furkan Türkal <furkan.turkal@trendyol.com>
Fixes #1383

Fix panic in crane rebase

---

pkg/v1/partial/compressed_test.go
pkg/v1/partial/with.go
pkg/v1/remote/mount.go

Because we wanted to reuse the layer uploading code, we wrap the config
bytes up as a Layer. Unfortunately, the partial.ConfigLayer
implementation doesn't preserve the fact that for mountable images, we
can perform a cross-repo mount.
This change updates partial.ConfigLayer to look for a ConfigLayer
implementation on the given image to see if it can simply dispatch to
that, falling back to calculating it from the config bytes otherwise.

Allow config files to be mounted

---

pkg/v1/remote/check.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

This is currently only implemented by Google but we'd like to upstream
this to the distribution spec. There's a small possibility that this
will break registries that don't implement the spec properly.
We signal the domain of the origin registry with the "origin"
querystring parameter.
Fixes https://github.com/google/go-containerregistry/issues/1321
Likely breaks with harbor because of https://github.com/google/go-containerregistry/pull/219 but they [SHOULD](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#mounting-a-blob-from-another-repository) be returning a 202 here.

Implement cross-registry blob mounting experiment

---

pkg/v1/google/keychain.go

This would have been helpful in debugging why crane worked while gcrane
didn't.

Add debug logs to google.Keychain

---

pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

This allows the go http client to retry requests transparently in
certain situations.
Fixes https://github.com/google/go-containerregistry/issues/1318

Set GetBody on blob uploads

---

cmd/crane/cmd/root.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_append.md
cmd/crane/doc/crane_auth.md
cmd/crane/doc/crane_auth_get.md
cmd/crane/doc/crane_auth_login.md
cmd/crane/doc/crane_blob.md
cmd/crane/doc/crane_catalog.md
cmd/crane/doc/crane_config.md
cmd/crane/doc/crane_copy.md
cmd/crane/doc/crane_delete.md
cmd/crane/doc/crane_digest.md
cmd/crane/doc/crane_export.md
cmd/crane/doc/crane_flatten.md
cmd/crane/doc/crane_ls.md
cmd/crane/doc/crane_manifest.md
cmd/crane/doc/crane_mutate.md
cmd/crane/doc/crane_pull.md
cmd/crane/doc/crane_push.md
cmd/crane/doc/crane_rebase.md
cmd/crane/doc/crane_tag.md
cmd/crane/doc/crane_validate.md
cmd/crane/doc/crane_version.md
pkg/crane/options.go

Since https://github.com/google/go-containerregistry/pull/930 non-distributable layers can be pushed by setting an option.
This PR exposes this option (`--allow-nondistributable-artifacts`) to crane command.

feat(crane): add --allow-nondistributable-artifacts option to allow pushing non-distributable layers

---

go.mod
pkg/authn/kubernetes/go.mod
pkg/authn/kubernetes/go.sum
pkg/name/digest.go
pkg/name/digest_test.go
vendor/github.com/opencontainers/go-digest/algorithm.go

Fixes https://github.com/google/go-containerregistry/issues/1394
cc @wlynch

Use go-digest to validate digests

---

hack/presubmit.sh
pkg/v1/remote/transport/error_test.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/transport/transport_test.go
pkg/v1/remote/write_test.go

This PR contains the following changes:
1. Bump staticcheck to the latest version and fix problems detected.
2. When a RoundTripper of the type `transport.Wrapper` is provided to the function `NewWithContext`, the function will assume that the called has already created the RoundTripper and made sure that the authentication happened and that the registry supports V2 of distribution spec.

Do not check /v2 endpoint on registry when RoundTripper is provided

---

cmd/crane/cmd/pull.go
cmd/crane/doc/crane_pull.md
pkg/crane/pull.go

A bunch of breaking changes that might be contentious, but I think this
is probably the right behavior.
1. Stick the full image ref in the image (not just e.g. ubuntu) so it's
clear that it's the image and not just a tag.
2. Only do this when --annotate-ref is passed, so that these things are
location-independent by default.
3. Switch from a crane annotation key to the standard OCI key.

Don't annotate refs by default, switch to OCI key

---

pkg/v1/remote/multi_write.go
pkg/v1/remote/progress.go
pkg/v1/remote/write.go

Atomically incrementing the number of bytes written isn't sufficient if
we're sending the updates out of order.
I ran the progress tests 50 times after this change and they passed.

Wrap progress updates in a mutex

---

pkg/authn/kubernetes/keychain_test.go

This wasn't previously covered, and better tests seem like they might help us narrow down the cause of https://github.com/knative/serving/issues/12761
cc @dprotaso

Add unit test covering .dockerconfigjson secrets

---

cmd/crane/cmd/root.go
internal/cmd/edit.go
internal/cmd/edit_test.go
internal/editor/editor.go

This works at least on linux with neovim. If stdin appears to be
interactive, crane edit will open an editor with the contents of the
target manifest/config/file. Otherwise, crane edit will read the desired
contents from stdin and just overwrite them for the target.

Implement crane edit

---

.github/workflows/ecr-auth.yaml
.github/workflows/ghcr-auth.yaml
cmd/crane/cmd/auth.go
cmd/crane/cmd/root.go
cmd/crane/doc/crane_auth_get.md
cmd/gcrane/main.go
pkg/crane/options.go

This PR enables to work "auth get" command with the platform specific keychains given in `krane` tool.

Support the platform specific authentication of krane in "auth get" command

---

pkg/v1/mutate/mutate.go

Fix tar PAX format handling

---

pkg/authn/README.md

`authn.NewFromHelper` is not a function, and should be `authn.NewKeychainFromHelper`.

Correct usage of authn.NewKeychainFromHelper in docs

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

In a kubernetes environment, a volume from a Secret can be optionally
mounted. If the Secret does not exist, the mounted path is always a
directory.
This change modifies auth.DefaultKeychain to ignore the case where the
docker config file is unexpectedly a directory.
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

Ignore docker config if it's a directory

---

.github/workflows/release.yml

Signed-off-by: Asra Ali <asraa@google.com>
Hi,
I'm reaching out on behalf of the [Open Source Security Foundation (openssf.org)](https://openssf.org/). We work on improving the security of critical open source projects like yours. 
Together with [GitHub](https://github.blog/2022-04-07-slsa-3-compliance-with-github-actions/), we designed a free, easy-to-use method of code signing. It will help your users verify that your release tarballs were built from your repository’s [workflow](https://github.com/google/go-containerregistry/blob/main/.github/workflows/release.yml) and not altered by anyone. It’s just a few lines of code, but it will make your project more secure against third-party tampering and attacks like attacks like [Codecov](https://about.codecov.io/apr-2021-post-mortem) and …

ci: Generate SLSA signatures for GitHub released tarballs

---

.goreleaser.yml

This adds krane to the release artifacts of this repo so it is not necessary to run `go install` to use it.

feat: Add krane to release archive

---

.github/workflows/release.yml

Signed-off-by: Asra Ali <asraa@google.com>
This updates goreleaser-action to fix this bug, ensures that v3.1.0 is chosen: https://github.com/goreleaser/goreleaser-action/issues/368
Otherwise, the action does not populate the artifacts output, which would lead to provenance generation failure.
@laurentsimon

deps: update goreleaser-action for bug

---

cmd/crane/cmd/root.go

https://github.com/google/go-containerregistry/pull/1449 changed `remote.DefaultTransport` to be a `http.RoundTripper` instead of a `*http.Transport`, and made a corresponding change in `crane` to call `Clone` only if the provided `RoundTripper` was also cloneable. It was overly clever, and unnecessary, and seems to have broken `crane`'s insecure repo support.

fix crane's root.go after DefaultTransport change

---

pkg/name/errors.go
pkg/name/errors_test.go

The function IsErrBadName says it is deprecated and directs the user to
use errors.Is(), but that will never return true because this error is
custom based on the tag value.
This fixes that problem by implementing an Is() function on ErrBadName
so that errors.Is() can properly identify the error as an ErrBadName.
Usage can now be: errors.Is(err, &ErrBadName{})
This exact problem was actually discussed when the deprecated warning was introduced: https://github.com/google/go-containerregistry/pull/1164/files#r742970357

Make ErrBadName checkable via errors.Is()

---

.github/workflows/release.yml

Signed-off-by: Asra Ali <asraa@google.com>
We just updated the generators because of a breaking change in verification flows due to a rekor sharding rollout

deps: bump version of slsa generator

---

pkg/authn/kubernetes/keychain.go
pkg/authn/kubernetes/keychain_test.go

Fixes https://github.com/google/go-containerregistry/issues/1471

k8schain: Log and proceed if secret or SA are not found

---

pkg/v1/remote/transport/bearer.go

Signed-off-by: Spike Curtis <spike@coder.com>

Fix missing body.Close() in bearer auth

---

cmd/crane/cmd/catalog.go
cmd/crane/cmd/root.go
cmd/crane/doc/crane_catalog.md

Following [Cobra Recommended Syntax](https://github.com/spf13/cobra/blob/main/command.go#L50) for "Use", I added the required argument annotation to the command.
While the registry argument may be assumed, I believe this improves the user experience by explicitly defining required arguments. Runtime without a registry `Error: accepts 1 arg(s), received 0` and use of the `--help` flag does not define what the expected argument should be.

crane: add catalog argument use annotation

---

internal/retry/retry.go
internal/retry/retry_test.go

When using the default retry predicate, `context.DeadlineExceeded` errors wrapped in a `*url.Error` are misclassified as temporary and retryable due to an error equality comparison that should be an `errors.Is`.
This bug results in behavior where timeouts cause the client to continue retrying (and therefore sleeping due to the retry backoff) past the client timeout. [This script](https://gist.github.com/ethan-lowman-dd/7f7af09a5ca5ee9146e41b16f0d87e7d) can be used to reproduce the issue. It simulates 5 seconds of latency on every HTTP request and a 10 second client timeout.
```
git clone git clone https://gist.github.com/7f7af09a5ca5ee9146e41b16f0d87e7d.git go-containerregistry-timeout-test
cd go-containerregistry-timeout-test
go run main.go
```
Output:
```
2022/11/09 20:53:52 POST …
```

Fix context.DeadlineExceeded error comparison in retry.IsTemporary

---

.github/workflows/release.yml

Our v0.12.1 failed to generate provenance because we're using a broken version. I checked for the latest release of this before cutting our release, but v1.2.2 is not marked as "latest" on GitHub, so I missed it.

Bump slsa-framework/slsa-github-generator to 1.2.2

---

pkg/authn/kubernetes/keychain.go
pkg/authn/kubernetes/keychain_test.go

:gift: There are contexts where it may be desirable to leverage the `kubernetes` keychain for authentication where `imagePullSecrets` are explicitly specified, but there isn't a `serviceaccount`.  However, currently there isn't a way to bypass the `default/default` `serviceaccount` lookup performed by this keychain.
This change introduces a new `NoServiceAccount` constant that may be passed via `ServiceAccountName` to elide the `serviceaccount` -> `imagePullSecrets` lookup.  The chosen constant is itself an invalid `serviceaccount` name, so this change is backwards compatible.
/kind feature

Features: Allow eliding `serviceaccount` lookups.

---

cmd/crane/README.md

I don't think it is standard to advise people to pull the debug image. I would imagine that would be like giving people the beta as the standard

docs: pull latest instead of debug

---

pkg/v1/remote/transport/bearer.go

We hit this if the auth handshake fails, but this says "no matching credentials", which isn't necessarily true. Check for authn.Anonymous before saying they weren't found.

Make credential warning slightly more accurate

---

cmd/crane/depcheck_test.go
cmd/gcrane/depcheck_test.go
internal/cmd/edit_test.go
pkg/gcrane/copy_test.go
pkg/registry/blobs.go
pkg/registry/depcheck_test.go
pkg/registry/registry.go
pkg/v1/partial/compressed_test.go
pkg/v1/partial/index_test.go
pkg/v1/partial/uncompressed_test.go
pkg/v1/remote/image_test.go
pkg/v1/remote/multi_write_test.go
pkg/v1/remote/options.go
pkg/v1/remote/progress_test.go
pkg/v1/tarball/progress_test.go

Before:
```
$ time go test -short -count=1 ./...
ok  	github.com/google/go-containerregistry/cmd/crane	0.843s
?   	github.com/google/go-containerregistry/cmd/crane/cmd	[no test files]
?   	github.com/google/go-containerregistry/cmd/crane/help	[no test files]
ok  	github.com/google/go-containerregistry/cmd/gcrane	0.883s
?   	github.com/google/go-containerregistry/cmd/gcrane/cmd	[no test files]
?   	github.com/google/go-containerregistry/cmd/registry	[no test files]
ok  	github.com/google/go-containerregistry/internal/and	0.028s
ok  	github.com/google/go-containerregistry/internal/cmd	1.638s
ok  	github.com/google/go-containerregistry/internal/compare	0.044s
ok  	github.com/google/go-containerregistry/internal/compression	0.024s
?   	github.com/google/go-containerregistry/internal/depcheck …
```

Make unit tests substantially faster

---

internal/retry/retry.go
pkg/v1/remote/check.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/options.go
pkg/v1/remote/transport/retry.go
pkg/v1/remote/transport/retry_test.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

We have two levels of retries here.
The first is in the retryTransport, which currently just tests IsTemporary. This has a short backoff and was intended to handle blips in the network.
The second level was intended for higher level issues, e.g. if an upload PUT failed, we have to retry more than just a single HTTP request, because we might have to restart the upload with a new POST and PATCH.
This change propagates the default retryable predicate (from the scond level) down to the retryTransport. This also adds a list of HTTP codes that are retryable, so that the retryTransport can also handle server-side errors that should be retried.
Note that this doesn't respect remote.WithRetry{Backoff,Predicate} because callers can just override the entire transport via remote.WithTransport. This …

Use the default retry predicate in transport

---

cmd/crane/README.md

Fixes https://github.com/google/go-containerregistry/issues/1503
This reverts commit 37b993ac11d2c2f9708ed7927909d850b4a17bbe.

Revert "docs: pull latest instead of debug (#1497)"

---

pkg/v1/remote/options.go
pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go

This implements a "happy eyeballs" (RFC 6555) style of race in order to speed up http fallback during registry pings.
This heavily borrows code from [net/dial.go](https://cs.opensource.google/go/go/+/master:src/net/dial.go;l=447;drc=38cfb3be9d486833456276777155980d1ec0823e) which implements this same kind of race for dual stack DNS.
Rather than waiting for the initial "https" ping to time out completely before attempting to use "http", we will instead start a second fallback ping after 300ms and return whichever response comes back first.
Partially reverts https://github.com/google/go-containerregistry/pull/1165 given that it negatively impacts dns fallback (https://github.com/google/go-containerregistry/pull/1517).

Race http fallback ping

---

pkg/authn/keychain_test.go
pkg/crane/crane_test.go
pkg/v1/cache/fs_test.go
pkg/v1/layout/write_test.go

A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

cmd/crane/cmd/digest.go
cmd/crane/doc/crane_digest.md

```
$ crane digest cgr.dev/chainguard/static
sha256:0394eb00eabee3530bdfc0dd5845806e5badcc840cbd0746b0d5bd912c9d51fc
$ crane digest --full cgr.dev/chainguard/static
cgr.dev/chainguard/static@sha256:0394eb00eabee3530bdfc0dd5845806e5badcc840cbd0746b0d5bd912c9d51fc
$ crane digest --full cgr.dev/chainguard/static --platform=linux/arm64
cgr.dev/chainguard/static@sha256:694b43c7eca332b9a37d7767299d51ac336c2a2187acce230eb528a17ae3522d
```
I find myself wanting this sometimes, and I usually hack it together with bash and feel terrible about myself.

crane: add digest --full

---

cmd/crane/cmd/list.go
cmd/crane/doc/crane_ls.md

Before:
```
crane ls cgr.dev/chainguard/static
20220302
sha256-bab7d22b93180e8a05d0f02c739605cc7ed52b414b8f70ad6a173f2c0c8dc946.sig
sha256-e86edc0a7f00adb469d13b49192f38f992a981d778aa3f24525aa83b370b4001.sig
20220303
sha256-1535c58eb82f566a382131ba23583135aaba4e22fccccaadcd00b24286c47ad7.sig
...
```
After:
```
go run ./cmd/crane ls cgr.dev/chainguard/static --full-ref
cgr.dev/chainguard/static:20220302
cgr.dev/chainguard/static:sha256-bab7d22b93180e8a05d0f02c739605cc7ed52b414b8f70ad6a173f2c0c8dc946.sig
cgr.dev/chainguard/static:sha256-e86edc0a7f00adb469d13b49192f38f992a981d778aa3f24525aa83b370b4001.sig
cgr.dev/chainguard/static:20220303
cgr.dev/chainguard/static:sha256-1535c58eb82f566a382131ba23583135aaba4e22fccccaadcd00b24286c47ad7.sig
...
```

crane: support --full-ref for crane ls

---

pkg/v1/remote/descriptor.go

DockerHub has rolled out a fix for this:
```
$ cat .git/HEAD
ref: refs/heads/plugins
$ go run ./cmd/crane/ manifest vieux/sshfs
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"config": {
"mediaType": "application/vnd.docker.plugin.v1+json",
"size": 1055,
"digest": "sha256:b336e50d046bfb078f0b2eced46851322603342c34ae25ca6cc4712253344ae1"
},
"layers": [
{
"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
"size": 8820470,
"digest": "sha256:52d435ada6a4127b66e31157e3ad0f4db3f4b61c7c380ffd89d065fc24faa339"
}
]
}
```

Revert plugin scope hack

---

cmd/crane/README.md

The download instructions include the $VERSION in the path twice, which isn't a valid link. 
After getting it to work for a specific release, I figured people might also want instructions to download the latest release, which uses a different URL path, so added that example as well.

clarify crane download readme

---

pkg/legacy/tarball/write.go
pkg/registry/manifest.go
pkg/registry/registry_test.go
pkg/v1/hash.go
pkg/v1/random/image.go
pkg/v1/remote/write_test.go
pkg/v1/stream/layer.go
pkg/v1/validate/layer.go

This enables doing something like
https://github.com/opencontainers/go-digest/issues/71#issuecomment-1330069987 to override the hashing method (example: replace with sha256simd).
When an importer does not overriden, the library should behave exactly the same.
See https://github.com/google/go-containerregistry/issues/1330

hash: use generic instantiation

---

.github/workflows/release.yml

Fix https://github.com/google/go-containerregistry/issues/1539
NOTE: we will release the slsa verifier Action Installer in a few weeks, so we'll be able to remove the script that manually downloads the slsa-verifier binary.

Update attestation name

---

pkg/v1/manifest.go
pkg/v1/mutate/index_test.go
pkg/v1/mutate/mutate.go
pkg/v1/partial/with.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/image.go
pkg/v1/remote/index.go
pkg/v1/types/types.go

If an index contains an image whose config.mediaType is not the normal config type (i.e., it's an artifact, packaged as an image for registry compatibility), the index's descriptor for the image will include `artifactType`.
This is work toward supporting the OCI 1.1 referrers fallback tag scheme, where referrers are managed by the client and pushed as indexes to the registry, tagged with `:sha256-abcdef...`.
cc @jdolitsky

Support artifactType, for images whose config.mediaType is not a config

---

internal/cmd/edit.go

Instead of using mutate, just do this ourselves to allow for arbitrary config file contents rather than mutating the OCI config struct.

Allow crane edit to generate non-image artifacts

---

pkg/v1/manifest.go
pkg/v1/mutate/image.go
pkg/v1/mutate/index.go
pkg/v1/mutate/mutate.go
pkg/v1/mutate/mutate_test.go
pkg/v1/remote/delete.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/options.go
pkg/v1/remote/referrers.go
pkg/v1/remote/referrers_test.go
pkg/v1/remote/write.go

Builds on top of #1541 
Crane subcommands "attach" and "refs" dropped in this PR, but can be found here: https://github.com/google/go-containerregistry/compare/main...jdolitsky:attach-pt-3?expand=1
cc @imjasonh

Support for OCI 1.1+ referrers via fallback tag

---

pkg/v1/mutate/mutate.go

fixes #1523 
Currently, layerTime only mutates the modification timestamp which is present in all tar formats. When working with layers GNU or PAX header formats, access and change timestamps are also generated/recorded. This breaks functionality like reproducible builds which rely on having control over all variable fields (esp. timestamps)  in the layers
This commit adds a special case to the layerTime(Layer, Time) function which will also set the additional timestamps if the header is of GNU or PAX format
Signed-off-by: Joel Pepper <pepper@bronze-deer.de>

fix(mutate): also set timestamps only present in some formats

---

internal/cmd/edit.go

This uses the --media-type flag.

Allow setting Content-Type in crane edit manifest

---

pkg/registry/manifest.go
pkg/registry/registry.go
pkg/registry/registry_test.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/referrers_test.go
pkg/v1/remote/write.go

Follow-up to #1543, use the referrers API endpoint if the registry supports it, otherwise fallback to digest tag

Support for OCI 1.1+ referrers via API

---

cmd/crane/cmd/index.go
cmd/crane/cmd/root.go
cmd/crane/cmd/util.go
cmd/crane/doc/crane.md
cmd/crane/doc/crane_index.md
cmd/crane/doc/crane_index_append.md
cmd/crane/doc/crane_index_filter.md
cmd/crane/recipes.md
pkg/v1/config.go
pkg/v1/platform.go
pkg/v1/platform_test.go

crane index filter allows platform-based filtering of manifests in an index. This is primarily useful for folks who want to use only some entries in a base image without having to copy irrelevant platforms.
crane index append allows appending manifests to an existing index or creating a new index from scratch.
Fixes https://github.com/google/go-containerregistry/issues/1144
Fixes https://github.com/google/go-containerregistry/issues/1143
Fixes https://github.com/google/go-containerregistry/issues/1557
See also:
* https://github.com/google/go-containerregistry/pull/891
* https://github.com/google/go-containerregistry/issues/1144#issuecomment-1044845681

Implement crane index subcommand

---

pkg/v1/tarball/write.go

In `tarball.MultiWrite()`,  the `map[name.Reference]v1.Image` is inverted to a `map[v1.Image][]string` by 3 independent helpers. This PR modifies to invert the map once, then pass the result between helpers.
I'd made this change as part of a failed attempt at `tarball.WriteIndex()` - I realize now why that was a bad idea, but this snippet seemed worth saving.

tarball: pass imageToTags

---

cmd/crane/README.md

Fixes #1565 
1. Updates the slsa-verifier command to use v2.
2. Instructions now ensure you set the `VERSION` environment variable.
Signed-off-by: Ian Lewis ianlewis@google.com

docs: Update crane installation and verification instructions

---

cmd/crane/cmd/index.go
cmd/crane/doc/crane_index_append.md
pkg/v1/zz_deepcopy_generated.go

While it's possible that folks might want to append an index to an index, it's more likely that they would want to merge them. This flag gives them an option to do either.

crane: add --flatten for index append

---

cmd/crane/cmd/list.go
cmd/crane/doc/crane_ls.md

Before:
```
$ crane ls cgr.dev/chainguard/static | head -n 10
20220302
sha256-bab7d22b93180e8a05d0f02c739605cc7ed52b414b8f70ad6a173f2c0c8dc946.sig
sha256-e86edc0a7f00adb469d13b49192f38f992a981d778aa3f24525aa83b370b4001.sig
20220303
sha256-1535c58eb82f566a382131ba23583135aaba4e22fccccaadcd00b24286c47ad7.sig
sha256-061d30276694f8ae8e6a47eec9e7b7526d5e0c89436217907cac09cc19d9a953.sig
20220304
sha256-6168c94e3afa1b01a090632f77309ce541e1f502d8783071d026eb97a211b723.sig
sha256-8953bc492aebe6574d8735174000a7cea046de6ec8b6b28501ae27110352bc11.sig
20220305
$ crane ls cgr.dev/chainguard/static | wc -l
7890
```
After:
```
$ go run ./cmd/crane ls cgr.dev/chainguard/static --omit-digest-tags | head -n 10
20220302
20220303
20220304
20220305
20220306
20220307
20220308
20220309
20220310
20220311
$ go run …
```

crane: support --omit-digest-tags in crane ls

---

internal/cmd/edit.go

Fixes #1552
(I opted _not_ to base this on top of #1583, but I'm happy to adjust if that's preferred or rebase/update after it is :sweat_smile:)
Of course, happy to rebase, amend, adjust, close, etc as desired. :bow:

Update descriptor "data" field (when valid) during "crane edit config"

---

internal/cmd/edit.go

Because of how omitempty works, an empty Layers and a nil Layers will both be omitted. We don't want that, because different registries support different variants of that. Instead, we just pass through whatever was there before by treating the manifest as a map[string]any and manipulating that rather than using v1.Manifest-based helpers.

Avoid v1.Manifest in crane edit config

---

.github/workflows/release.yml

closes https://github.com/google/go-containerregistry/issues/1600
Changes in this PR:
- Updated the command line, since the Action uses v2.x installation
- Updated the binary call. The Action installs it in the `PATH` and the binary name is `slsa-verifier`

Fix SLSA verification

---

pkg/gcrane/copy.go

I'm not sure the backoff needs changing, but the posted quotas have changed.
TODO: ARBackoff()

update GCR quotas

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

Sometimes Authenticators stick around for a while and eventually expire. This changes modifies Authenticators returned by DefaultKeychain to re-resolve after 5 minutes to ensure the underlying creds are fresh.
The hard-coded 5 minutes should prevent us from spamming the underlying Keychain (it can be expensive) while also preventing the creds from expiring.

Refresh authn.DefaultKeychain creds every 5 min

---

pkg/v1/remote/catalog.go
pkg/v1/remote/delete.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/descriptor_test.go
pkg/v1/remote/image.go
pkg/v1/remote/image_test.go
pkg/v1/remote/index.go
pkg/v1/remote/index_test.go
pkg/v1/remote/layer.go
pkg/v1/remote/list.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/options.go
pkg/v1/remote/progress.go
pkg/v1/remote/referrers.go
pkg/v1/remote/write.go

This will allow reuse across a repository.
One major difference is that keychains are no longer resolved within the option execution, but lazily during fetcher/writer construction.

Refactor fetcher/writer constructors

---

pkg/v1/remote/descriptor.go
pkg/v1/remote/schema1.go
pkg/v1/remote/schema1_test.go
pkg/v1/types/types.go

This will allow just passing a remote.Descriptor to remote.Pusher and
also gives an escape hatch for filesystem access to schema1 images.

Add remote.Descriptor.Schema1()

---

pkg/crane/export.go
pkg/v1/types/types.go

Fixes https://github.com/google/go-containerregistry/issues/1623
Before:
```
$ crane export quay.io/integreatly/3scale-bundle:v0.8.0 | tar -tv | grep wh
-rwxr-xr-x  0 0      0           0 Dec 31  1969 root/.wh..wh..opq
-rwxr-xr-x  0 0      0           0 Dec 31  1969 metadata/.wh..wh..opq
-rwxr-xr-x  0 0      0           0 Dec 31  1969 manifests/.wh..wh..opq
```
After:
```
$ crane export quay.io/integreatly/3scale-bundle:v0.8.0 | tar -tv | grep wh
$
```

Don't export whiteouts for single layers

---

cmd/crane/cmd/flatten.go

Fixes https://github.com/google/go-containerregistry/issues/1622

crane: ignore buildx attestations in flatten

---

cmd/crane/cmd/flatten.go
pkg/v1/mutate/index.go
pkg/v1/partial/index.go
pkg/v1/remote/index.go

This allows us to manipulate an index that contains an image that contains a streaming layer.

Add partial.Manifests for lazy index access

---

pkg/v1/remote/image.go

The partial.ConfigLayer implementation needs to fetch the config blob, but we don't always need to do that (e.g. if we just need the digest).

Allow remote config layers to be lazy fetched

---

internal/cmd/edit.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/multi_write.go
pkg/v1/remote/multi_write_test.go
pkg/v1/remote/progress_test.go
pkg/v1/remote/pusher.go
pkg/v1/remote/write.go

The Pusher handles multiplexing across multiple repositories and deduplicating in-flight uploads. This removes the need to do an awkward dance around re-using auth handshakes by passing custom transports.
This also fixes limitations in remote.MultiWrite around streaming layers and multiple repositories.

Implement remote.Pusher

---

.ko/debug/.ko.yaml

:broom: This doesn't have `glibc` (like `base`) and just has the `busybox` necessities.
/kind cleanup

Cleanup: Switch the debug image to `cgr.dev/chainguard/busybox`

---

pkg/v1/remote/options.go

Fixes https://github.com/google/go-containerregistry/issues/1620

Retry net.ErrClosed

---

pkg/authn/k8schain/go.mod
pkg/authn/k8schain/go.sum
pkg/v1/empty/index.go
pkg/v1/mutate/mutate_test.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/referrers.go
pkg/v1/remote/referrers_test.go

Actually using this was cumbersome because it just returns a struct. This is a breaking change, but I don't think it's a huge deal because not too many people should be using this yet (and we're < 1.0.0).

Change return type of remote.Referrers

---

pkg/v1/google/keychain.go
pkg/v1/google/list.go

We dropped down to 1000 for the sake of ECR, but that doesn't make much sense, really.
Per https://cloud.google.com/artifact-registry/quotas#limits this will return up to 10k items.
Fixes https://github.com/google/go-containerregistry/issues/1643

gcrane: Use page size of 10,000 for googley things

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

Fixes https://github.com/google/go-containerregistry/issues/1595
cc @hasheddan

authn: Add NewConfigKeychain to load a config from explicit path

---

pkg/authn/keychain.go
pkg/authn/keychain_test.go

Reverts google/go-containerregistry#1603
Fixes https://github.com/google/go-containerregistry/issues/1662

Revert "authn: Add NewConfigKeychain to load a config from explicit path"

---

cmd/crane/cmd/push.go

Fixes https://github.com/google/go-containerregistry/issues/1514

crane push: print pushed ref@digest to stdout

---

cmd/crane/cmd/auth.go
cmd/crane/doc/crane_auth_logout.md

Fixes https://github.com/google/go-containerregistry/issues/1587
NB: This doesn't clear creds from Podman-configured auth, which `authn.DefaultKeychain` uses if a Docker config file isn't found. This might be confusing, but `crane auth login` doesn't use that either, so 🤷.
It might make more sense to always `login` using `DOCKER_CONFIG` and `logout` of Docker- or Podman-configured auth, feedback welcome.

add crane auth logout

---

.github/workflows/release.yml

* upgrade the slsa-verifier installer action to the latest v2.1.0
* use the `PROVENANCE` variable in the `Download Assets` stage to avoid having hardcoded naming
* [`attestation-name` is now deprecated, we should use `provenance-name` instead.](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#workflow-outputs)
PTAL @jonjohnsonjr @imjasonh

verify provenance

---

pkg/v1/daemon/image.go
pkg/v1/daemon/image_test.go
pkg/v1/daemon/options.go

https://github.com/google/go-containerregistry/pull/1121 allows `daemon.Image` to get a config name without exporting a tar file. This PR also generates a config file from `docker inspect` and `docker history` without exporting. Note that `RawConfigFile()` cannot be emulated by Docker Engine API as far as I know.
I referred to this implementation.
https://github.com/google/go-containerregistry/blob/0e8b581974ddd6879e02df540662c394921387e7/pkg/v1/mutate/image.go#L52
In addition, I changed some value receivers to pointer receivers since we should not mix receiver types.
>Don't mix receiver types. Choose either pointers or struct types for all available methods.
https://github.com/golang/go/wiki/CodeReviewComments#receiver-type

feat(daemon): generate config file from Docker Engine API

---

cmd/crane/cmd/catalog.go
cmd/crane/cmd/list.go
cmd/crane/doc/crane_catalog.md
pkg/v1/remote/catalog.go
pkg/v1/remote/descriptor.go
pkg/v1/remote/list.go
pkg/v1/remote/puller.go

This PR adds a Puller implementation and uses it in `crane ls` and `crane catalog` to stream results for each page.

Add remote.Puller

---

pkg/v1/random/image.go
pkg/v1/random/image_test.go
pkg/v1/random/index.go
pkg/v1/random/options.go

allow pkg/v1/random to accept a RNG source

---

.goreleaser.yml

Hi All 
love this code, I am using it on multiple architectures, and would like to add the PowerPC (ppc64le) architecture was not included (in the container image it is). 
This is to make the release consistent and ensure the ppc64le is available.
Thanks
Paul

Add ppc64le to .goreleaser.yml

---

pkg/v1/remote/write.go

DockerHub fails to auth if you ask for an invalid repository. Docs say this should not happen, but here we are.
Fixes https://github.com/google/go-containerregistry/issues/1679

Retry without mount if auth fails

---

pkg/name/registry.go

```
reg, _ := name.NewRegistry("foo.io")
repo := reg.Repo("bar").Tag("v3") // -> foo.io/bar:v3
```

add `registry.Repo("foo")`

---

cmd/crane/cmd/copy.go
cmd/crane/doc/crane_copy.md
pkg/crane/copy.go
pkg/crane/options.go

This will copy every tag in the src repo to dst.
This adds a --no-clobber flag that crane cp will respect that avoids overwriting an existing tag (at the time of command invocation).
Fixes https://github.com/google/go-containerregistry/issues/1355

Add --all-tags flag to crane cp

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md

Fixes https://github.com/google/go-containerregistry/issues/1542
I think this breaks callers that pass multiple key-value pairs in a single flag, and I'm ok with that.

Keep order of env in crane mutate

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md

Allows configuring of `ExposedPorts` via `mutate`.

Add `mutate` `--ports` option to set the exposed ports

---

pkg/v1/remote/fetcher.go
pkg/v1/remote/puller.go

This causes issues with broken registry implementations that 403 if you have requested push scopes even for pull operations.
See https://github.com/sigstore/cosign/issues/2973

Do not reuse pushers for pullers

---

pkg/v1/layout/write.go

If the rc is not closed (which happens when the files with the same digest already exists, due to the same image being added to the OCI layout directory twice) then 
```go
if s, err := os.Stat(file); err == nil && !s.IsDir() && (s.Size() == size || size == -1) {
return nil
}
```
will not close the io.ReadCloser leaking a goroutine [here](https://github.com/ktarplee/go-containerregistry/blob/009eea0d1c371a8bc3ba6898a2e88d6fab35eecf/internal/gzip/zip.go#L53)

fixed a goroutine leak

---

pkg/v1/remote/options.go

Previously, on X-Men: https://github.com/google/go-containerregistry/pull/1612
https://http.dev/522 says:
> HTTP response status code 522 Connection timed out is an unofficial server error that is specific to Cloudflare. This HTTP status code occurs when Cloudflare is unable to connect to the [origin](https://http.dev/origins) server due to a timeout.

retry HTTP 522 errors by default

---

pkg/v1/remote/fetcher.go

This adds a limit to the size of manifest that can get pulled.
Since the manifest is untrusted, this imposes a security risk to go-containerregistry users; If the size of the manifest is excessive compared to the ressources available on the machine running go-containerregistry, then a large manifest could cause Denial of Service by exhausting the memory of the machine.

Limit size of manifest

---

cmd/crane/cmd/auth.go
cmd/crane/doc/crane_auth.md
cmd/crane/doc/crane_auth_token.md
pkg/crane/options.go
pkg/crane/options_test.go
pkg/v1/remote/transport/bearer.go
pkg/v1/remote/transport/ping.go
pkg/v1/remote/transport/ping_test.go
pkg/v1/remote/transport/schemer.go
pkg/v1/remote/transport/transport.go
pkg/v1/remote/transport/transport_test.go

This makes it easier to just use curl.
Fixes https://github.com/google/go-containerregistry/issues/1470

Add crane auth token

---

pkg/v1/mutate/mutate.go

fixes #1646 
Based on PR by @Gnoale here - https://github.com/GoogleContainerTools/kaniko/pull/2538.  From the PR there - "It seems that the addendums slice index is incremented twice in cases there is an empty layer in the history" <-- this seems to lead to a possibly unexpected case where addendumIdx > len(addendums) which makes addendums[addendumIdx] panic
Adding context from the above issue in the description below vvv:
Currently in kaniko v1.9.2+ (which uses go-containerregistry v0.14.0+) a panic occurs when attempting to call go-containerregistry related to the code here:
https://github.com/google/go-containerregistry/blob/main/pkg/v1/mutate/mutate.go#L405
No errors using the same dockerfile with kaniko v1.9.1 which uses go-containerregistry v0.8.1-0.20220507185902-82405e5dfa82
The …

fix: add bounds checking to addendum layer mutations to prevent panic

---

cmd/crane/cmd/index.go

If we're trying to do things to a non-index, we should fail earlier.
Fixes: https://github.com/google/go-containerregistry/issues/1720
Before:
```
$ crane index filter docker.io/neuvector/scanner:latest --platform linux/amd64
Error: pulling docker.io/neuvector/scanner:latest: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
```
After:
```
$ crane index filter docker.io/neuvector/scanner:latest --platform linux/amd64
Error: expected docker.io/neuvector/scanner:latest to be index, got "application/vnd.docker.distribution.manifest.v2+json"
```

Surface better error messages in crane index

---

cmd/crane/cmd/append.go
cmd/crane/cmd/auth.go
cmd/crane/cmd/catalog.go
cmd/crane/cmd/config.go
cmd/crane/cmd/digest.go
cmd/crane/cmd/flatten.go
cmd/crane/cmd/index.go
cmd/crane/cmd/list.go
cmd/crane/cmd/manifest.go
cmd/crane/cmd/mutate.go
cmd/crane/cmd/push.go
cmd/crane/cmd/rebase.go
cmd/crane/cmd/validate.go
cmd/crane/cmd/version.go

When calling Crane programmatically, it's difficult to capture the output as it's written directly to stdout. This change uses Cobra's built-in support for changing stdout to an io.Writer.

crane: Respect cmd.OutOrStdout

---

pkg/v1/remote/descriptor.go
pkg/v1/remote/descriptor_test.go

The `TestGetSchema1` said it should fail based on media type while gave the unsupported MediaType. But it not return the true.
This fixes that problem by implementing an `Is()` function on `ErrSchema1`
so that `errors.Is()` can properly identify the error as an ErrSchema1.
Usage can now be: `errors.Is(err, &ErrSchema1{schema : "foo"})`

Make ErrSchema1 checkable via errors.Is()

---

cmd/crane/cmd/serve.go
pkg/registry/blobs.go
pkg/registry/blobs_disk.go
pkg/registry/blobs_disk_test.go
pkg/registry/registry.go

This only writes blobs to disk, and keeps manifests in memory. This is mostly a short-term bandaid to be able to store more/larger images while we work on a storage backend that writes to an OCI layout.
```
$ PORT=8080 go run ./cmd/crane registry serve --blobs-to-disk
2023/06/15 09:28:36 storing blobs in /var/folders/gw/86t1jg2109s5j8vzszj281kc0000gn/T/
2023/06/15 09:28:36 serving on port 8080
...
```
...do some pushes...
```
$ ls /var/folders/gw/86t1jg2109s5j8vzszj281kc0000gn/T/sha256:*
/var/folders/gw/86t1jg2109s5j8vzszj281kc0000gn/T/sha256:0d7529a407858eb4f76aa7087887a3d0e854a52dde475938080ae6c43297a929
/var/folders/gw/86t1jg2109s5j8vzszj281kc0000gn/T/sha256:31e352740f534f9ad170f75378a84fe453d6156e40700b882d737a8f4a6988a3
/var/folders/gw/86t1jg2109s5j8vzszj281kc0000gn/T/sha256:35d589f20 …
```

add --blobs-to-disk to 'crane registry serve'

---

cmd/crane/cmd/serve.go

This allows you to run `docker run -e PORT=1234 --name foo.local cgr.dev/chainguard/crane registry serve` and then `--link foo.local` to push to `foo.local:1234`.
Right now it only listens on the loopback interface, so unless it's run in a K8s-style pod with something that exposes and proxies things (e.g. like Knative / Cloud Run), it is inaccessible.

Drop localhost to support crane registry serve in a container

---

.github/workflows/release.yml

v0.16.0 release failed with 
```
line 94: field replacements not found in type config.Archive
```
https://github.com/google/go-containerregistry/actions/runs/5743578802/job/15568191187
That line hasn't changed in 3 years (https://github.com/google/go-containerregistry/commit/96cf69f03a3cf2d9c8850ce9d8e1f33da354826a) and the file hasn't changed since v0.15.2 where this wasn't a problem.
My only thinking is that the version of goreleaser changed from 1.18 to 1.19 since the v0.15.2 release (https://github.com/google/go-containerregistry/actions/runs/4996651209/job/13531871710)
So let's pin to 1.18 and see if it helps.

fix: pin to goreleaser v1.18 to unblock release

---

cmd/crane/cmd/validate.go
pkg/v1/validate/index.go

Now crane validate will validate the entire remote index, including that there are not any mismatched architectures.
If you pass a --platform flag, it will behave how it previously behaved.

:eagle: Validate index architectures match children :eagle:

---

pkg/v1/remote/write.go

Sometimes we know it, sometimes we don't. When we do, set it.

Set Content-Length for blob uploads

---

pkg/authn/keychain.go

The heuristic only works well if the upstream keychain doesn't do any caching. This is usually the case, but I've run into a couple situations where the hardcoded 5 minutes does not overlap well with certain cred helper implementations.
Undoing that wrap allows callers to set a time that makes sense for them. With the wrap, there's not any direct reference to DefaultKeychain, which feels... bad.

Don't wrap DefaultKeychain with refreshes

---

pkg/registry/blobs_disk.go
pkg/registry/blobs_disk_test.go

this change makes blob disk implementation mimic oci-layout for storing blobs.  This will speed up the pushing of 
oci-layout images on disk to the registry by providing the oci-layout image as the storage directory. 
Cross-ref: https://github.com/bazel-contrib/rules_oci/issues/365

fix: mimic oci-layout in diskblobhandler

---

cmd/crane/cmd/tag.go
cmd/crane/doc/crane_tag.md

Long help didn't explain that the command operates on remote images.

tag: add command explanation to the long help

---

cmd/crane/cmd/serve.go
cmd/crane/doc/crane_registry.md
cmd/crane/doc/crane_registry_serve.md

Cross-ref: https://github.com/bazel-contrib/rules_oci/issues/418

feat: allow port and disk path to be overriden

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml

saw the issue in the release notes, sorry about that.
FWIW I'm changing some stuff so goreleaser follows semver properly. 
Meanwhile, here's the fix, updating to goreleaser v1.19.

fix: goreleaser config

---

cmd/crane/cmd/push.go

Currently if you use `--image-refs` with `crane push`, the result reference doesn't get pushed if the manifest already exists, e.g.: 
```
2024/01/03 21:50:41 existing manifest: sha256:eef3b150e5e8d2b5b9ff7ed861ba503e0093139f595f9a549f614b64b6d6e1b2
2024/01/03 21:50:45 existing manifest: dev@sha256:eef3b150e5e8d2b5b9ff7ed861ba503e0093139f595f9a549f614b64b6d6e1b2
```
This change ensures that `crane push` always prints the full reference that was pushed.

Always print pushed digest in crane push

---

pkg/registry/blobs.go
pkg/registry/registry_test.go

This makes crane registry usable with registry explorer.

registry: Implement Range requests for blobs

---

cmd/crane/cmd/mutate.go
cmd/crane/doc/crane_mutate.md

This is a potential solution to #1918, and allows an image config's os/arch/variant/osversion to be set via `crane mutate myimage --set-platform linux/arm64`.
I chose `--set-platform`, since `--platform` is already in use as a persistent flag and a selector for the image to mutate.

feat: crane mutate platform

---

pkg/v1/layout/write.go

This is a potential solution for #1920, any feedback would be greatly appreciated.

Fix windows race condition when writing image with duplicate layers

---

cmd/crane/cmd/list.go
cmd/crane/doc/crane_ls.md

--omit-digest-tags is hard to remember and easy to typo. Support -O as an alias.

Add -O shorthand for --omit-digest-tags to crane.

---

pkg/v1/remote/referrers.go

As per the spec, [https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers) Content-Type header MUST be set to application/vnd.oci.image.index.v1+json.
This is important as GAR today (OCI 1.0) redirect "referrers" API call to the google console authentication page, and doing so the call return 200 OK  + content-type: text/html.
As the test use the registry package it is quite difficult to set a test explicitly on this part.

Referrer API must return correct Content-Type

---

cmd/crane/rebase.md
pkg/v1/remote/pusher.go
pkg/v1/remote/write.go
pkg/v1/remote/write_test.go

This used to do a blind write, but I "simplified" that when introducing remote.Pusher, which actually broke some things downstream of ggcr, so this restores that behavior.

Restore blind-write to remote.Put

---

pkg/v1/remote/transport/bearer.go

Make the bearer transport safe for use by multiple go-routines.
I found the following race conditions in my application, when using the transport in a client making multiple concurrent requests.
<details>
<summary>Data race backtraces</summary>
```
==================
WARNING: DATA RACE
Read at 0x00c00014c248 by goroutine 18:
github.com/google/go-containerregistry/pkg/v1/remote/transport.(*bearerTransport).RoundTrip()
/Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/bearer.go:163 +0x1fc
github.com/google/go-containerregistry/pkg/v1/remote/transport.(*Wrapper).RoundTrip()
/Users/fons/go/pkg/mod/github.com/google/go-containerregistry@v0.16.1/pkg/v1/remote/transport/transport.go:108 +0x4c
net/http.send()
/opt/local/lib/go/src/net/http/client.go:260 …
```

remote/transport: Make bearer transport go-routine-safe

---

internal/redact/redact.go

When a request URL contains basic auth information, that URL segment is ending up in the logs unredacted. Use the standard library's `Redacted()` function to fix this.

fix: redact.URL uses (*URL).Redacted to omit basic-auth password

---

pkg/v1/remote/referrers.go

While using the [remote.Referrers](https://github.com/google/go-containerregistry/blob/main/pkg/v1/remote/referrers.go#L36) function with the Artifactory registry, I found the function was unexpectedly failing. Digging into the error, I found the registry was returning a 406 instead of a 404 when the `remote.Referrers` function attempted to make a request to the referrers endpoint. Adding http.StatusNotAcceptable to the list of handled status codes in `transport.CheckError` fixed the problem for me.
This PR adds `http.StatusNotAcceptable` to the list of status codes handled by transport.CheckError. Since it is a 4XX error, `remote.Referrers` is able to fallback and try the manifests API endpoint.
I had filed https://github.com/google/go-containerregistry/issues/1962 asking about this …

Check for 406 status code when handling referrers API endpoint response

---

pkg/v1/mutate/mutate.go

Since this is computed lazily, the caller can modify the map, which would break the ~immutable nature of this API, so we create a defensive copy.

mutate: Create a defensive annotations copy

---

pkg/name/digest.go
pkg/name/registry.go
pkg/name/repository.go
pkg/name/tag.go
pkg/v1/hash.go

Various things in the Go ecosystem natively understand how to go from `string->Foo` if `Foo` implements `TextUnmarshaler`, and likewise from `Foo->string` if `Foo` implements `TextMarshaler`.
This adds TextMarshaler and JSONMarshaler support to `name.Registry`, `name.Repository`, `name.Tag`, and `name.Digest`, and makes `v1.Hash`'s implementation a bit more consistent with those (using `json.Unmarshal` instead of `strconv.Unquote`)

implement TextMarshaler/JSONMarshaler more consistently

---

.github/workflows/release.yml

Example failure: https://github.com/google/go-containerregistry/actions/runs/15148456191/job/42589682769

Update goreleaser permissions

---

hack/presubmit.sh
pkg/v1/daemon/image.go

I am removing `staticcheck` from presubmit.sh because it it out of sync with out fixed version of staticcheck used in  the Style action: https://github.com/google/go-containerregistry/blob/main/.github/workflows/style.yaml#L28

Fix ArgsEscaped lint directive
